### ISSUE TITLE
npm command does not run from child_process.exec on mac

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#100]
![image](https://cloud.githubusercontent.com/assets/2189477/17220938/d64a98ae-54f1-11e6-8e48-98fb76afa358.png)

likely related to https://discuss.atom.io/t/how-to-execute-node-js-child-process-from-package/4880/3

workaround: call npm command from /usr/local/bin/npm on mac, and `npm` on windows

**Comment by JeroenVinke** [comment]
we will likely bump into this for the gulp task runner functionality as well

**Comment by adriatic** [comment]
I do not find this being a hack as we are dealing with very specific OS functionality that cannot be abstracted to same OS independent layer.

I am assuming that "calling `npm` on windows" means that you use windows envronment's `path` variable to find where npm lives

**Comment by JeroenVinke** [comment]
> I am assuming that "calling npm on windows" means that you use windows envronment's path variable to find where npm lives

Yes

**Comment by JeroenVinke** [comment]
we can try to run `npm` from mac again as https://github.com/sindresorhus/fix-path seems to help

**Comment by vegarringdal** [comment]
Info
I didnt get any issues running on mac npm when using spawn.
(only testet with the monetery-dev, the one that downloads everything install npm/jspm)

**Comment by JeroenVinke** [comment]
this issue only presented itself in the deployed app (when using the installer). the path environment variable has a different value when running via `gulp watch` than when you run it outside of a terminal. I think [this plugin](https://github.com/sindresorhus/fix-path) fixed it though
