### ISSUE TITLE
enhancing monterey "create application" wizard

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#102]
### _Plan for this article_

_Present the current project creation wizard in supported situations - with Nik's critical comments._

_Summarize several existing project creation wizards._

_Nik's proposal for a new creation wizard_

_Discussion (Rob, Jeroen, Daniel - maybe Charles if we can resurrect him)._
***

**Comment by adriatic** [comment]
### Current project creation wizard

The wizard is invoked by a click on the `Create new Aurelia application` button:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/17307931/78ea6088-5805-11e6-9530-52aee7ec9778.png"></img>
 <br><br>
Image 1
</p>

resulting with:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/17308144/7bbdc2f4-5806-11e6-96e3-5072e730d31d.png"></img>
 <br><br>
Image 2
</p>

**Comment by adriatic** [comment]
### Visual Studio

**Comment by adriatic** [comment]
### Webstorm

**Comment by adriatic** [comment]
Let's discuss whether you are happy with the ideas presented above. If the answer is yes, I will present my proposal for creating Monterey's wizard. Note that we would have to agree to use Aurelia / KendoUI to do that - and given how light-weight the new KendoUI bridge could be, this should not be a problem at all.

**Comment by EisenbergEffect** [comment]
Just chiming in here real quick. With respect to the Aurelia CLI, we have a UI abstraction. It would be great if any visual tool could just call the CLI and let the CLI drive the wizard. In that way, if we add new capabilities or change the wizard around, the GUI tool will always be in sync.

**Comment by adriatic** [comment]
We are aware of that and using this feature already (it is possible that the released version is a bit behind the master branch). Check the Image 2 **[above](https://github.com/monterey-framework/monterey/issues/102#issuecomment-236702708)**

**Comment by JeroenVinke** [comment]
After discussing this with @adriatic we would like to propose two changes.

The first change is going to allow users to always see the selected project template:

![img](http://i.imgur.com/rHaxat6.png)

And the second change involves the last screen of the wizard, where the user can choose what to do next:

![img](https://files.gitter.im/JeroenVinke/EHL7/blob)

The selected actions are executed in sequence after clicking the finish button. The goal of this change is to reduce the amount of steps between creating and running the project

Whenever a project gets opened (or created) in Monterey, all Monterey plugins ([link](https://github.com/monterey-framework/monterey/tree/master/app/src/plugins)) are asked to evaluate the project. For example, the NPM plugin [detects](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/npm/index.ts#L32-L54) the package.json. JSPM looks in package.json for a `jspm` property. We don't have an aurelia-cli monterey plugin yet, but it's going to look in `aurelia.json` for information

So Monterey has a pretty good idea of what the project looks like (and as we create more plugins it will know more and more). Based on that information we can create the list of actions shown [here](https://files.gitter.im/JeroenVinke/EHL7/blob)

**Comment by JeroenVinke** [comment]
Created separate issues to track the implementation
