### ISSUE TITLE
Can we use hyperterm in Monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#105]
Without understanding how Monterey's **current integrated console** works

![image](https://cloud.githubusercontent.com/assets/2712405/17273727/c14995ca-568d-11e6-97c9-6cca94f518e6.png)

I am suggesting to evaluate https://github.com/zeit/hyperterm

**Comment by JeroenVinke** [comment]
The black square that is highlighted is not meant to be a command line, it outputs log messages from tasks in monterey and a task is not always the execution of a command line command

I am a bit hesitant to integrate a terminal in monterey given the fact that each developer could have a personal preference. Lets wait a bit as we may decide that something like this is useful for our gulp task runner / `au run` (to start aurelia cli project)

I believe hyperterm is not compatible yet for all three platforms so we need to look for something else

**Comment by adriatic** [comment]
> I am a bit hesitant to integrate a terminal in monterey given the fact that each developer could have a personal preference

That is a very valid concern that we should keep in mind all the time,

**Comment by Thanood** [comment]
We could make it a tile. From a user's point of view I can remove it if my preference is something else.

**Comment by JeroenVinke** [comment]
Yes, and i've been thinking about whether or not it has value if we convert [this](https://cloud.githubusercontent.com/assets/2712405/17273727/c14995ca-568d-11e6-97c9-6cca94f518e6.png) into a console. Even though the tasks we let the task-manager execute aren't always commands, it would be cool if you could execute a command quickly after a task has finished. 

For example, you click on the `install` button on the jspm screen, the task manager shows up and you wait for it to finish. Then you want to install a plugin (`jspm install x`). Now you need to close the taskmanager, go back to the tiles screen, click the terminal button of your choice and run the command. If we convert [this](https://cloud.githubusercontent.com/assets/2712405/17273727/c14995ca-568d-11e6-97c9-6cca94f518e6.png) into a console, you can enter a command right after `jspm install` is finished. I'm sure there will be other places in monterey where you may want to execute a command quickly.

**Comment by Thanood** [comment]
Hyperterm (https://hyperterm.org/) is html/js based.

I'm not a fan of having real a consoles in the task manager. You would have one console per task, right?
What if the task output looks *convincingly* like a real terminal but when you click on it to enter the next commad, the real console opens.

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/17289393/cfc750e0-57d9-11e6-9982-e4392e838b12.png)

:(

> I'm not a fan of having real a consoles in the task manager. You would have one console per task, right?
What if the task output looks convincingly like a real terminal but when you click on it to enter the next command, the real console opens.

Good one, that should be possible. We are doing this to increase performance, right?

**Comment by Thanood** [comment]
I'm pretty sure that the "not for windows/linux" line refers to the *application*, not the library.
On the other hand I don't find anything on using this as a library - but I only had a brief look.

> We are doing this to increase performance, right?

Yes, right. :smile:

**Comment by adriatic** [comment]
After reading all comments, I remain confused - my proposal to consider using this is completely lined up with @JeroenVinke's comment

> It would be cool if you could execute a command quickly after a task has finished.

We might constrain user's input so that he/she cannot stop the execution with a Ctrl-C sequence (stopping anything should take place at proper Monterey's level), but having this "black rectangle" be bidirectional could have its appeal.

So, I am not sure about doing it to increasing performance, unless the ability to intervene at this level **after** the task ended is considered as a performance increase :smile:

**Comment by JeroenVinke** [comment]
We will get better performance if we do not automatically initialize console's (and don't initialize them for every task). @Thanood's idea is to only start a console when the black square is clicked. But we'll see if this is necessary when we start implementing this

**Comment by adriatic** [comment]
> only start a console when the black square is clicked.

?? - this does not seem intuitive, it can cause a confusion. If starting the real console is time expensive, I would rather see a `View ouput` button to open the console instead to have to click on an existing but fake console.

**Comment by vegarringdal** [comment]
Played around making a console/terminal plugin/tile
the PR #126 scrolls automatically to bottom as updated come in, video was made before I added that.
[video](https://drive.google.com/file/d/0B_wM5SJf8IXoOFJaWkZpcjg0Njg/view)

**Comment by JeroenVinke** [comment]
Implemented by @vegarringdal
