### ISSUE TITLE
Implement aurelia menu for monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#106]
We should at minimum have the help menu with several menu-items like

- on-line documentation
- check for updates
- report a problem
- ...

This list was not created after a deep thinking sessions - we need to discuss it. I am only sure that the online documentation will be in GitBooks

**Comment by JeroenVinke** [comment]
Question: should we build this in monterey and not the menu (we both missed the menu in mac). There already is a support button in the taskbar that leads to this github repository so can we extend that?

**Comment by JeroenVinke** [comment]
This way we can use aurelia to create a nice UI, and perhaps we can create a registry (https://github.com/monterey-framework/registries?files=1) with a collection of gitbooks that drives the UI

**Comment by adriatic** [comment]
> should we build this in monterey and not the menu (we both missed the menu in mac):

Can you expand this a bit (_in monterey and not the menu_)?

I m also curious about the concept of using a "registry" of UI parts that are "composed" into the application. That seems like a trip into the future that nobody has done before (assuming that I get your drift)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/17276510/11cd9d9a-572c-11e6-8637-3b0a92272b43.png)

**Comment by adriatic** [comment]
I understand and think that this is a better approach

**Comment by JeroenVinke** [comment]
Also needs to show version of monterey

**Comment by adriatic** [comment]
I believe that most of this information (if not all) would be good to have

![image](https://cloud.githubusercontent.com/assets/2712405/17307749/b00d6f7a-5804-11e6-94a5-9342fdd5fbd5.png)

Note that click on the About menu item results with

![image](https://cloud.githubusercontent.com/assets/2712405/17307804/e081b490-5804-11e6-90fe-ef8acf7afb54.png)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/17449522/7276fa3c-5b5b-11e6-8916-60efd4085f8a.png)

![image](https://cloud.githubusercontent.com/assets/2189477/17449532/7b15e4fa-5b5b-11e6-8ca7-f9d8430519a3.png)

![image](https://cloud.githubusercontent.com/assets/2189477/17449537/812b7bc0-5b5b-11e6-9d7a-808872c2c823.png)

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/registries/blob/gh-pages/gitbooks.json is used in the popup, so we can edit the json and it'll show up in monterey

**Comment by adriatic** [comment]
It took me a while to find the `Support` item on the footer, which is being used to open that pop-up. It does not seem intuitive to look for Monterey version there.

**Comment by JeroenVinke** [comment]
I agree

**Comment by JeroenVinke** [comment]
What about an "about" item in the taskbar. That would open a popup with info about general info about monterey and the version

**Comment by adriatic** [comment]
Much better - as asking to see this information requires to run a task of some kind

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/17455438/fc7639d0-5bb7-11e6-890c-bc7ee44a427d.png)
