### ISSUE TITLE
Nuclide and monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#108]
https://nuclide.io/docs/features/remote/

I am not at all sure how to relate these two - but would like to keep this issue open

**Comment by JeroenVinke** [comment]
I have added this to our [gitbook](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/introduction/montereyfuture_evolution.html) and we can create an issue for implementation when we decide to start working on it

**Comment by adriatic** [comment]
What is "this" in the above comment? - the reference https://nuclide.io/docs/features/remote/ ?

**Comment by JeroenVinke** [comment]
Yes, we are thinking of doing something with nuclide but we are not sure exactly how, what or when

**Comment by adriatic** [comment]
Perfect, thanks
