### ISSUE TITLE
Create JSPM plugin

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#11]
Should detect config.js file in similar fashion as the npm plugin detects package.json files. The plugin should add a JSPM tile for the jspm package manager screen.

**Comment by Thanood** [comment]
I'd like to try that. :smile:

**Comment by Thanood** [comment]
@JeroenVinke Is there a "execution order" in place?
I mean can I expect an already parsed `package.json` before JSPM plugin detects JSPM or will I have to do that myself?

**Comment by JeroenVinke** [comment]
As long as the npm plugin has registered itseld before the jspm plugin then the npm plugin will have retrieved the package.json path, which can be found on any project object

**Comment by Thanood** [comment]
First take..

![image](https://cloud.githubusercontent.com/assets/677826/16545067/4dd71010-411e-11e6-8b6f-86678aa26c3c.png)

**Comment by JeroenVinke** [comment]
Awesome. What do you think about https://github.com/monterey-framework/monterey/issues/13? Automatic detection is preferred, but I dont think we should to force the user into selecting a config.js when automatic detection fails.

**Comment by Thanood** [comment]
So how would I hide the JSPM tile for projects not using JSPM? :smile:

**Comment by Thanood** [comment]
I'd say use a `hide` or `notRelevant` property. So the plugin author decides if the plugin is relevant but you can still show the tiles if a user says "show them".

**Comment by Thanood** [comment]
Maybe used like this:

```javascript
import {useView, inject} from 'aurelia-framework';
import {Main}            from '../../main/main';

@inject(Main)
@useView('plugins/default-tile.html')
export class Tile {
  constructor(main) {
    this.title = 'JSPM';
    this.isHidden = true;
    this.main = main;
  }

  activate(model) {
    this.project = model.project;
    if (this.project.isUsingJSPM) {
      this.isHidden = false;
    }
  }

  onClick() {
    this.main.activateScreen('plugins/jspm/screen');
  }
}
```

**Comment by Thanood** [comment]
Oops, that's the answer to a different question.
Well, I'm not sure. If we detect jspm there should be a `config.js` but the project could also be in a state in which the user would usually run `jspm init`.

**Comment by JeroenVinke** [comment]
I have never seen a setup where there is a jspm section in package.json but there is no config.js. Am I seeing this right?

**Comment by JeroenVinke** [comment]
Or do you mean a state where jspm has been initialized once (so there is a jspm section in package.json) but the user has removed config.js

**Comment by Thanood** [comment]
You're right. When there`s a `jspm` section, there should probably be a `config.js`.
But your last comment can also be true. :smile:
For whatever reason, the `config.js` could have been deleted.

**Comment by JeroenVinke** [comment]
Besides, the config file has been renamed in jspm 0.17

**Comment by adriatic** [comment]
The "loose" relationship between `package.json` and `config.js`, officially managed by `jspm` should not be ours to fix - certainly not at this early time in monterey's life. The rules are simple:

If `package,json` exists and `config.js` does not (we certainly do have to establish that fact) then either `jspn install` was never run or somebody deleted `config.js`. We should generate the error message with this explanation.

**Comment by JeroenVinke** [comment]
Yep, not ours to fix. I think as long as there is a jspm section in package.json we can safely assume that JSPM is used in that project.

**Comment by vegarringdal** [comment]
Fix for the jspm install, so it works for more then 1 project.
@JeroenVinke you might want it done with other naming, hope it helps :-)

**1:Monterey Repo**
In monterey/app install this module```npm install electron-remote --save```

---

**2:Monterey-electron-pal Repo**
Add new file, ```jspmTask.js```

Add code:
````javascript
exports.install = function(jspmOptions){
  "use strict";
  return new Promise((resolve, reject) => {
    let jspm = require("jspm");
    jspm.setPackagePath(jspmOptions.workingDirectory);
    jspm.install(true, jspmOptions).then(() => {
      resolve()
    }).catch(error => {
      reject(error);
    });
  });

};


};
```




---

**3:Monterey-electron-pal Repo**
Edit the jspm.js:
```javascript
const requireTaskPool = System._nodeRequire("electron-remote").requireTaskPool;
const jspmTaskPath = System._nodeRequire.resolve(__dirname + '/jspmTask.js');

export class JSPM {
  isLoaded = false;

  install (packages, options) {

    let jspmOptions = options.jspmOptions || {};

    let originalWorkingDirectory = process.cwd();
    process.chdir(jspmOptions.workingDirectory || process.cwd());
    this._log(options, `chdir: ${jspmOptions.workingDirectory}`);

    this._log(options, "installing...");
    return new Promise((resolve, reject) => {
      let jspmModule = requireTaskPool(jspmTaskPath);
      jspmModule.install(jspmOptions).then(()=> {
        this._log(options, "finished installing...");
        process.chdir(originalWorkingDirectory);
        resolve();
      }).catch((error)=>{
        reject(error);
      });
    }).catch(error => {
      this._log(options, "error while installing...", error);
        process.chdir(originalWorkingDirectory);
    });
  }

  _log(options, msg) {
    if (options.logCallback) {
      options.logCallback({level: 'custom', message: msg });
    }
  }
  
}

````

**Comment by JeroenVinke** [comment]
hmm, requireTaskPool doesn't seem to allow function callbacks to be passed to `jspmTask.js. This is necessary to log progress and output of `jspm install`. But it seems that errors thrown in `jspmTask.js` are catchable in the main process. So what we can do is to throw an error when JSPM logs an `err`, and when this does not happen we can assume that the process finished without errors.

**Comment by vegarringdal** [comment]
You can prb use the built in messaging in electron too.

**Comment by JeroenVinke** [comment]
@vegarringdal would you mind to try that out? then we can probably use requireTaskPool for other more CPU intensive tasks

**Comment by vegarringdal** [comment]
Yes, I can have a try at it later, great if you add it like you want it for now so can I work on that, since old does not work for more then 1 project

**Comment by JeroenVinke** [comment]
@vegarringdal it's all in master

**Comment by vegarringdal** [comment]
Great :-)
I'll work on it later until it works then :-)

**Comment by JeroenVinke** [comment]
The plugin is done
