### ISSUE TITLE
Teach monterey to create package.json

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#112]
Based on the experience from **[manual bridge upgrade process](https://github.com/monterey-framework/monterey/issues/101)** (which I want to expand some more), we could assume that Monterey can completely build an application from scratch (as different from today's approach of using the pre-built GitHub resident templates) just by being clever enough to create  a "good enough" **`package.json`**.

At the moment, the above assumption is true in the context of using **`jspm`** - as I do not know enough about **`RequireJS`** and **`webpack`** to make a similar claim.

___More information to be written here.___

**Comment by JeroenVinke** [comment]
Aurelia-cli does this already, so we probably don't want to do this in Monterey as well

**Comment by JeroenVinke** [comment]
Please reopen if you disagree. Aurelia-cli creates a package.json file based on the input of the user. And as jspm/webpack support will be coming I don't think why we need to do the same thing in monterey as well

**Comment by adriatic** [comment]
I am fine with this - if we can re-use this functionality in situations where Aurelia-CLI is not specifically chosen by Monterey user
