### ISSUE TITLE
Look into auto updates

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#115]
Need to see if this works

**Comment by adriatic** [comment]
I believe that you wrote this issue as a remainder to yourself as it references nothing I could test

**Comment by JeroenVinke** [comment]
Yes I did

**Comment by JeroenVinke** [comment]
Tried this out (by changing the version of package.json to something older than the current version on github), running `gulp run dist`  (which builds the installer to the `dist/monterey` folder) and then running the installer. It found the newer version, downloaded it and said in a [toastr](http://codeseven.github.io/toastr/demo.html) message that the update would be installed as soon as the program exited. after closing and opening monterey again it showed the new version

will document this as part of https://github.com/monterey-framework/monterey/issues/138

**Comment by adriatic** [comment]
### That is a major deal
