### ISSUE TITLE
Better error msg for when github user/pass is wrong

### ISSUE THREAD

**Issue by vegarringdal** [monterey-framework/monterey#116]
Got this error today when trying to test monterey

![image](https://cloud.githubusercontent.com/assets/2901416/17342786/0cf2d36e-58fb-11e6-8280-1787a45145e3.png)

In devconsole I see this error:
 ```https://api.github.com/repos/aurelia/skeleton-navigation/releases/latest 401 (Unauthorized)```

So we need to add better error handling to this part
Reason why I get it is since Ive added 2 factor authentication to my github account   ( I think )

**Comment by vegarringdal** [comment]
Managed to get it working with access token as password, but needed to restart the app for it to actually get download from github working

**Comment by vegarringdal** [comment]
Info
Cleared my github credentials, and could still create project, so looks like this does not kick in before next app start

**Comment by vegarringdal** [comment]
Quickfix suggestion:
https://github.com/monterey-framework/monterey/blob/master/app/src/shared/github-api.ts#L33
Replace ```return response.json();```
with this:
```
 if (response.status === 401) {
        throw {message:`Github returned '${response.statusText}', please check you credentials and try again`};
      } else {
        return response.json();
      }
```
Then user gets this response
![image](https://cloud.githubusercontent.com/assets/2901416/17345986/fc47ddb2-5908-11e6-94b0-543990cf5737.png)

**Comment by vegarringdal** [comment]
maybe this will be more safe...

```

      if (response.status === 200) {
        return response.json();
      } else {
        if (response.status === 401) {
          throw {message:`Github returned ${response.statusText}, please check you credentials and try again`};
        } else {
          throw {message:`Github returned ${response.statusText}`};
        }
      }
```

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/pull/118
