### ISSUE TITLE
JSPM package manager screen

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#12]
This screen can show a list of jspm dependencies (name, current version, latest version) and you should be able to update selected dependencies. Also, "jspm install" should also be possible

**Comment by JeroenVinke** [comment]
@vegarringdal can you share your findings of when you tried to use jspm from nodejs? Code snippets would help too.

**Comment by Thanood** [comment]
I'd like to try that, too. That is if @vegarringdal doesn't want to take it.

**Comment by vegarringdal** [comment]
Not home atm, but here is the api

http://jspm.io/docs/api.html

I just tried testing from electron, and it work on the main project running, but we need to have it working on the projects we add/make.

**Comment by vegarringdal** [comment]
Ill install the Monterey and give this a try after i figure out why my grid isnt working at all in the aurelia-cli project
See you have done a lot of updates, keep up the good work :+1: 
Lets hope i understand some of it :-)

@JeroenVinke 
Are we going to go typescript on it?
*Reason why I ask it that the more code you trow into it, the more pain it will be to convert in the end, if typescript is the way we want to go.*

Are we going to switch to absolute positioning in css?
*Reason why I ask is because its a desktop application. Not a web app.*

**Comment by JeroenVinke** [comment]
> Are we going to go typescript on it?

Yes. @adriatic when can we switch to typescript?

> Are we going to switch to absolute positioning in css?
Reason why I ask is because its a desktop application. Not a web app.

Only when we really have to. For example, the main screen uses absolute positioning right now (just for two columns) but we may eventually make this responsive. That way you could make the Monterey screen smaller and keep it next to a different window (the browser / your editor perhaps).

**Comment by adriatic** [comment]
### On switching to typescript

My preference would be **not to switch to typescript** for this initial monterey app. By saying **initial**, I mean two things:

1. Everyone at this point (with noted exception of Daniel) is more or less a typescript noob (is this the right term to describe a novice?), so developing an unknown (more or less that is true for all of use, with **maybe** noted exception of Jeroen) application in an unknown language seems like challenging our fate.

2. It **should** be obvious to all of us that what we are developing now **is not** the code we will release. We will likely use it in the **preview mode** to gain users feedback - and then we will start writing the version 2 - likely using typescript.

Unless we do not have the proper sense for common sense, rewriting an app over has a lot better influence on world's entropy that having hundreds of thousands of our future users use the premature version of monterey.

**Comment by JeroenVinke** [comment]
> Unless we do not have the proper sense for common sense, rewriting and app over has a lot better influence on world's entropy that having hundreds of thousands of our future users use the premature version of monterey.

To be honest, I was not planning to rewrite Monterey. We may do that if we decide that the current monterey app is completely useless (and that refactoring will not solve the issue), but until that time I do not see why we should consider this app as "preview". The consequence of labeling this as preview is that the quality of the code will be worse, because you are not going to going to build a feature ready for use in production when you know that you will rewrite it again in the near future.

"Switching to typescript" sounds like a huge task that would warrant a rewrite, but that is not the case. Typescript is just a superset of javascript and we would just need to rename `.js` to `.ts` and perhaps fix a couple of compilation errors.

**Comment by adriatic** [comment]
> To be honest, I was not planning to rewrite Monterey

I am glad that I used forms like "it **should**", "we **might**, etc - as my role in this project is not to declare how to do things. Jeroen is the boss in the real sense of this word in this specific context. To illustrate the difference between "this specific context" and other contexts, if Jeroen asks me to sell my house - I will flatly refuse :-)

With this said, I would hope that
- Jeroen will declare the time of the switch
- Daniel will advise on how the initial code will be converted 

Now, my **personal concern**: my reason for switching to TypeScript is to ensure better team work -where compile time type checking, wide use of interfaces, refactoring  and all other features listed [here](https://www.typescriptlang.org/). Using these features from the start requires a lot more than just renaming existing files.

As I am not the boss in the classical sense (person who can create a very strong reasons (job and salary) to ensure compliance), my personal concerns do not have impact on common decisions.However I would like to see a discussion on how deep involvement of TypeScript we want to have

**Comment by vegarringdal** [comment]
@JeroenVinke 
* quickfix for running jspm install on a project
* so if you copy the npm module you have and rename everything to jspm and replace the install function with this one it will work on windows..

Btw the task are running at the same time, maybe having a queue withing a project would be better?




```javascript
  install() {
    if (this._installing) {
      alert('Already installing');
      return;
    }

    this._installing = true;

    let task = {
      title: `jspm install of '${this.project.name}'`,
      estimation: 'This could take minutes to complete',
      logs: []
    };

    let jspmInstall = () => {
      return new Promise((resolve, reject) => {
        let exec = require('child_process').exec;
        let path = this.project.packageJSONPath.replace('/package.json', ''); //<-@jeroen check path.. something is wrong with it...

        //todo, check os and use correct commands-> this works for windows
        let cmd = 'cd ' + path + ' &&  jspm install';


        let child = exec(cmd, function (error, stdout, stderr) {
          if (error !== null) {
            reject('exec error: ' + error);
          } else {
            resolve(stdout)
          }
        });
      });
    };

    let promise = jspmInstall().then(()=> {
      this._installing = false;
    });

    task.promise = promise;

    this.taskManager.addTask(task);
  }


```

**Comment by JeroenVinke** [comment]
@vegarringdal instead of running a cmd of `jspm install` i'd like to know if (and how) we can call JSPM directly, like 

```
// pseudo code, haven't tried this at all
const install = require('jspm').install;

install();
```

can you try to see if you can get it working that way? the install function exists here: https://github.com/jspm/jspm-cli/blob/master/lib/install.js#L79

**Comment by vegarringdal** [comment]
Ill give it a new try later.
Got it to work yesterdaywith setPackagePath but main problem when I did that was that it messed up the entire monterey project, so that keept throwing errors and pretty much broke it.

**Comment by adriatic** [comment]
I like the [direction](https://github.com/monterey-framework/monterey/issues/12#issuecomment-230306259) this is going ...

**Comment by JeroenVinke** [comment]
@vegarringdal thanks, if you are unable to fix the errors you can post it here and we can help you in figuring it out

**Comment by adriatic** [comment]
It would be great if the jspm could be used in the **what if** scenario - the opposite of what we have now by invoking `jspm install` in the console. Using API we could get a warnings about things that will go wrong if we really to that installation, without having to wait for three minutes to see it - and worse of, there is no undo for `jspm install`.

This is not meant to be implemented in the initial version

**Comment by JeroenVinke** [comment]
It seems that JSPM logs can be received using [this function](https://github.com/brillout/gulp-jspm/blob/master/index.js#L14-L21)

**Comment by vegarringdal** [comment]
This kinda works, I get to install jspm on the project I set with ```jspm.setPackagePath(path)```
Only problem is that I will not be able to change it after, so it pretty much breakes monterey project after
But Ill play more with it to see what I can figure out. have some ideas in my head I want to try

(copy of npm folder, just replaced everything to jspm
```
install() {
    if (this._installing) {
      alert('Already installing');
      return;
    }

    this._installing = true;

    let task = {
      title: `jspm install of '${this.project.name}'`,
      estimation: 'This could take minutes to complete',
      logs: []
    };


    var path = this.project.packageJSONPath.replace('/package.json', '');

    let jspm = require("./node_modules/jspm");
    jspm.setPackagePath(path); //<-- running this code messes up the monterey project
    let promise = jspm.install(true, {lock:false}).then(()=>{
      this._installing = false;
    });
    

    task.promise = promise;

    this.taskManager.addTask(task);
  }
```

**Comment by JeroenVinke** [comment]
:+1:  you could also try and look in the JSPM codebase to figure out what `setPackagePath` actually does

**Comment by vegarringdal** [comment]
Here is one solution, that looks to be stable when I try on different projects I created.
Btw, we need to set name in package.json to name of project when installing from the github skeletons, else they all have same name.


Install ```npm install electron-remote --save```


>jspm.js on root of monterey, you can put it where you want.

```
exports.install = function(path){
  "use strict";
  let jspm = require("jspm");
  jspm.setPackagePath(path); 
  let promise = jspm.install(true, {lock:false}).then(()=>{
    return "done"
  });
  
};

```

> screen.js -> jspm (copy of npm plugin)

```
 install() {
    if (this._installing) {
      alert('Already installing');
      return;
    }

    //this._installing = true;

    let task = {
      title: `jspm install of '${this.project.name}'`,
      estimation: 'This could take minutes to complete',
      logs: []
    };


    let installJspm = ()=> {
      return new Promise((resolve, reject) => {

          let jspmModule = requireTaskPool(require.resolve(__dirname + '/jspm.js'));
          let path = this.project.packageJSONPath.replace('/package.json', '');

          jspmModule.install(path).then((result)=> {
            this._installing = false;
              resolve();
          });
      });
    };

    task.promise = installJspm();


    this.taskManager.addTask(task);
  }

```

**Comment by JeroenVinke** [comment]
Nice :)

**Comment by vegarringdal** [comment]
I was hoping we could do it with web worker, but didnt have access to require there
