### ISSUE TITLE
Change UI of project scaffolding screen

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#121]
![image](https://cloud.githubusercontent.com/assets/2189477/17432919/195c3f92-5b02-11e6-83fc-31e64c29a864.png)

**Comment by vegarringdal** [comment]
Looks a lot better, will also help knowing what you selected to begin with

**Comment by JeroenVinke** [comment]
sorry what do you mean exactly?

**Comment by vegarringdal** [comment]
you will see what you selected on the right, or do you remove that part?

**Comment by JeroenVinke** [comment]
you'll select whatever project template you want to use on the left side, and go through the wizard on the right side to configure settings for the selected project template. the idea behind it is that you can always see the project template you selected throughout the wizard

**Comment by vegarringdal** [comment]
great
