### ISSUE TITLE
Allow for setting the npm registry in preferences screen

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#126]
not sure if this is caused by monterey, but registering it here anyway

![image](https://cloud.githubusercontent.com/assets/2189477/17463765/c9a8457c-5ccd-11e6-943b-43b931eac194.png)

2 commands (found [here](https://github.com/npm/npm/issues/10579)) seems to fix it:
$ npm config set registry http://registry.npmjs.org/
$ npm config set strict-ssl false

**Comment by adriatic** [comment]
I believe that these commands should be set and maintained in the "preferences dialog"
