### ISSUE TITLE
running the clone of the current monterey fails

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#128]
Here is what I got after making a fresh clone and building it by

``` 
npm install
cd app
npm install && jspm install
gulp watch
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/twbs/bootstrap@3.3.6/css/bootstrap.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/work/monterey-framework/monterey/app/jspm_packages/system.src.js Failed to load resource: net::ERR_FILE_NOT_FOUND
config.js:1 Uncaught TypeError: System.config is not a function
index.html:26 Uncaught TypeError: System.import is not a function
C:\work\monterey-framework\monterey\app\node_modules\electron-connect\lib\client.js:27 [2016-08-09T00:51:58.053Z] [electron-connect] [client: 1] connected server
```

Being a good citizen (read working on KendoUI beta) I did not try to fix this.

**Comment by JeroenVinke** [comment]
Interestingly when I removed jspm_packages and ran jspm install it mentioned this:

```
warn Error on download for github:twbs/bootstrap

     GitHub rate limit reached, with authentication enabled.
     The rate limit will reset in 40 minutes.

err  Error downloading github:twbs/bootstrap.
```

resulting in the same error when running `gulp watch`

![image](https://cloud.githubusercontent.com/assets/2189477/17507965/c78f238c-5e12-11e6-944b-fc52b0294e18.png)

**Comment by JeroenVinke** [comment]
right, so without any idea why the rate limit would be reached I decided to create an access token for JSPM. each access token has its own rate limit

1. https://github.com/settings/tokens
2. "Generate new token"
3. enable public_repo scope
4. copy access token and store it somewhere safe
5. jspm registry config github
6. yes
7. paste access token
8. run jspm install again

this time I did not get that error

**Comment by adriatic** [comment]
I will contact GitHub support with this question

**Comment by JeroenVinke** [comment]
I haven't seen this anymore so closing it until this resurfaces

**Comment by adriatic** [comment]
I did not contact GitHub (could not phrase the question in a meaningful way) and I also did not run into this since the first time
