### ISSUE TITLE
Show/hide relevant tiles

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#13]
What happens if the jspm plugin does not detect a config.js file when the project gets added to monterey, but it is in fact a jspm project. Since the jspm plugin did not detect config.js, the jspm tile isnt visible. So a way to toggle relevant plugins to make the JSPM tile visible anyway, so that the jspm plugin can be provided with enough information to work would be nice

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16544232/5ed6661a-40fe-11e6-808d-53d07a61f8cf.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16544237/7245d2b2-40fe-11e6-89c5-f9de43861449.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16544239/7ae74a4a-40fe-11e6-960f-f1b0fc0defb5.png)

**Comment by JeroenVinke** [comment]
Related to https://github.com/monterey-framework/shell/issues/13

**Comment by JeroenVinke** [comment]
@Thanood can we extend https://github.com/monterey-framework/monterey/blob/master/src/plugins/app-launcher/index.js#L11 with a relevant boolean argument?

**Comment by Thanood** [comment]
Sure, we can do that.

**Comment by JeroenVinke** [comment]
Using the app launcher tile as an example:

![image](https://cloud.githubusercontent.com/assets/2189477/16567681/9b6fb120-4221-11e6-887c-f1f421743cc8.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16567696/af7c2d06-4221-11e6-9aba-3708b4b9f4ef.png)

@Thanood perhaps we should merge your stuff to master so you can use this feature for the jspm plugin

The `getTiles()` function now gets a `showIrrelevant` bool from which you can determine to show the jspm tile or not:

```
  getTiles(project, showIrrelevant) {
    let tiles = [];
    if (showIrrelevant) {
      tiles.push({
        viewModel: 'plugins/app-launcher/editor-tile',
        model: { relevant: false }
      });
     return tiles;
  }
```

**Comment by Thanood** [comment]
Please merge when you think it's in an acceptable state. I'm breaking things atm and will cease pushing then.

On the other hand I can always merge your changes into my repo.

**Comment by JeroenVinke** [comment]
> On the other hand I can always merge your changes into my repo.

that sounds like a better solution for now yep
