### ISSUE TITLE
cannot find module '../bin/darwin/x64.m49.node'

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#133]
resolved by running `./node_modules/.bin/electron-rebuild -f -w pty.js`. pty is a requirement for the terminal to work, and this command should have been run via the `postinstall`  script. Not sure what happened here, I am pretty sure I ran ` npm install` as otherwise pty.js wouldn't be on my filesystem

**Comment by JeroenVinke** [comment]
after the build finally worked again (https://github.com/monterey-framework/monterey/issues/134) I tried to run the installer, which gave me no problems. but I got this error immediately after starting monterey

![image](https://cloud.githubusercontent.com/assets/2189477/17642111/2b39e44c-613a-11e6-82f2-d05065b08efc.png)

**Comment by vegarringdal** [comment]
from the looks of it its not built for the electron version...
is this error you get just in windows?

**Comment by vegarringdal** [comment]
Did this improve on your windows after we upgraded the builder ?

**Comment by JeroenVinke** [comment]
Yep, works fine now :+1:
