### ISSUE TITLE
appveyor fails to build

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#134]
https://ci.appveyor.com/project/JeroenVinke/monterey/build/1.0.79#L753

@vegarringdal have you seen this before?

**Comment by JeroenVinke** [comment]
right, so node-gyp requires python to be installed

**Comment by adriatic** [comment]
This (node-gyp <--> python) is the source of lots of evil when running npm on a windows platform. Most of the fast scrolling error messages that we are used to "safely" ignore are caused by this

**Comment by vegarringdal** [comment]
Dont think Ive had that one, not used electron-builder before, its on my 1 mile long todo list 😂 
I had a lot of node-gyp and issues just getting pty.js installed on my windows pc, had to install latest npm to get it to work, but cant be the same issue, since you had the terminal running earlier.

**Comment by JeroenVinke** [comment]
this is unrelated to electron-builder as it happens before electron-builder begins.

so I finally was able to fix the build by installing npm@next, using nodejs 4.4.7 instead of node 6, and installing windows-build-tools which installs python
