### ISSUE TITLE
Call logger before each action

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#139]
The aurelia-logger now writes actions to a log file which will help to reproduce issues. Now we need to call the logger whenever monterey does something important enough to write to a logfile

**Comment by vegarringdal** [comment]
something that hit me yesterday while using electron-builder, how do someone access the log files when using the compiled/built version?

**Comment by JeroenVinke** [comment]
well if the logs folder always exists (meaning that we don't create it ourselves anymore) then we can probably unpack the folder in electron-builder

**Comment by vegarringdal** [comment]
yes, that is a option.
