### ISSUE TITLE
output of `npm run setup` looks a bit unorganized

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#141]
![img](https://files.gitter.im/monterey-framework/monterey/oRhU/thumb/blob.png)

@vegarringdal can you take a look if you have time?

**Comment by vegarringdal** [comment]
its because I run both at the same time, that way it will be faster.

**Comment by JeroenVinke** [comment]
i'd actually be in favor of doing it one by one so we can see the errors npm may throw (and we can see which npm install caused it)

**Comment by vegarringdal** [comment]
ok, I can fix that

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/pull/142
