### ISSUE TITLE
warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#147]
This might help resolve `warning: possible EventEmitter memory leak detected` issue

http://www.jongleberry.com/understanding-possible-eventemitter-leaks.html

**Comment by JeroenVinke** [comment]
This is a problem with the newest nodeJS (which we need for the terminal) as I get this with any nodejs command (even in different projects)

![image](https://cloud.githubusercontent.com/assets/2189477/17787407/51ff470e-6589-11e6-87dc-4c365892dcfb.png)

**Comment by adriatic** [comment]
Is the problem with Chrome or NodeJs (they are the same thing - but packaged differently as we know)?

**Comment by JeroenVinke** [comment]
This is a nodejs thing, as I even get it when running `gulp watch` in other projects

**Comment by adriatic** [comment]
I mentioned Chrome because of the **red message** on the screenshot [above](https://github.com/monterey-framework/monterey/issues/147#issuecomment-240827611)
