### ISSUE TITLE
Remove jspm dependency from app/package.json

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#149]
@vegarringdal can you check if we can remove the jspm dependency from the package.json of the app? perhaps we can use jspm globally, or put the dependency in the root package.json

**Comment by vegarringdal** [comment]
This for getting the size on final build down ?

**Comment by JeroenVinke** [comment]
Yep, happy with what we've got but we can always try :)

**Comment by vegarringdal** [comment]
I tried removing jspm and npm from app package.json, and ran:
- "npm run setup" 
- "npm run dist" just to see how big final build ended up.
That gave us size of 66,9, compared to 68,9... so dunno if 2 megs are worth it..

trying to generate a esnext skeleton in it now to see if it works

**Comment by JeroenVinke** [comment]
nope, that probably isn't worth it

**Comment by JeroenVinke** [comment]
thanks for trying it out :+1:
