### ISSUE TITLE
More visual indication of the "post project creation steps" monterey is executing

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#153]
As soon as a project is created the user can tell monterey to execute certain steps to get the project in a runnable state:
![image](https://cloud.githubusercontent.com/assets/2189477/17692201/f245710e-6398-11e6-9ade-b36f603406e7.png)

Right now the progress of these tasks can be seen via the taskmanager, but this is pretty hidden and does not give the user a good overview of what monterey is doing to setup the project.

So I wonder if we could do something like this:

![image](https://cloud.githubusercontent.com/assets/2189477/17692705/7922bdd8-639b-11e6-8b6f-8ccce8adfef6.png)

As soon as the project is created (in a situation where the user told monterey to install the npm dependencies and afterwards start `au run --watch`) monterey will add numbers to relevant tiles and show a spinner in the tile monterey is working on. In the above screenshot you can see that monterey is working on installing the npm dependencies.

Not sure if this is possible, but we can give it a try. This is a also a good way to test (and improve) the extensibility of the tiles

**Comment by JeroenVinke** [comment]
The "au run --watch" tile can be seen as a shortcut for 
![image](https://cloud.githubusercontent.com/assets/2189477/17692722/9dab0b38-639b-11e6-98f8-1d33ff52dd7a.png)

**Comment by vegarringdal** [comment]
So if you switch project and that project does not have NPM task running, it will not display anything ?
What about having a red number in taskbar after "Taskmanager" text so its easier to see how many tasks are running/scheduled ?

**Comment by JeroenVinke** [comment]
> So if you switch project and that project does not have NPM task running, it will not display anything 

Yes, the npm logo will be shown instead. One thing I like about [this](https://cloud.githubusercontent.com/assets/2189477/17692705/7922bdd8-639b-11e6-8b6f-8ccce8adfef6.png) is that it is really close to what the user would do if this wouldn't be done automatically. The user would open the NPM tile, click 'Install', wait for the spinner, then start `au run --watch`. Now the user can just sit back and watch the process happening in the tiles

> What about having a red number in taskbar after "Taskmanager" text so its easier to see how many tasks are running/scheduled ?

I don't think this solves the problem where the taskmanager is not good at visualizing what it's doing when multiple steps are involved.

**Comment by adriatic** [comment]
### This is a huge issue and the initial ideas about addressing it are great

I want to come back to this once I finish all emails in my queue this morning

**Comment by adriatic** [comment]
I like what is proposed here. I also "remembered" this issue as I would like to revisit it once I am done with straight testing.

**Comment by JeroenVinke** [comment]
this will be part of https://github.com/monterey-framework/monterey/issues/166
