### ISSUE TITLE
session per environment

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#155]
it's not very convenient to have the same monterey session in development and when using monterey

instead of [this line](https://github.com/monterey-framework/monterey/blob/master/app/src/shared/application-state.ts#L20)

maybe we can use the current path as the unique identifier:

```
Object.assign(this, await SESSION.get('state-' + __dirname));
```

**Comment by JeroenVinke** [comment]
this change will probably cause the session to be gone for everyone, luckily this is a one time thing

**Comment by adriatic** [comment]
> this change will probably cause the session to be gone for everyone, luckily this is a one time thing

Please expand this comment

**Comment by JeroenVinke** [comment]
The next time any of us (people who have used monterey so dar) opens monterey it will not find the old session and it will start from scratch. this is a one time thing
