### ISSUE TITLE
Improve dialogs

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#157]
1. Monterey should automatically maintain its window size and position (this should be just a few lines oc code added)

2. I would very much like to be able to adjust the size of each pop-up window and have this size remembered as well

3. I would even more like to be able to be able to say that some pop-up windows would be "normal windows" - that are not modal. Example:

 ![image](https://cloud.githubusercontent.com/assets/2712405/17704831/3c3f34d8-63a4-11e6-9522-f6326b5c1b7b.png)
 <br><br>
 In the situation like this, there is really no reason to force the focus on this terminal - and I would love to  move it to some nice place, while keeping it "associated" with Monterey. The fact that at this point this terminal is launched with just the information on "current directory", there is no reason to keep it this simple in the future - Monterey could be taught to "listen" to what the user is doing in this terminal.

**Comment by JeroenVinke** [comment]
I agree completely

Same thing for the task runners:

![image](https://cloud.githubusercontent.com/assets/2189477/17705305/325a9fdc-63d8-11e6-8c45-5dbad01fac8e.png)

they should be movable and resizable

**Comment by adriatic** [comment]
### That was meant to be my next observation - as they are now, they look more like a toy than a serious tool

**Comment by JeroenVinke** [comment]
We may need to patch up some dialogs (I briefly checked them but they may not resize well)

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/commit/22b3637382febddfef81fc9760934f916ff0c877
