### ISSUE TITLE
can I fix this without restarting Monterey?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#158]
This instance is still running since yesterday, as I wanted to see the end of the aureli-acli created asp.net app. So far I only executed `npm install` and then started to create the issues for you.

![image](https://cloud.githubusercontent.com/assets/2712405/17705324/f3fcab68-63a5-11e6-9905-7dc58f8b9786.png)

As we discussed (via reported issues) this state is due the unwanted inheritance. Am I able to just fix these icons using only app launcher - or am I better off to abandon this session, see how can I salvage the series of screenshots already made and start this same test from scratch

Also:

1. Would you prefer me to continue with this Monterey instance that I built from sources of to install one from the release.

2. I would prefer not to refresh my Monterey instance with a new one that might have some fixes for issues I already reported. Instead I want to test **all possible combinations of use** and then upgrade Monterey **when you tell me to**

**Comment by JeroenVinke** [comment]
> Would you prefer me to continue with this Monterey instance that I built from sources of to install one from the release.

From source seems better, as this way you to quickly confirm a fix when it is not sure whether or not a commit actually fixed the issue by running `git pull`

> Am I able to just fix these icons using only app launcher - or am I better off to abandon this session
you can, by either changing 

you could:
- fix the image paths of the app launchers (it is pointing to a non-existing path right now)
- remove the app launchers and add them again via the app launcher browser (the screen to search and install new app launchers)
- start from scratch by using this option:  
  ![image](https://cloud.githubusercontent.com/assets/2189477/17705797/fb97395e-63d9-11e6-9e3c-707db81fde34.png)


you will probably lose the session as a side effect of https://github.com/monterey-framework/monterey/issues/155 when you pull in the latest changes, which is a change necessary to fix this precise issue

**Comment by adriatic** [comment]
I will take the least risky part, stop this session, make sure that I have correct tools defined and working and go through https://github.com/aurelia-ui-toolkits/assets/issues/4 sequence again.

**Comment by adriatic** [comment]
Let's not rush this release by not doing a lot of testing - this thing deserves all of my efforts (except that I will likely be thrown to bed soon :smile: )

**Comment by JeroenVinke** [comment]
Agreed :+1:

**Comment by adriatic** [comment]
Another point for meaningful separation of "local data" by keeping it in the database. Now, as I issues "clear cache" command, I lost the state of my previous run. I do not believe that this would be necessary if everything was already in perfect shape (this is not a criticism, but rather impetus for making things better.

The other alternative to recover is to try and open the existing app was more successful - as Monterey only needed to be to go one folder up in order to find package.json (it tried to find it in aurelia_project folder which is likely a bug, as package.json would never be there).

Now, having this state (remember, I went to the point of successful execution of `npm install`) I see this:

![image](https://cloud.githubusercontent.com/assets/2712405/17706990/4c0ca514-63ac-11e6-9f7e-7054b7db079e.png)

or this:

![image](https://cloud.githubusercontent.com/assets/2712405/17707014/6a1ab564-63ac-11e6-912c-cc7cbbadc882.png)

At this point, **I know** that I need to run `jspm install` - however, because of executing `clear cache` I lost my GitHub credentials - something that should **never happen** unless you want to spend the rest of your life supporting Monterey :smiling_imp: )

Side note: **it is beautiful** to see how you expected people to escape the offer to enter GitHub credentials and try to click on JSPM tile

![image](https://cloud.githubusercontent.com/assets/2712405/17707139/0a856008-63ad-11e6-8ad9-d52a9a8967d6.png)

However, while this specific situation is pretty exceptional (needing to continue the building process by running `jspm install`) the fact that JSPM tile is not normally visible people might get stuck.

**Comment by JeroenVinke** [comment]
I do not follow

![img](https://cloud.githubusercontent.com/assets/2712405/17707014/6a1ab564-63ac-11e6-912c-cc7cbbadc882.png)

Here I see that you have selected the aurelia-cli-test project, which I assume was generated by aurelia-cli and therefore does not support JSPM. 

you lost me here:

> At this point, I **know** that I need to run jspm install

**Comment by adriatic** [comment]
### Of course it is the time to go to bed - I was simply being silly and completely forgot what am I really doing.

**Comment by JeroenVinke** [comment]
Rest well :+1: It is well deserved

**Comment by adriatic** [comment]
This does tell us how Monterey should not allow activating tiles that are not part of the build - I should be given the message "This operation should not be used in the context of your project"

We may offer the safe and un-safe modes of using Monterey, so that forcing the use of an irrelevant tile might be allowed in unsafe mode assuming that the user knows what is he doing ( I clearly am not in that category :smil)

**Comment by adriatic** [comment]
Final note in this thread:

I restarted Monterey, added the project and run `au run --watch`. Here is the data from the terminal (note the unusual order of lines - the last one on top). Given that this process was interrupted to many times even by running some meaningless commands (JSPM), I do not believe that this is worth further debugging; leaving that decision to you.
```
Application Available At: http://localhost:9000 BrowserSync Available At: http://localhost:3001
Finished 'writeBundles'
[16:55:18] gulp-notify: [Error running notifier] Could not send message: Command failed: C:\work\tests\Testing monterey\aurelia-cli\aurelia-cli-test\node_modules\node-notifier\vendor\toaster\toast.exe -open -subtitle -p C:\work\tests\Testing monterey\aurelia-cli\aurelia-cli-test\node_modules\gulp-notify\assets\gulp-error.png -m Error: custom_typings\aurelia-protractor.d.ts(8,41): error TS2305: Module 'protractor' has no exported member 'Protractor'. -t Error running Gulp Unhandled Exception: System.Exception: The notification platform found application is already registered. (Exception from HRESULT: 0x803E0118)
 at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
 at toast.Program.ShowToast(String title, String message, String imageURI, Boolean sound)
 at toast.Program.Main(String[] args)
[16:55:18] gulp-notify: [Error running notifier] Could not send message: Command failed: C:\work\tests\Testing monterey\aurelia-cli\aurelia-cli-test\node_modules\node-notifier\vendor\toaster\toast.exe -open -subtitle -p C:\work\tests\Testing monterey\aurelia-cli\aurelia-cli-test\node_modules\gulp-notify\assets\gulp-error.png -m Error: custom_typings\aurelia-protractor.d.ts(9,56): error TS2305: Module 'protractor' has no exported member 'Protractor'. -t Error running Gulp Unhandled Exception: System.Exception: The notification platform found application is already registered. (Exception from HRESULT: 0x803E0118)
 at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
 at toast.Program.ShowToast(String title, String message, String imageURI, Boolean sound)
 at toast.Program.Main(String[] args)
Writing app-bundle.js... Writing vendor-bundle.js...
Tracing aurelia-testing...
Tracing aurelia-templating-router...
Tracing aurelia-templating-resources...
Tracing aurelia-templating-binding...
Tracing aurelia-router...
Tracing aurelia-route-recognizer...
Tracing aurelia-logging-console...
Tracing aurelia-loader-default...
Tracing aurelia-framework...
Tracing aurelia-history-browser...
Tracing aurelia-bootstrapper...
Tracing aurelia-history...
Tracing aurelia-event-aggregator...
Tracing aurelia-dependency-injection...
Tracing aurelia-binding...
Tracing app... Tracing text...
Tracing resources/index...
Tracing main...
Tracing environment...
Tracing app...
Finished 'buildTypeScript' Starting 'writeBundles'...
[16:55:15] TypeScript: 3 semantic errors [16:55:15] TypeScript: emit succeeded (with errors)
[16:55:15] gulp-notify: [Error running Gulp] Error: custom_typings\aurelia-protractor.d.ts(14,36): error TS2503: Cannot find namespace 'webdriver'.
custom_typings\aurelia-protractor.d.ts(14,36): error TS2503: Cannot find namespace 'webdriver'.
[16:55:15] gulp-notify: [Error running Gulp] Error: custom_typings\aurelia-protractor.d.ts(9,56): error TS2305: Module 'protractor' has no exported member 'Protractor'.
custom_typings\aurelia-protractor.d.ts(9,56): error TS2305: Module 'protractor' has no exported member 'Protractor'.
[16:55:15] gulp-notify: [Error running Gulp] Error: custom_typings\aurelia-protractor.d.ts(8,41): error TS2305: Module 'protractor' has no exported member 'Protractor'.
custom_typings\aurelia-protractor.d.ts(8,41): error TS2305: Module 'protractor' has no exported member 'Protractor'.
Finished 'configureEnvironment' Starting 'buildTypeScript'...
Finished 'processMarkup'
Finished 'processCSS'
Starting 'processMarkup'... Starting 'processCSS'... Starting 'configureEnvironment'...
Finished 'readProjectConfiguration'
Starting 'readProjectConfiguration'...
```

**Comment by JeroenVinke** [comment]
I created https://github.com/monterey-framework/monterey/issues/172
