### ISSUE TITLE
aurelia-cli application fails to run

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#159]
Starting from  **[here](https://github.com/aurelia-ui-toolkits/assets/issues/4#issuecomment-240249589)** executing `au run` resulted with failure. I will take this as the end of the project defined by 

* **Project name**
aurelia-cli
* **Project path:**
C:\work\tests\Testing monterey\aurelia-cli
* **Package.json path:**
C:\work\tests\Testing monterey\aurelia-cli\package.json
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.3
* **Chrome:**
52.0.2743.82
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
C:\work\tests\Testing monterey\aurelia-cli\aurelia_project\aurelia.json

```
Application Available At: http://localhost:9000 BrowserSync Available At: http://localhost:3001
Finished 'writeBundles'
Writing app-bundle.js... Writing vendor-bundle.js...
Tracing aurelia-testing...
Tracing aurelia-templating-router...
Tracing aurelia-templating-resources...
Tracing aurelia-templating-binding...
Tracing aurelia-router...
Tracing aurelia-route-recognizer...
Tracing aurelia-logging-console...
Tracing aurelia-loader-default...
Tracing aurelia-framework...
Tracing aurelia-loader...
Tracing aurelia-history-browser...
Tracing aurelia-dependency-injection...
Tracing aurelia-history...
Tracing aurelia-event-aggregator...
Tracing aurelia-binding...
Tracing aurelia-bootstrapper...
Tracing app... Tracing text...
Tracing resources/index...
Tracing main...
Tracing environment...
Tracing app...
[17:42:20] TypeScript: 3 semantic errors [17:42:20] TypeScript: emit succeeded (with errors) Finished 'buildTypeScript' Starting 'writeBundles'...
[17:42:20] gulp-notify: [Error running Gulp] Error: custom_typings\aurelia-protractor.d.ts(14,36): error TS2503: Cannot find namespace 'webdriver'.
custom_typings\aurelia-protractor.d.ts(14,36): error TS2503: Cannot find namespace 'webdriver'.
[17:42:20] gulp-notify: [Error running Gulp] Error: custom_typings\aurelia-protractor.d.ts(9,56): error TS2305: Module 'protractor' has no exported member 'Protractor'.
custom_typings\aurelia-protractor.d.ts(9,56): error TS2305: Module 'protractor' has no exported member 'Protractor'.
[17:42:20] gulp-notify: [Error running Gulp] Error: custom_typings\aurelia-protractor.d.ts(8,41): error TS2305: Module 'protractor' has no exported member 'Protractor'.
custom_typings\aurelia-protractor.d.ts(8,41): error TS2305: Module 'protractor' has no exported member 'Protractor'.
Finished 'configureEnvironment' Starting 'buildTypeScript'...
Finished 'processMarkup'
Finished 'processCSS'
Starting 'processMarkup'... Starting 'processCSS'... Starting 'configureEnvironment'...
Finished 'readProjectConfiguration'
Starting 'readProjectConfiguration'...
```

**Comment by JeroenVinke** [comment]
It seems like the aurelia-cli application was started:

> Application Available At: http://localhost:9000 BrowserSync Available At: http://localhost:300

Did you try and go to this URL? it does not open automatically like the skeletons do. This is actually an opportunity to use the browser app launchers. We could add a project-specific chrome/safari app launcher automatically after creating/adding a project to monterey

The gulp errors are typescript compilation errors, I am pretty sure this is not a monterey error but aurelia-cli problem.

**Comment by adriatic** [comment]
Yes, the app was started - I was just not aware of it at the time. This indicates how it would be good to do what you propose:

> This is actually an opportunity to use the browser app launchers. We could add a project-specific chrome/safari app launcher automatically after creating/adding a project to monterey. Then you could just click on the Google chrome tile and it would open http://localhost:9000 in chrome

I am not sure whether you can find out what port number the app is running on - but that would really be cool

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/issues/174

**Comment by jbrinkman** [comment]
Even though the application runs... what about the errors that are displayed? This is still occurring in 1.0.3.

**Comment by JeroenVinke** [comment]
The errors were caused by the typescript definitions not being installed. By calling `typings install` it resolved the errors if I remember correctly

**Comment by ycharron-cstj** [comment]
Yes got the same error, with aurelia-cli 0.0.22 and fix them fit `typings install`.
