### ISSUE TITLE
Automatically "npm install" after new project gets created

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#16]
![image](https://cloud.githubusercontent.com/assets/2189477/16544246/aeca5f78-40fe-11e6-90e3-281b21132ab2.png)

NPM install already works in monterey: https://github.com/monterey-framework/shell/blob/master/src/plugins/npm/screen.js#L28-L48, we just have to trigger this process after a project has been created

**Comment by JeroenVinke** [comment]
Should we do this automatically? Or do we let the user click on the NPM tile and then click "Install dependencies"

**Comment by vegarringdal** [comment]
Let the user click "install dependencies"
It could also be last question on the "wizard"
"Do you want to start installing dependencies ?"

**Comment by JeroenVinke** [comment]
Thats a very nice option :)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16652046/1b97d576-4448-11e6-8ff3-4c56780aac90.png)

when you choose "yes" and click on "close" then NPM install will be started (and will be monitored in the taskmanager like [this](https://cloud.githubusercontent.com/assets/2189477/16465558/b24d52ca-3e3f-11e6-9132-8c277bee495d.png))

**Comment by adriatic** [comment]
Nice :-)

I am guessing that you verified how `npm install` is a meaningful action in **all** supported monterey scenarios (jspm obviously is not and until today, it was possible to run `jspm install` **before** `npm install` which does not make sense
