### ISSUE TITLE
where is the Monterey log?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#162]
Running this
* **Project name**
default-esnext
* **Project path:**
C:\work\tests\Testing monterey\default-esnext
* **Package.json path:**
C:\work\tests\Testing monterey\default-esnext\package.json
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.3
* **Chrome:**
52.0.2743.82
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
C:\work\tests\Testing monterey\default-esnext\aurelia_project\aurelia.json

results with a complete success - the only thing I could not find is the log of actions that is meant to be used for support issues. Here is my files hierarchy

![image](https://cloud.githubusercontent.com/assets/2712405/17718018/8fe6b18e-63df-11e6-9e35-a0525014c662.png)

**Comment by JeroenVinke** [comment]
Logs are not project-specific, so they aren't in the project folder. 

The logging functionality is not done yet. these issues are relevant:
https://github.com/monterey-framework/monterey/issues/139
https://github.com/monterey-framework/monterey/issues/154

we basically need to store the log files in a folder that is not removed when updating the application, and we need to call the logger before doing actions we want to have logged

**Comment by adriatic** [comment]
> we basically need to store the log files in a folder that is not removed when updating the application

That is what it should be. I was not aware that logging is still to be implemented, so I wanted to see how it looks

**Comment by JeroenVinke** [comment]
Closing this then :smile:

**Comment by adriatic** [comment]
+ack
