### ISSUE TITLE
Why is VS Code selected as the editor for Aurelia-CLI default-typescript project?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#163]
![image](https://cloud.githubusercontent.com/assets/2712405/17718118/311c4546-63e0-11e6-9f2f-04728ab85e87.png)

**Comment by JeroenVinke** [comment]
This is taken straight from the workflow of aurelia-cli (https://github.com/aurelia/cli/blob/master/lib/commands/new/new-application.json#L8-L42). The default is set to visual studio code, and there is no step in that workflow to change the default. 

In step 3 you choose "default-typescript", then it goes to step 11 (which is not a step where the user has to do anything) and it goes to step 13 right after that, which is the step where the project gets created. So step [10](https://github.com/aurelia/cli/blob/master/lib/commands/new/new-application.json#L242) is not used in this path. I'm also not sure what this Editor setting does

**Comment by adriatic** [comment]
Strictly following Aurelia-CLI is more important than any minor inconveniences / lack of clarity issues. No need to change anything.
