### ISSUE TITLE
what to do while waiting on a build?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#164]
### This is the situation running the build for

* **Project name**
default-typescript
* **Project path:**
C:\work\tests\Testing monterey\default-typescript
* **Package.json path:**
C:\work\tests\Testing monterey\default-typescript\package.json
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.3
* **Chrome:**
52.0.2743.82
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
C:\work\tests\Testing monterey\default-typescript\aurelia_project\aurelia.json

<br>

![image](https://cloud.githubusercontent.com/assets/2712405/17718255/d68cc898-63e0-11e6-9646-77095ac0eeb7.png)

I would like to get the same user experience I have when running my standard tools (Sublime / Cmder Chrome) - not having to watch the terminal window for 3+ minutes (I will check whether running  `au run` separate from Monterey is any faster)

I do not have any concrete proposal - but have a gut feeling that we could offer something cool in this situation :smile_cat:

**Comment by JeroenVinke** [comment]
take https://github.com/monterey-framework/monterey/issues/153 into consideration

**Comment by JeroenVinke** [comment]
https://github.com/wayou/t-rex-runner

http://wayou.github.io/t-rex-runner/ ( hit space )

**Comment by adriatic** [comment]
# THIS, YES!!!

You perfectly read my mind here - please put it in right away
