### ISSUE TITLE
make better use of GistRun in the context of Monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#165]
The gistrun tool integrated with monterey will be one of the highlights and cause everyone to use monterey just for that thing alone.

We need to be able to invoke GistRun with defining the initial content of the "blue box" shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/16881939/8a0b4522-4a8a-11e6-952f-2c0f51183410.png)

Of course, like with all other situations, we define what happens when the GistRun tile is clicked (and that knowledge is either set automatically from the monterey's "state information" or, monterey offers the choices

- which item from the [aurelia-kendoui-bundles](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bundles) repository to preload
- invoke GistRun in the context of creating a problem report (this clearly has a far wider applicability than just just our own support issues
- ... (whatever else we decide to use monterey's own GistRun for)

**Comment by JeroenVinke** [comment]
can you close https://github.com/monterey-framework/monterey/issues/75 if it's a duplicate?

**Comment by adriatic** [comment]
:smiling_imp: you closed it already - and to preserve the original content I copied it to this issue.

**Comment by JeroenVinke** [comment]
> you closed it already

I did not :cry: that was https://github.com/monterey-framework/monterey/issues/43 :)

**Comment by JeroenVinke** [comment]
This is now called "Quick app" and explained in https://github.com/monterey-framework/monterey/issues/175
