### ISSUE TITLE
task manager is lying

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#166]
It shows this:

![image](https://cloud.githubusercontent.com/assets/2712405/17718619/d5ff06e6-63e2-11e6-9698-ae81cbc2231e.png)

Note the highlighted default-typescript project which was running last -- and which is still running despite what task-manager says. This is also why this (default-typescript) app runs at port 9002 - I did not realize that the previously running browser-sync instance are still alive 

![image](https://cloud.githubusercontent.com/assets/2712405/17718725/7a6e5038-63e3-11e6-932c-294f8539a534.png)

Specific command `cancel task` does the right thing, so this issue is a pilot error that will likely be repeated by others:

![image](https://cloud.githubusercontent.com/assets/2712405/17718814/1888f656-63e4-11e6-8860-d15537bdab15.png)

**Comment by JeroenVinke** [comment]
what is your proposal? the (1) behind Aurelia-CLI in the taskbar indicates that something is running

**Comment by JeroenVinke** [comment]
> Note the highlighted default-typescript project which was running last -- and which is still running despite what task-manager says

Perhaps we should consolidate the taskmanager and the taskrunner screens. Right now the taskmanager installs NPM modules and starts "au run --watch", after which you need to look in the taskrunner ([link](https://cloud.githubusercontent.com/assets/2712405/17718814/1888f656-63e4-11e6-8860-d15537bdab15.png)) for the output and to be able to cancel it.

I think you are looking for an overview of running `gulp` or `au run` tasks. The reason we have a taskmanager is that it allows you to see what monterey is working on, regardless of what project you have selected. So it would make sense to show the running `au run` tasks in the taskmanager, but this may add to the confusion.

I think we can improve the taskmanager UI so it's able to start `gulp watch`  or `au run` tasks as well. This was the main reason for creating the taskrunner

**Comment by JeroenVinke** [comment]
@adriatic thoughts?

**Comment by adriatic** [comment]
I want to think about it some more - realizing that we need to ensure uniform behavior across building of all different application types (so far I was only focused on testing CLI apps). For example, I just tried `skeleton-esnext-aspnetcore`, which I believe is being fetched from the Github [aurelia skeletons](https://github.com/aurelia/skeleton-navigation) collection. 

In this situation `NPM` and `JSPM` tiles are activated as a consequence of selecting the  checkboxes in the last wizard panel (see [issue 182](https://github.com/monterey-framework/monterey/issues/182)) - and even `Gulp` can be activated there. So, we need some global view for all projects and all stages of the project from which every of these actions could be handled.

**Comment by JeroenVinke** [comment]
in https://github.com/monterey-framework/monterey/issues/166 a better UI will be implemented
