### ISSUE TITLE
steps sequencing usability issue

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#167]
Probably not the best title for this issue - but here goes. 

I am asked about the name for the new project **before** I see the project type - like below:

![image](https://cloud.githubusercontent.com/assets/2712405/17720042/e0e7f4b4-63ec-11e6-84e8-a93b01b0dea6.png)

I would like to name the project after the type that I will select on the next wizard step - so I enter `x` as a place-holder, so I can move ahead, and see 

![image](https://cloud.githubusercontent.com/assets/2712405/17720099/44b6e0c2-63ed-11e6-83d0-cc9751acd7ba.png)

Here I will select custom and then go step back to rename the project's name. Nitpicking I know and again this is a flow issue that I want to discuss separately

**Comment by JeroenVinke** [comment]
This needs to be discussed with Rob, as the wizard uses [this file](https://github.com/aurelia/cli/blob/master/lib/commands/new/new-application.json) which is maintained in the aurelia-cli repository.

**Comment by adriatic** [comment]
Let's leave any issue that is a direct consequence of being Aurelia-CLI compliant to be exempted from usability discussions at this time. I only care about being Aurelia-CLI compliant until we are fully established as a good Aurelia-CLI partner.

**Comment by JeroenVinke** [comment]
OK
