### ISSUE TITLE
why am I asked "Did you install npm modules"?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#168]
This is the first time I left the default settings (install NPM and start the project)

![image](https://cloud.githubusercontent.com/assets/2712405/17720425/cfb0ea86-63ef-11e6-94c6-418889909ee0.png)

for this project

* **Project name**
custom-1
* **Project path:**
C:\work\tests\Testing monterey\custom-1
* **Package.json path:**
C:\work\tests\Testing monterey\custom-1\package.json
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.3
* **Chrome:**
52.0.2743.82
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
C:\work\tests\Testing monterey\custom-1\aurelia_project\aurelia.json

and found myself with this screen

![image](https://cloud.githubusercontent.com/assets/2712405/17720269/997b7c8e-63ee-11e6-9b8e-e7b854836fc9.png)

at the same time, I saw the task manager saying that it is `busy with one task`

![image](https://cloud.githubusercontent.com/assets/2712405/17720290/bc6b1d6c-63ee-11e6-9d65-b5257f79e883.png)

The above `npm install` ended fine:

![image](https://cloud.githubusercontent.com/assets/2712405/17737818/c91f3d2c-645c-11e6-8bb0-a25d9cd7a657.png)

but click on aurelia-CLI in the footer

![image](https://cloud.githubusercontent.com/assets/2712405/17737850/f4f740d4-645c-11e6-87bd-d7a8a05e2fef.png)

still shows this same "Did you install npm modules"? question

**Comment by JeroenVinke** [comment]
There may be some confusion as you have 3 of the same images, but based on the textual description I believe I noticed this once before, it is definitely a bug

**Comment by adriatic** [comment]
> There may be some confusion as you have 3 of the same images,

Apologies for being sloppy - the images above are now the right ones.

**Comment by JeroenVinke** [comment]
this was caused by the error in https://github.com/monterey-framework/monterey/issues/180. Right now it throws another error which doesn't seem to cause any problems, but as https://github.com/monterey-framework/monterey/issues/184 may cause us to get rid of this code i'm not investigating this further right now
