### ISSUE TITLE
How to do deployment

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#17]

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/pull/46 implements https://github.com/electron-userland/electron-packager:

![image](https://cloud.githubusercontent.com/assets/2189477/16596549/bb4efff4-42f4-11e6-9a86-1422e50ed765.png)

This produces a ZIP per OS that a user has to extract before it can be run. There is also no auto-update so when we release an update the user has to download a new ZIP file and again extract all the files.

I think that https://github.com/electron-userland/electron-builder will take a lot more to implement but is a much nicer solution (especially the auto update feature)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16612595/094c9504-4368-11e6-967b-46cfecb7f7d6.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16612639/30b1a396-4368-11e6-8ec0-6ddf0afa7b29.png)

Never mind then ;)

**Comment by Thanood** [comment]
https://medium.com/@svilen/auto-updating-apps-for-windows-and-osx-using-electron-the-complete-guide-4aa7a50b904c#.tmbu5wgpr

**Comment by JeroenVinke** [comment]
:smile: will take a look

**Comment by JeroenVinke** [comment]
https://github.com/electron/grunt-electron-installer#sign-your-installer-or-else-bad-things-will-happen damn

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16623011/7d50aaba-439c-11e6-89ad-84e820323a8c.png)

the button brings you to https://github.com/monterey-framework/monterey/releases/tag/0.0.1

**Comment by JeroenVinke** [comment]
No, if we want to create installers for monterey then we need to sign them using a code signing certificate. These are [not cheap](https://www.globalsign.com/en/code-signing-certificate/comparison/) and must be paid annually. It is possible to create installers without signing them, but antivirus will pick it up as a virus and browsers may block the download. While the dialog I showed above is not as nice as automatic updating, users will be aware of new releases (and we don't have to pay a lot of money for a certificate ;) )

**Comment by adriatic** [comment]
So, how does this solution circumvent the need for signing - because we do not use the installer in this case?

**Comment by JeroenVinke** [comment]
Yes, the users would download a zip and can extract this anywhere they want. This is what the ZIP for windows contains:

![image](https://cloud.githubusercontent.com/assets/2189477/16624147/e14f54e0-43a0-11e6-8afd-4e81f4cd00c8.png)

You can download it [here](https://github.com/monterey-framework/monterey/releases/tag/0.0.1)

**Comment by adriatic** [comment]
Perfect - although at some point I might break my promise to myself not to spend any money on OSS work and get us that certificate. It may make monterey look more professional. For now, I **really appreciate** your solution.

**Comment by JeroenVinke** [comment]
OK, going to close this for now.

**Comment by adriatic** [comment]
Saving this [Auto-updating apps for Windows and OSX using Electron: The complete guide](https://medium.com/@svilen/auto-updating-apps-for-windows-and-osx-using-electron-the-complete-guide-4aa7a50b904c#.hysmze3ka)
