### ISSUE TITLE
anything against this layout?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#170]
![image](https://cloud.githubusercontent.com/assets/2712405/17722893/b27ee8e6-6403-11e6-80bc-a81077ae74ac.png)

I find it a lot more "standard" as we currently have the toolbar in the footer - and know of no other application looks that way!

**Comment by JeroenVinke** [comment]
Visual studio code does this:

![image](https://cloud.githubusercontent.com/assets/2189477/17729299/c98c5662-6463-11e6-9e77-30e25a300614.png)

The advantage of keeping the footer in the toolbar is that the footer is always visible. Whatever we do in the "main" part of monterey (anything above the footer), the footer is always visible.

**Comment by adriatic** [comment]
> The advantage of keeping the footer in the toolbar is that the footer is always visible

Why is the same statement not true when the toolbar is on the top? It is certainly possible to make it so - and my concern is to be "standard".

**Comment by JeroenVinke** [comment]
we came to an agreement :)

**Comment by adriatic** [comment]
Because I realized that this layout is **also** used quite often.
