### ISSUE TITLE
(left side) navigation bar takes too much space

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#171]
The width is at the moment dictated by the tab item's readability:

![image](https://cloud.githubusercontent.com/assets/2712405/17722989/6a703ef0-6404-11e6-8ff9-2a2b234ccdb9.png)

The immediate solution to this would be to make the navbar collapsible - just like Gitter does

![image](https://cloud.githubusercontent.com/assets/2712405/17723041/c9ae3e80-6404-11e6-8e68-982679286b93.png)

**Comment by JeroenVinke** [comment]
Agreed :+1:

**Comment by vegarringdal** [comment]
What about just having it smaller, the buttons really dont need to have "project" word in them.
( I know that all dont agree with me here :joy: )

![image](https://cloud.githubusercontent.com/assets/2901416/17782330/455038d0-6573-11e6-9836-bf93730471b2.png)

**Comment by JeroenVinke** [comment]
Thinking that it would be nice if you could do this:

![image](https://cloud.githubusercontent.com/assets/2189477/17782672/002e27b0-6575-11e6-8be5-bc77725773d0.png)

**Comment by adriatic** [comment]
The personal preferences should still be subjected to usability issues and with Monterey which integrates so many different tools, many of which might be taking desktop space, it is really important that we do not waste any of the Monterey's own internal real estate.

@vegarringdal's proposal above is certainly an improvement as the label `my projects` already implies the  meaning of `Add`, `Create` and `Remove` buttons. 

In this specific situation, it is important that one can see the full name of any projects (list items), so here is what I believe would be a good approach:

1. The navbar should be resizable - just like it is in Sublime for example
2. The `Add`, `Create` and `Remove` buttons should be replaced by the context menu that can be started from the empty list or on any existing item applying the proper semantic (cannot show `Delete` on the empty list, etc

**Comment by adriatic** [comment]
@JeroenVinke can you explain what you meant [above](https://github.com/monterey-framework/monterey/issues/171#issuecomment-240786327)?

**Comment by vegarringdal** [comment]
Maybe, I just dont see me ever using it like that
it would be mostly a tool to maintain/create/install plugins. And when I do that kind of work I want to get as much information without any scrolling. Thats why I made it so the project list hides when viewing the npm/jspm details etc.
But maybe thats just me :smile:

**Comment by adriatic** [comment]
> Thats why I made it so the project list hides when viewing the npm/jspm details etc.

This touches another issue that I do not like: making the project list be "overwritten" (covered completely) by a tile-owned view can cause easy confusion as the user loses the context (which project am I massaging now)

**Comment by vegarringdal** [comment]
:-)

**Comment by JeroenVinke** [comment]
It is now much smaller 😄
