### ISSUE TITLE
Revert order in which logs are displayed

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#172]
https://github.com/monterey-framework/monterey/issues/158#issuecomment-240237495

Newest messages should be on the bottom, and it should automatically scroll down

**Comment by JeroenVinke** [comment]
The difficulty here is automatically scrolling down. While this is easy to do in javascript, the trick is knowning **when** to scroll. The view that's displaying the log messages does not know when a log messages gets added / removed, and the view-model that does know this doesn't know about the view.

**Comment by adriatic** [comment]
I do not understand this as proper scrolling should behavior should be "internal affair" of the terminal object. We should simply append lines to it without having to worry about the consequences of the user scrolling as well. ??
