### ISSUE TITLE
monterey building issue

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#176]
After `git pull` I run the commands:

```
npm install --global --production windows-build-tools npm@next
npm run setup
```

I got this (showing only last relevant portions of the log:

```
...
 Looking up npm:buffer
     Looking up npm:ieee754
     Looking up npm:base64-js
     Looking up npm:isarray
ok   Up to date - dragula as npm:dragula@^3.7.1 (3.7.1)
ok   Up to date - core-js as npm:core-js@^2.4.0 (2.4.1)
ok   Up to date - babel-polyfill as npm:babel-polyfill@^6.9.1 (6.9.1)
ok   Up to date - semver as npm:semver@^5.2.0 (5.3.0)
ok   Up to date - babel-runtime as npm:babel-runtime@^5.8.24 (5.8.38)
ok   Up to date - aurelia-validatejs as npm:aurelia-validatejs@^0.6.0 (0.6.0)
ok   Up to date - monterey-pal as github:monterey-framework/monterey-pal@^0.1.22 (0.1.22)
ok   Up to date - text as github:systemjs/plugin-text@^0.0.3 (0.0.3)
ok   Up to date - fetch as github:github/fetch@^1.0.0 (1.0.0)
     Installed Forks

                                     npm:babel-runtime 5.8.38 6.11.6

     To inspect individual package constraints, use jspm inspect registry:name.


warn core-js@2.4.1 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.

ok   Install complete.
JSPM install done
Using electron for building:
C:\work\monterey-framework\monterey\node_modules\electron-prebuilt\dist\electron
Rebuilding native modules in:
C:\work\monterey-framework\monterey\app\node_modules
build success
gypfix success
```

This fork is most likely the consequence of [this](https://github.com/monterey-framework/monterey/blob/master/app/package.json#L61) and [that](https://github.com/monterey-framework/monterey/blob/master/app/package.json#L45) entry in [package.json](https://github.com/monterey-framework/monterey/blob/master/app/package.json) file.

I believe that now knowing the relevance of using ` "babel-polyfill": "npm:babel-polyfill@^6.9.1", I will solve this locally by using ` "babel-polyfill": "npm:babel-polyfill@^5.8.38"`

**Comment by vegarringdal** [comment]
Something else, just for info.
This you just need to install once on a fresh computer, no need to install everytime.
```npm install --global --production windows-build-tools npm@next```

npm run setup takes enough time :-)

**Comment by adriatic** [comment]
Thank you @vegarringdal :+1: 

The above described attempt did not fix the forking problem. `jspm` says:

```
ok   Installed babel-polyfill as npm:babel-polyfill@^5.8.24 (6.9.1)
```

**Comment by vegarringdal** [comment]
I bit unsure why we have babel at all, we use typescript, so do we really need it?
Only reason why using babel with typescript would be to trans-pile typescript ->es6 -> babel -> es5/3.
But we dont need that when we use electron and have control over node/chromium version.

**Comment by vegarringdal** [comment]
maybe the testing needs it

**Comment by adriatic** [comment]
### Verified fixed
