### ISSUE TITLE
monterey leaves many running instances of nodejs 

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#177]
In the few days of testing (without ever rebooting my Windows), I started / exited / cleared Monterey cache many times. So, I observed that each time I start new instance of Monterey, **open** an existing application and run it, I would get higher and higher port number 

Windows Task manager listed more than 10 instances of nodejs running that were not attached to anything - and since I was not doing anything else that requires nodejs, I am sure that all these were created by Monterey.

I believe that this is a consequence of https://github.com/monterey-framework/monterey/issues/160

**Comment by vegarringdal** [comment]
we where talking about a global quit event when I was using just node .spawn for the terminal.
If we use nodes child process in monterey and dont manually stop them, they will be running after monterey quit.
(atm I dont know if we use this),
 I know Ive tested the terminal I added for this by running gulp watch in it, and checked it stopped when I quit monterey.

**Comment by adriatic** [comment]
This issue is well document (in Electron) so I do not think we need to discuss it. If we cannot relay on Electron runtime to exit all spawned child processes when the user initiates Monterey shutdown, then we need to do it ourselves. It is probably safer if we do it anyway.

**Comment by JeroenVinke** [comment]
need to see how long [this](https://github.com/monterey-framework/monterey/blob/7374340d99422400aac0c784d4cbc6b79d344c84/app/src/cleanup.ts#L10-L25) holds water

**Comment by adriatic** [comment]
I will be watching like a hawk
