### ISSUE TITLE
building monterey from source

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#178]
The [instructions](https://github.com/monterey-framework/monterey) say:

```
From inside the monterey folder:

1. npm install --global --production windows-build-tools npm@next
2. npm run setup
3. gulp watch (or gulp watch --manual if you want to reload manually. gulp watch --env=production (default environment is development))
```
The commands 1 and 2 are "different" from what I am used to do so, I would like to know what should I do when I install a fresh clone and what do I do after `git pull` 
***
***Hint: documenting the build process might be a nice gesture to your teammates***

**Comment by JeroenVinke** [comment]
> Hint: documenting the build process might be a nice gesture to your teammates

Please add this to https://github.com/monterey-framework/monterey/issues/138

The instructions explain the setup procedure for a clean install. If there are no changes to dependencies (e.g a new package got added to monterey) then you do not have to do anything after `git pull`.

**Comment by adriatic** [comment]
> f there are no changes to dependencies (e.g a new package got added to monterey) then you do not have to do anything after git pull.

As expected ... 

Thanks

**Comment by adriatic** [comment]
> Please add this to #138

Added.

**Comment by JeroenVinke** [comment]
Closing this, will be added as part of #138
