### ISSUE TITLE
Wizard label is confusing in this context

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#182]
![image](https://cloud.githubusercontent.com/assets/2712405/17792514/120ca822-656f-11e6-88e6-8abf309a520f.png)

Action **3** on this screenshot should be renamed to **`Create`** instead of `Close`

***Note that this is related to [issue 180](https://github.com/monterey-framework/monterey/issues/180)***

**Comment by JeroenVinke** [comment]
Hmm, well at that point the project has already been created, so calling it "Create" might be confusing as well... What about calling the button "Close" if no items have been selected and otherwise calling "Start" ?
