### ISSUE TITLE
Gulp fails across many app types

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#183]
Just tried to create and build the **`skeleton-esnext-aspnetcore`** application, where I selected all three "build actions" available on the last page of the wizard (see [issue #182](https://github.com/monterey-framework/monterey/issues/182))

Outcome:

1. `npm install` run and finished fine
2. click on `JSPM` file results with

 ![image](https://cloud.githubusercontent.com/assets/2712405/17793189/8eb5d2dc-6573-11e6-847e-5754d3880705.png)

 (yes, I have all needed npm modules - so I am not sure how to move ahead from here)

3. There is the error indication in the footer area which shows:

 ![image](https://cloud.githubusercontent.com/assets/2712405/17793278/05d1072e-6574-11e6-8086-d527791387e3.png)

***

***Note: this situation is identical to the problem described in [issue #180](https://github.com/monterey-framework/monterey/issues/180)***

**Comment by JeroenVinke** [comment]
as you said this is the same as https://github.com/monterey-framework/monterey/issues/180
