### ISSUE TITLE
Monterey global task manager design

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#184]
See **[issue 166](https://github.com/monterey-framework/monterey/issues/166)** to understand the need for this discussion.

***Let me take a whack on this***

**Comment by adriatic** [comment]
I have a complete solution for this item - it is at the same time so simple and so powerful that everyone will have the reaction "How did I not think of it". 

I will make a bet that this will be voted as the most powerful Monterey feature :-)

***Coming tomorrow ...***

**Comment by JeroenVinke** [comment]
Can't wait :smile:

**Comment by adriatic** [comment]
***I will evolve this some more - at this point, I wanted to share the basic idea***

**Comment by JeroenVinke** [comment]
Nice! We need a screen design so we can properly merge the taskmanager and the taskrunners into a single dialog. Some requirements:

- The log of a specific process should be displayed (meaning that we need to be able to select a running process and view the log of it)
- The user should be able to start a new **gulp**, **au start** or **npm start** (for webpack) process
- processes that have been completed should be visible somehow

**Comment by adriatic** [comment]
Good added requirements.

**Comment by JeroenVinke** [comment]
I wonder if we can display queued tasks in a nice way as well. 

- NPM install (busy)
- JSPM install (queued)
- au run (queued)

Then we wouldn't need a big change like I proposed in https://github.com/monterey-framework/monterey/issues/153

**Comment by adriatic** [comment]
We are not limited in any way by the set of features that a real Task manager offers - I used it only as a model that presents several (mutually linked) lists that are "leaves" of (shallow) tree. The tree leaf "Queued tasks" makes all the sense in the world
