### ISSUE TITLE
Project list does not scroll

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#188]
![image](https://cloud.githubusercontent.com/assets/2189477/17837689/c33e112a-67b9-11e6-9a77-bb0f4f5a8cb9.png)

**Comment by vegarringdal** [comment]
I will prb get time to look at this tomorrow, Im guessing its just the task-bar overlapping the entire app at the bottom, so bottom of left/right part need to be adjusted with bottom: Xpx; (same height as the taskbar)

**Comment by JeroenVinke** [comment]
:+1:

**Comment by vegarringdal** [comment]
I have a scrollbar on windows, and the bottom in the css is correct
Is this a mac issue?



![image](https://cloud.githubusercontent.com/assets/2901416/18016792/8d816500-6bce-11e6-9c59-7dc099cd3c99.png)

**Comment by vegarringdal** [comment]
during testing being able to add same project multi able times is great, but this can cause so much issues if someone messes up

**Comment by JeroenVinke** [comment]
strange, not sure how I got this then:

![img](https://github.com/monterey-framework/monterey/issues/188#issue-172322778)

**Comment by vegarringdal** [comment]
unless you still get it you can close this one

**Comment by JeroenVinke** [comment]
Will keep an eye on it :+1:

**Comment by JeroenVinke** [comment]
Ahh, got it.

if you refresh while some of the projects are overflowed:
![image](https://cloud.githubusercontent.com/assets/2189477/18145128/208053da-6fca-11e6-99b0-ca43292e7262.png)

then the scroll bar works OK after the refresh.

But when you refresh when the scroll bar isn't necessary:
![image](https://cloud.githubusercontent.com/assets/2189477/18145144/3131272c-6fca-11e6-89a0-d900a393c310.png)

then the scroll bar is never shown after the refresh

**Comment by adriatic** [comment]
Someone seems to be using my identity - as I do not remember ever doing this:

![image](https://cloud.githubusercontent.com/assets/2712405/18146304/e23dc940-6f9c-11e6-9810-6fcdde6a5b29.png)

Can we resolve this issue (whether there is some other `adriatic` - or am I losing my mind), please?

**Comment by JeroenVinke** [comment]
I added this item to the list, or else there is no use for the checklist

**Comment by JeroenVinke** [comment]
strange that it shows your name though

**Comment by adriatic** [comment]
I am not the reasons for adding this, but rather why does it show me as adding it?

**Comment by JeroenVinke** [comment]
No idea, this looks like a bug in Github

**Comment by adriatic** [comment]
Must be - I never saw this before so, I became paranoid that we have a party-crasher here :-)

**Comment by vegarringdal** [comment]
so scrollbar works when you add project, but does not work after refresh of montery, if its not needed? (even if new projects are added?)

**Comment by JeroenVinke** [comment]
the behavior is kind of strange. When Monterey is opened when some projects are overflowed, then the scroll bar is visible and keeps working when I resize the screen (all good). but when I maximize the screen by double clicking on the window, then the scroll bar is gone, and won't return when I make the screen smaller so that the projects overflow

When monterey gets opened without projects overflowing (there are only a few projects in a very large window) then the scroll bar is never visible

**Comment by JeroenVinke** [comment]
Here is a vid: http://screencast.com/t/wQagKNpCpb

**Comment by vegarringdal** [comment]
well I know the grid compensate if window resize event triggers and it redraws if it gets larger then it was(quickfix I added a while back) , but looks like I need to check the scrollbars that I only show if needed in same event, Ill try and get it fixed in grid code today or latest during the weekend.
Would have loved more control when parent div did resized, like a event.

**Comment by JeroenVinke** [comment]
as a workaround, can we always show the scrollbar?

**Comment by vegarringdal** [comment]
it might work as a quickfix until I fix the bug in the grid
