### ISSUE TITLE
Improve task manager UI

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#19]
The UI of the taskmanager is a bit confusing. It is not always clear what task has been selected and you dont always want to see all tasks (often just the ones that are running

This is what it looks like now:

https://cloud.githubusercontent.com/assets/2189477/16541959/2546068a-4095-11e6-9ae8-28427a1b47cd.png

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16655168/6b26f70a-4459-11e6-88b1-dcb341e3f8a5.png)

:smile:

**Comment by adriatic** [comment]
# :+1:
