### ISSUE TITLE
package.json should not be required for a project

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#191]
right now a project is required to have a package.json file in order to work with monterey, but this restriction is unnecessary

**Comment by adriatic** [comment]
This is rather interesting relaxation, particularly given my impression that config.js defines the application.

**Comment by JeroenVinke** [comment]
I was thinking about the quick apps, which consists of an `index.html, `app.html` and `app.js`, but no package.json file.  Technically an aurelia app can be an aurelia app without there being a package.json file. This is a low priority change for now, but something to keep in mind

**Comment by adriatic** [comment]
+ack
