### ISSUE TITLE
Add context menu support

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#192]
https://github.com/monterey-framework/monterey/issues/40 and https://github.com/monterey-framework/monterey/issues/184 need a context menu, so lets add support for context menu's to monterey

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/commit/6cb55800a10a95fd1de5304d9ce7d7c32efb774c

**Comment by adriatic** [comment]
I am adding this code for the testing starting this afternoon
