### ISSUE TITLE
Monterey testing template

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#194]
- [ ] **Aurelia-CLI**
 - [ ]  Default ESNext
    - [ ] `npm install && au-run`
    - [ ] **NOT** `npm install && au-run`
 - [ ]   Default ESNext
    - [ ] `npm install && au-run`
    - [ ] **NOT** `npm install && au-run`
 - [ ]  Custom
    - [ ] `npm install && au-run`
    - [ ] **NOT** `npm install && au-run`

***

- [ ] skeleton-esnext-aspnetcore

- [ ] skeleton-esnext-webpack

- [ ] skeleton-esnext

- [ ] skeleton-typescript-aspnetcore

- [ ] skeleton-typescript-webpack

- [ ] skeleton-typescript

***

- [ ] ZIP

***

- [ ] App launcher

  - [ ] Add app launcher

  - [ ] Remove app launcher

  - [ ] Get more ...

  - [ ]  Share this app launcher

 ***

***To be added***

Aurelia-CLI used for KendoUI (RequireJS loader)
"Frozen" KendoUI-Navigation-Skeletons (need to ensure that KendoUI works with Webpack)

**Comment by JeroenVinke** [comment]
Closing this, it will still exist so we can take this template again when needed
