### ISSUE TITLE
Session 08242016

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#196]
- [ ] **Aurelia-CLI**
 - [ ]  Default ESNext
    - [x] `npm install && au-run`   
      - [x] run 1 **[failed](https://github.com/monterey-framework/monterey/issues/195)**
      - [x] run 2 **[succeded - but ...](https://github.com/monterey-framework/monterey/issues/197)**
    - [ ] **NOT** `npm install && au-run`
 - [ ]   Default TypeScript
    - [ ] `npm install && au-run`
    - [ ] **NOT** `npm install && au-run`
 - [ ]  Custom
    - [ ] `npm install && au-run`
    - [ ] **NOT** `npm install && au-run`

***

- [ ] skeleton-esnext-aspnetcore

- [ ] skeleton-esnext-webpack

- [ ] skeleton-esnext

- [ ] skeleton-typescript-aspnetcore

- [ ] skeleton-typescript-webpack

- [ ] skeleton-typescript

***

- [ ] ZIP

**Comment by JeroenVinke** [comment]
closing this, but keeping https://github.com/monterey-framework/monterey/issues/194
