### ISSUE TITLE
Default-ESNext runs - but  ...

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#197]
Several sub-issues that are best kept together

## 1. 
The terminal is (still) **jumbled** - see **[this](https://github.com/monterey-framework/monterey/issues/198)** for details.

The image below shows at least the line indicating that the app is ready:

  ![image](https://cloud.githubusercontent.com/assets/2712405/17947660/a575a798-6a1b-11e6-9961-1a8f80d13cbc.png)

while this next image (obtained in the identical context, later), offers no indication that I could launch the app:

 ![image](https://cloud.githubusercontent.com/assets/2712405/17950926/68312248-6a2c-11e6-99a8-3d73467f90cf.png)

  **note** that while showing the `au-watch` is technically correct, it is also confusing as the previous task orderly finished and people will wait forever to see how the application is ready to be accessed- the terminal should show that information and indicate the port number (9000 in this case).

 **Solution:** the terminal should not be blindly launched but rather launched and observed - Task Manager should be able to set a watch-point (in the sense a debugger does) and trigger on such watch point. In this specific case, Task manager should catch the terminal line `Application Available At: http://localhost:9000` and update the status of the currently running task (**` au run --watch`** in this situation) by adding the (indented) line **`http://localhost:9000`** in the task's header (above the terminal) and leaving the indicator that this task is running, unchanged.

## 2. 
Instead of **`Cancel this task`** I would propose **`End task`** command - offered via `context menu` as we discussed before:

 ![image](https://cloud.githubusercontent.com/assets/2712405/17950108/1ccb8154-6a27-11e6-9a1a-bdf0bd7e3cf4.png)

 This change should be shown as**`stopped by the user`** in the selected task header area (above the terminal).

## 3.

Any tasks available in the given context should be "restartable". A good example is this:

 ![image](https://cloud.githubusercontent.com/assets/2712405/17950577/1cefd88a-6a2a-11e6-91a5-95491257fccc.png)

 where I "cancelled" **`au run --watch`** (should be "ended" instead) to verify that the running app will stop when I end this task.

In this situation the context menu (off that task) should offer **`run`** command - so I do not have to close the task manager and then re-open it again from the `Task Manager` button on the Monterey footer or `Task manager tile`.

**Comment by JeroenVinke** [comment]
I split this up into different issues:

https://github.com/monterey-framework/monterey/issues/199
https://github.com/monterey-framework/monterey/issues/202
https://github.com/monterey-framework/monterey/issues/201
https://github.com/monterey-framework/monterey/issues/200

Reason is that 3 out of 4 needs be fixed right away, but last one is "nice to have", since you can simply start a new task via the "Start new task" leaf. By splitting these issues up we can atleast close 3 out of 4 issues.
