### ISSUE TITLE
terminal needs to be improved - no ifs ands or buts

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#198]
I would strongly suggest that we do not release Monterey 0.3.0 without fixing the terminal issues discussed so far (all of them should be listed below)

1. Terminal should **stop** writing output over the existing lines - at the moment it still does that with a random-like behavior.

2. The Terminal ought to persists all output (the user should be able to select to not require this, but the default should be ON). 

3. The user should be able to define the terminal buffer size (I always set it to some large number - 15000 for example

 ![image](https://cloud.githubusercontent.com/assets/2712405/17950311/7570f31a-6a28-11e6-84c6-3325219f649f.png)

4. The Task Manager should offer "search interface" to process the content of the terminal content - this might be easiest to do to launch user's editor preloaded with the saved terminal lines)

**Note** We could decide not to make all these fixes (if some of them are "very difficult") - in such case, the existing inadequacies should be visibly documented, explained and promised to be removed soon.

**Comment by JeroenVinke** [comment]
I am pretty sure that all these issues come back to one thing we have discussed before: https://github.com/monterey-framework/monterey/issues/161. But I believe that I was not clear enough. Please read the following carefully and let me know if we disagree on some points:

The terminal displays and keeps **all** messages, with the exception of useless NPM install messages. NPM outputs tens of thousands of messages (10MB+ worth) and when I initially wrote all these messages to the terminal of Monterey it crashed Monterey entirely and consistently.  So we **can not** do this.

I then started "npm install" from a normal terminal and noticed that messages of type "silly" and of type "info" were shown, but each message would be removed as soon as a new message comes in. Only messages of type "warning" and "error" are kept on the screen and are not "removed" when a new message comes in. 

So this is exactly what we are doing in Monterey now and it is the best alternative to Monterey crashing.

I do recognize the need to search through the entire NPM install log. That is why I wrote in https://github.com/monterey-framework/monterey/issues/161 that we could have a feature that writes the entire NPM output (10MB) to the project's directory. But this is something the user should specifically **enable** as there is no good reason to lose 10MB of diskspace for all NPM install's.

**Comment by adriatic** [comment]
I read all of the above - and agree with everything, particularly since it suddenly dawned on me that the `npm app` uses cursor addressing while writing its logs to the terminal

![image](https://cloud.githubusercontent.com/assets/2712405/17983872/c136694c-6adc-11e6-94fd-b15fa46729c2.png)

**Comment by adriatic** [comment]
It is quite obvious that the current implementation of the terminal is not ready to be even shown to Rob - seeing that "internal" `npm install` takes three times as long than "external" would not yield a good grade :smile: 

So, I would like to make the terminal instance that is shown while running long tasks to be static. It should only show the text like "not functional yet - coming soon"

The terminal instances created by the footer resident `terminal` button should stay as they are.

I will define the terminal requirements that pass my "muster" soon - although I believe that everyone know what they are.

**Comment by JeroenVinke** [comment]
You are assumkng that the terminal causes the slowdown, but it may still be something else

**Comment by JeroenVinke** [comment]
posting more [here](https://github.com/monterey-framework/monterey/issues/214)

**Comment by JeroenVinke** [comment]
@adriatic do you still feel that these improvements are needed?

**Comment by adriatic** [comment]
I think that we are fine now - I held that opinion close to my chest until I run all tests, but is is safe to say that all is cool

**Comment by JeroenVinke** [comment]
ok
