### ISSUE TITLE
Plan for Monterey User Manual

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#205]
In order to do this quickly while still useful, I will count on the pact that the initial readership will be exceptionally smart.

The **[document](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/)** will have three chapters:

### 3. Monterey tiles

The first two chapters will have the same internal structure (sub-chapters) which strongly resembles the testing template

- [ ] **Aurelia-CLI**
 - [ ]  Default ESNext
 - [ ]   Default ESNext
 - [ ]  Custom
<br><br>
- [ ] skeleton-esnext-aspnetcore

- [ ] skeleton-esnext-webpack

- [ ] skeleton-esnext

- [ ] skeleton-typescript-aspnetcore

- [ ] skeleton-typescript-webpack

- [ ] skeleton-typescript

- [ ] ZIP

For each of the above listed "types" I will present the series of screenshots (with only few words in-between) as shown **[here](https://github.com/monterey-framework/monterey/issues/195)**

Same approach for the second chapter

Third chapter should be obvious.

**Comment by JeroenVinke** [comment]
What is going to be written in "Managing existing application" and "Monterey tiles"?

**Comment by adriatic** [comment]
Thought that this would be obvious :-)

### 2. Managing existing application

For each template we show:

- How to open the app
- How to change something 
- How to run it again

The above explanation will be accompanied with basic demonstration of how to use NPM and JSPM tile or Aurelia-CLI tile

I will write some more as I creates some screenshots - hoping that I can write the docs and test at the same time.

**Comment by JeroenVinke** [comment]
> How to open the app
How to change something
How to run it again

Am I wrong in thinking that this is a very specific task and that one would need to be lucky if he wanted to do this exact task?

I must say that I really liked [this format](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/monterey_tiles/app_launcher.html). What do you think about explaining all individual parts of Monterey like that (where some parts fall outside the "Monterey Tiles" category)? 

Then users can pick relevant chapters of the manual themselves. They could pick "opening an existing application", "jspm package manager tile" and "running the application".

**Comment by adriatic** [comment]
I am planning to keep [monterey overview](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content) coexist with [user manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/). They have different focus and content sorting criteria - and this latter one would be people that like to see the details of how to use Monterey.

> Am I wrong in thinking that this is a very specific task and that one would need to be lucky if he wanted to do this exact task?

It seems that you ought to be wrong, as I see that workflow to be exactly what everyone will be doing:

1. Create the initial app

2. Start working the generated code

 2.1 Open the app

 2.2 Edit the app

 2.3 Build and run the app

 ... go to 2.2

**Comment by JeroenVinke** [comment]
Can't wait to see what it will look like :+1:

**Comment by adriatic** [comment]
Here is the bare beginning: https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/

**Comment by adriatic** [comment]
### Update

1. Created all screenshots for all templates highlighted in yellow - see [creating new application](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application.html)

2. Hope to bring the remainder of templates to the same level of being finished.

3. Write text for all of the sub-sections of the [creating new application](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application.html) chapter.

4. Discuss the content of the [managing existing applications](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/managing_existing_application.html) chapter with @JeroenVinke. I want to show things that might not yet be available - like
 - add a new module to the app
 - switch to a new version of aurelia / framework
 - switch to a new version of any module

**Comment by JeroenVinke** [comment]
As far as I know, we have done all this

**Comment by adriatic** [comment]
yes
