### ISSUE TITLE
Monterey and "classic" development tools

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#208]
#### This concept will become the chapter in Monterey documentation

Aurelia developers use a number of different development tools

### 1. Sublime and Console

 ![image](https://cloud.githubusercontent.com/assets/2712405/17972073/778f09f6-6aab-11e6-97d8-846e9751f7e9.png)

### 2. VS Code

![image](https://cloud.githubusercontent.com/assets/2712405/17972190/f064d608-6aab-11e6-9d2e-2db05335ba38.png)

**Comment by JeroenVinke** [comment]
I believe [this chapter](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/introduction/what_is_monterey.html) explains this very well
