### ISSUE TITLE
Monterey workflow

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#211]
This wizard page shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/17982746/4cad7200-6ad7-11e6-9b53-6b42ae090487.png)

is the smallest possible implementation of **`Monterey workflow`** feature I mentioned sometime earlier. It appears after the project was created and presents the "shortcut" to the case where these two checkboxes are not selected and are later invoked in a "step by step" fashion

**Comment by JeroenVinke** [comment]
Yes I remember. Is there a specific reason for creating this issue? if your intention was to name this the "monterey workflow" then I am all for it, as it makes sense

**Comment by adriatic** [comment]
I am raising it to introduce that name - and to indicate that at some point this may be the "location" where we could host a simple workflow engine like https://github.com/joyent/node-workflow.

The issue is not to automate a few consecutive activities from the Task manager - I am seeing a point in the future, where Monterey is used to deploy multiple applications to multiple hosting PaaS (like Engine Yard with Docker and or [Deis](http://deis.io/)

**Comment by JeroenVinke** [comment]
> I am seeing a point in the future, where Monterey is used to deploy multiple applications to multiple hosting PaaS (like Engine Yard with Docker and or Deis

Step for step Nikolaj :)

First step is: https://github.com/monterey-framework/monterey/issues/284

**Comment by adriatic** [comment]
So, if we are planning to ascent Mount Everest - you would like to be told that we need to make a trip to Kathmandu and that would be it?

Not my way of doing business :smirk_cat: )
