### ISSUE TITLE
Missing information on how to run the just built application

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#215]
Aurelia-CLI based apps are fine - as shown below, where running `au run --watch` results with the display of information how to run the app itself:

![image](https://cloud.githubusercontent.com/assets/2712405/18010627/43e0be90-6b7f-11e6-819f-cb1ff3903881.png)

This type of information is missing on the "skeleton class" of apps.

**Comment by JeroenVinke** [comment]
This has been resolved as monterey now runs `dotnet run` and it knows how to detect the URL from the output

**Comment by adriatic** [comment]
Let me come back with the confirmation that this is OK now.
