### ISSUE TITLE
Project randomly had a relative path to package.json

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#216]
All of my projects are present and even the last one I dealt with is selected as current:

![image](https://cloud.githubusercontent.com/assets/2712405/18021130/555d5a14-6bb3-11e6-976e-910146268bfc.png)

However, `Project info` tile says:

![image](https://cloud.githubusercontent.com/assets/2712405/18021184/ac16b670-6bb3-11e6-9943-d6ce704b0a97.png)

Note the "error indicator" which got set by clicking on the `NPM tile`:

![image](https://cloud.githubusercontent.com/assets/2712405/18021211/d622dcbe-6bb3-11e6-8c38-c8d6432f05dc.png)

The projects are here (and were here since I created them two days ago)

![image](https://cloud.githubusercontent.com/assets/2712405/18021232/02f58cdc-6bb4-11e6-927b-b3afbd96a117.png)

I believe that this problem has something in common with https://github.com/monterey-framework/monterey/issues/213

**Comment by adriatic** [comment]
### Added 5 minutes after

It is only this `skeleton-esnext-aspnetcore` project that has wrong path - which is RELATIVE - not absolute.

***It is almost certain that I created this project incorrectly (as you can see it does not appear on the files explorer screenshot)***

I deleted it and will recreate it. It is pretty sure bet that it will all work.

**Comment by adriatic** [comment]
Here is most likely place where I made the error in creating `skeleton-esnext-aspnetcore` project

**Comment by adriatic** [comment]
I thought that I found the culprit - 

![image](https://cloud.githubusercontent.com/assets/2712405/18021563/3cdbfb32-6bb6-11e6-9f5e-4c5a45be1828.png)

However, click on select folder resulted with the correct project path

* **Project name**
skeleton-esnext-aspnetcore
* **Project path:**
C:\work\tests\Monterey-testing-08252016\skeleton-esnext-aspnetcore
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.4
* **Chrome:**
52.0.2743.82
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-08252016\skeleton-esnext-aspnetcore\src\skeleton\package.json
* **Project is using JSPM**
* **JSPM version:**
0.16.41
* **Config.js path:**
C:\work\tests\Monterey-testing-08252016\skeleton-esnext-aspnetcore\wwwroot\config.js
* **Project is using Gulp**
* **gulpfile.js path:**
C:\work\tests\Monterey-testing-08252016\skeleton-esnext-aspnetcore\src\skeleton\gulpfile.js

#### also

Image 1 [here](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/skeleton-esnext-aspnetcore.html) shows that I did not leave the folder name undefined.

Everything is fine, no relative paths and I am sorry if I caused the storm in a teapot (I do not have any idea how could I have done that)

**Comment by JeroenVinke** [comment]
> (I do not have any idea how could I have done that)

me neither, and that is what worries me

**Comment by adriatic** [comment]
yep - I woke up at 3 AM and caught myself "running this scenario" in my head. Did not come up with anything - so, can you check the code to find out what happens if I click on the `Select folder` button, while the folder field is left blank? This situation should raise the error and prevent Monterey from  moving ahead.

![image](https://cloud.githubusercontent.com/assets/2712405/18021563/3cdbfb32-6bb6-11e6-9f5e-4c5a45be1828.png)

**Comment by JeroenVinke** [comment]
I get the absolute path of the folder that the windows explorer is in:

![image](https://cloud.githubusercontent.com/assets/2189477/18028119/145accfe-6c76-11e6-8886-b309be5913ef.png)

:(

**Comment by adriatic** [comment]
So do I now - I will do a bit of "pathology" research as I saved the monterey folder where that problem occurred, soon

**Comment by JeroenVinke** [comment]
http://screencast.com/t/GltuN529VHW

the screen asking for the directory is broken, where it sometimes accepts empty values

:tada:

**Comment by adriatic** [comment]
Did not see how that screen was broken in the screencast, but what's important is that you fixed it now and I do not need to worry about some random behavior in Monterey
