### ISSUE TITLE
npm & jspm grid columns too narrow (again / still)

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#219]
![image](https://cloud.githubusercontent.com/assets/2712405/18024755/244beec2-6be0-11e6-8645-ba958308c2eb.png)

**Comment by vegarringdal** [comment]
have you made it wider before making the screenshot?
(not close to a computer)

**Comment by adriatic** [comment]
I did not (knowing that this would indeed resolve the issue). Two reasons

1. I want to make all screenshots for the user manual be identical size - so until Montery can remember its size and position, this is not a good option for me.

2. Current problem with squished arrows happens with the Monterey default size - indicating high probability that other people with observe it as well.

**Comment by vegarringdal** [comment]
are you thinking about the small numbers after sort icon, thats for showing the sort order number..
in multisort you get 1 and 2 etc etc, and they are supposed to be smaller then the main text in header
![image](https://cloud.githubusercontent.com/assets/2901416/18027488/fba00cb2-6c64-11e6-9992-a79ce4f6d52c.png)

**Comment by adriatic** [comment]
I did not even realize that there is the sort number indicator - my problem report refers to the 4 "short horizontal bars" to the left of the number. Only now, I believe that I understand that this is an icon representing "sorting". 

So, please take my problem report as "make columns a bit wider, so that the bars and the small numbers get to be visible"

**Comment by JeroenVinke** [comment]
The sorting indicator with horizontal bars only becomes visible when columns are sorted (clicked) for the first time

**No sorting**
![image](https://cloud.githubusercontent.com/assets/2189477/18777625/6bd8cd50-8170-11e6-9850-8b980c2f4aa8.png)

**First sort order and sorting from low to high**
![image](https://cloud.githubusercontent.com/assets/2189477/18777627/6e1827be-8170-11e6-8a72-e8a353d211a6.png)
