### ISSUE TITLE
Skeleton-Typescript-Aspnetcore error message

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#221]
![image](https://cloud.githubusercontent.com/assets/2712405/18027762/82e5b080-6c3a-11e6-87dd-5cef6c3c02d6.png)

Did not verify the correct function of this app as I do not (yet) know how to run it. I will look into that once I finish taking screenshots.

**Comment by JeroenVinke** [comment]
Interesting, since this is a typescript project, it should have offered you to install typescript definitions in the last screen of the scaffolding wizard. Since this is a very new feature (created yesterday) I will try it with the skeleton-typescript-aspnetcore skeleton.

**Comment by adriatic** [comment]
I just rebuilt Monterey after running `git pull:

```
λ git pull
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 27 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (27/27), done.
From https://github.com/monterey-framework/monterey
   32d980c..edd85a0  master     -> origin/master
Updating 32d980c..edd85a0
Fast-forward
 app/src/plugins/about/about-modal.html           |  2 +-
 app/src/plugins/errors/error-modal.html          |  5 ++++
 app/src/plugins/errors/error-modal.ts            | 15 +++++++++++-
 app/test/unit/plugins/errors/error-modal.spec.ts | 29 ++++++++++++++++++++++++
 4 files changed, 49 insertions(+), 2 deletions(-)
 create mode 100644 app/test/unit/plugins/errors/error-modal.spec.ts
```

This original problem is very repeatable - just by running `gulp watch` task:

![image](https://cloud.githubusercontent.com/assets/2712405/18028078/9425b16c-6c42-11e6-905f-4fe1e2167f07.png)

There are also toasts flashing in the bottom right corner of my own monitor - did not manage to catch them as screen shots

**Comment by adriatic** [comment]
***I am really enjoying the fact that Monterey is quite predictable in its behavior, while rooting out some smaller bugs***

**Comment by JeroenVinke** [comment]
Me too, I really like seeing:

- NPM install
- JSPM install
- gulp watch

in the task manager :)

**Comment by adriatic** [comment]
Not only that - but Monterey is completely happy with me intervening with any of these tasks behind its back

**Comment by JeroenVinke** [comment]
This will be fixed as part of https://github.com/monterey-framework/monterey/issues/227. I'd prefer to close this issue and reopening it if this exact error returns
