### ISSUE TITLE
Need a well designed setup to test auto-update

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#222]
I would really like to allow at least @vegarringdal @JeroenVinke and @adriatic to be able to verify correct auto-update feature, on **all** supported platforms:

1. Fetch Monterey installer that delivers version x
2. Run the installer and resulting Monterey, verifying the version number.
3. @JeroenVinke creates the Monterey version x+1 and deploys it
4. Everyone starts the current Monterey and observes whether the auto-installer will offer and deliver the version x+1

I would suggest to keep this whole setup persisted somewhere handy.

**Comment by JeroenVinke** [comment]
will do this as part of https://github.com/monterey-framework/monterey/issues/328
