### ISSUE TITLE
Create dotnet plugin

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#225]
the skeleton-typescript-aspnetcore skeleton does not use `gulp watch` to start the webserver, which is why the url is not shown in the output of `gulp watch` (and therefore not picked up by monterey: https://github.com/monterey-framework/monterey/issues/215)

turns out that this skeleton uses dotnet core:
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-aspnetcore/src/skeleton#running-the-app-without-visual-studio

this will require additional work, as monterey needs to detect dotnet projects and needs to run "dotnet restore" and "dotnet run"

**Comment by adriatic** [comment]
I intentionally did not pursue the dotnet core samples beyond the point reached at this time in the [user manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application.html)

**Comment by JeroenVinke** [comment]
One thing that is necessary implementation-wise is that we need to detect whether or not a project is a dotnet project. So there needs to be a file (or a property in a file) that monterey can use to know wheter or not to run `dotnet restore` and `dotnet start`. Is dotnet a task runner just like gulp? If so, then we need to know which tasks there are (just like `gulp --task-list-simple`)

**Comment by adriatic** [comment]
No, [dotnet core](https://github.com/dotnet/core) started with the same approach as Aurelia-CLI - with [this tool](https://github.com/dotnet/cli), and has since grown a lot, where this basic piece (dotnet-cli) is used in a [family of tools](https://www.microsoft.com/net/core/platform).

Learning all that stuff is highly ranked on my to do list !!

**Comment by JeroenVinke** [comment]
Done with latest commits
