### ISSUE TITLE
NPM install barely shows "progress messages"

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#226]
continuation of https://github.com/monterey-framework/monterey/issues/214#issuecomment-242931308

Only warnings and errors, and the tree after installation is complete are shown when `npm install` is ran, giving the user almost no sense of progress. At a very minimum we should display messages like "still installing..." to let the user know things are actually happening

**Comment by vegarringdal** [comment]
do you get this when using the terminal I added, when you run npm install in one (On mobile only atm)

**Comment by JeroenVinke** [comment]
nope :(

**Comment by JeroenVinke** [comment]
good thinking though

**Comment by vegarringdal** [comment]
k, then normal cmd does not display anything either then.
why should we display more then normal installs do...

**Comment by JeroenVinke** [comment]
I just remembered that I had disabled the progress indicator (which is enabled by default). After enabling it again your terminal did show the progress indicator:

![image](https://cloud.githubusercontent.com/assets/2189477/18029250/35c2c6c2-6c93-11e6-80fd-d1bbc6bf83c3.png)

**Comment by vegarringdal** [comment]
wonder if we can run something like npm install in that special spawn (pty.js) and know when its finished... not usefull if not, atm I run default cmd.exe on windows, maybe just running npm install works like normal spawn

**Comment by JeroenVinke** [comment]
I don't think this is something we need to resolve as it hasn't bothered me over the last few weeks :)

**Comment by adriatic** [comment]
+ack
