### ISSUE TITLE
electron-connect client loaded 2 times, remove the one from index.html

### ISSUE THREAD

**Issue by vegarringdal** [monterey-framework/monterey#228]
electron-connect client loaded 2 times, remove the one from index.html

remove:
https://github.com/monterey-framework/monterey/blob/master/app/index.html#L12

keep:
https://github.com/monterey-framework/monterey/blob/master/app/index.js#L64

This will bring us down to same index.html for production and dev, unless I overlooked something

**Comment by JeroenVinke** [comment]
Could be the cause of https://github.com/monterey-framework/monterey/issues/160#issuecomment-241013290
