### ISSUE TITLE
How much of TypeScript we want in monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#23]
The simplest way to "convert" an `esnext` project to a Typescript project is to change the file extensions from `.js` to `.ts`. That however does not buy us any of the real advantages of using TypeScript as the development language, so I would like to initiate a brief discussion on what will be the outcome of this switch. 

> Types enable JavaScript developers to use highly-productive development tools and practices like static checking and code refactoring when developing JavaScript applications.

> Types are optional, and type inference allows a few type annotations to make a big difference to the static verification of your code. Types let you define interfaces between software components and gain insights into the behavior of existing JavaScript libraries.

> These features are available at development time for high-confidence app development, but are compiled into simple JavaScript that targets ECMAScript 3 (or newer) environments.

**Comment by JeroenVinke** [comment]
I guess we can start by adding types to the parts of the framework that are used most

**Comment by adriatic** [comment]
:+1:

**Comment by JeroenVinke** [comment]
In places where interfaces would be helpful yes. For example, [IStep.ts](https://github.com/monterey-framework/monterey/blob/master/app/src/scaffolding/istep.ts) defines what a step of the project scaffolding wizard looks like.

**Comment by JeroenVinke** [comment]
closing this as we gradually will add more and more types
