### ISSUE TITLE
Not enough storage in terminal

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#230]
https://github.com/monterey-framework/monterey/issues/214#issuecomment-242939587

@adriatic the terminal of the taskmanager is not a real terminal (just a div with a black background and white text). The terminal you are getting the "not enough storage" error in is a real terminal, but it did not change, and i'm not getting that error either.

found these links:
https://support.microsoft.com/en-us/kb/106167
http://serverfault.com/a/173427

is your normal command prompt (cmd.exe) working OK?

**Comment by adriatic** [comment]
My normal (Windows) cmd.exe is working just fine. I am not sure exactly why did it start invoked from Monterey in admin mode, though. I will look into that a bit later

**Comment by JeroenVinke** [comment]
Closing this as I believe it is a local issue
