### ISSUE TITLE
Project list does not resize well

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#231]
As part of adding splitters to some screens I tried to add one to the main screen.

![image](https://cloud.githubusercontent.com/assets/2189477/18032885/9c2036f8-6d14-11e6-958a-b8f9094360f2.png)

Note that the "my projects" column does not resize since it has a 300px fixed width set by the grid. This is not easily fixed since the grid somewhat depends on the absolute positioning. So until we either fix this problem with the grid, or replace it with something that does resize, we can't add a splitter to the main screen

Added this to the `main-splitter` branch

**Comment by JeroenVinke** [comment]
This is not at all a hig priority issue, but still something to keep in mind

**Comment by vegarringdal** [comment]
if I dont remember wrong the row repeat part of the grid is 100%,  when using that we can prb make it work since you have full control, but if we do not need sorting/filter in that list, then we can replace it

**Comment by vegarringdal** [comment]
but in that list, could it be usefull with infomation like jspm project, cli etc?

**Comment by vegarringdal** [comment]
@JeroenVinke 

edit the ```v-grid-col``` element to ```v-grid-row-repeat```
here:
https://github.com/monterey-framework/monterey/blob/master/app/src/main/components/project-list.html#L11

since we only have 1 column, I think that might work (might haveto do minir tweaks after)

**Comment by vegarringdal** [comment]
for the sort icon replace project-list-header with this
```
.project-list-header {
      background-color: #dfdfe1;
      color: #70509D;
      max-height: 36px;
      min-height: 36px;
      text-align: center;
      font-weight: 400;

      .vGrid-glyphicon-sort-asc{
        right:15px;
      }
      .vGrid-glyphicon-sort-desc{
        right:15px;
      }
    }
```

Here:
https://github.com/monterey-framework/monterey/blob/master/app/styles/less/main.less#L128

**Comment by JeroenVinke** [comment]
:sparkles:
