### ISSUE TITLE
Project may have multiple taskrunners

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#232]
A "taskrunner" is `gulp`, `aurelia-cli` (for `au watch`) but also `dotnet` (for `dotnet run`). And a project can use both gulp and dotnet, so monterey should be able to handle the fact that a project may have multiple taskrunners

**Comment by adriatic** [comment]
## YES

**Comment by adriatic** [comment]
That is what I am missing at most now - and did not even have the chance to say it (mind melding at its best)

**Comment by JeroenVinke** [comment]
to take into consideration: https://github.com/monterey-framework/monterey/issues/224

**Comment by JeroenVinke** [comment]
implemented with latest commits
