### ISSUE TITLE
Documenting the ZIP template

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#234]
Given this URL: https://github.com/aurelia-ui-toolkits/cm-bridges

What do I tell Monterey in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/2712405/18035147/541e48dc-6d1d-11e6-827f-3acb2a885f36.png)

The alternative form of this same question is: How do I tell GitHub to create the zip of my repo content?

The answer is likely: **create the release**. Since this repo will have multiple apps (just like Aurelia Navaigation Skeleton does) I am not sure how to make this release.

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18035174/51d31782-6d50-11e6-8c74-28fc832ded2f.png)

and the subfolder would be "originial"

**Comment by adriatic** [comment]
Magnificent, thanks :smile_cat:

**Comment by JeroenVinke** [comment]
Closing this
