### ISSUE TITLE
Release sync

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#237]
### List of tasks that need to be done in order to finish this pending release

- [x] [Monterey user manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/)
- [x] [Monterey overview](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/)
- [x] [Monterey technical documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-technical-documentation/content/)
- [x] Design, implement and document the registry of standard tiles
- [x] Add the support for persisting the main window location and size (like this https://www.npmjs.com/package/electron-window-state-manager)
- [x] https://github.com/monterey-framework/monterey/issues/188
- ...

**Comment by JeroenVinke** [comment]
https://www.npmjs.com/package/electron-window-state-manager works very nicely
