### ISSUE TITLE
Tiles should show the "current application"

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#238]
**Note:** now is not the time for systematic rooting of all such issues - reporting this as I just realized that 'NPM` tile completely overlays the main view and the information about which application's dependencies is lost.

Case in point: click on `NPM` tile in this stuation

![image](https://cloud.githubusercontent.com/assets/2712405/18094497/abab179e-6ea1-11e6-80c9-37cf93b60f50.png)

results with 

![image](https://cloud.githubusercontent.com/assets/2712405/18094445/79f47560-6ea1-11e6-8132-43eadb4225d4.png)

**Comment by vegarringdal** [comment]
it was shown in the title when I did that PR.
https://drive.google.com/file/d/0B_wM5SJf8IXoY0pIWURpYVFEOWc/view?usp=sharing

maybe it just got lost somewhere :+)

**Comment by JeroenVinke** [comment]
Yep, forgot to rename that when SelectedProject got introduced

![image](https://cloud.githubusercontent.com/assets/2189477/18168425/dab92ffc-7055-11e6-802e-fc1f24852ba7.png)

**Comment by vegarringdal** [comment]
nice :-)

**Comment by adriatic** [comment]
:smile:
