### ISSUE TITLE
why is my logfile removed?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#239]
Just started Monterey after rebuilding it from

```
λ git pull
remote: Counting objects: 30, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 30 (delta 19), reused 30 (delta 19), pack-reused 0
Unpacking objects: 100% (30/30), done.
From https://github.com/monterey-framework/monterey
   9630a2c..c9d9052  master     -> origin/master
Updating 9630a2c..c9d9052
Fast-forward
 app/src/plugins/task-manager/task-bar.ts           |   4 +
 app/src/scaffolding/activities.json                |   8 +-
 app/src/scaffolding/{zip => github}/run.html       |   0
 app/src/scaffolding/{zip => github}/run.ts         |  15 +--
 app/src/scaffolding/github/url-input.html          |  23 +++++
 app/src/scaffolding/github/url-input.ts            | 105 +++++++++++++++++++++
 app/src/scaffolding/project-description.html       |   8 +-
 app/src/scaffolding/scaffold-project.ts            |  13 ++-
 app/src/scaffolding/zip/url-input.html             |  18 ----
 app/src/scaffolding/zip/url-input.ts               |  39 --------
 app/src/shared/github-api.ts                       |   4 +
 .../unit/plugins/task-manager/task-bar.spec.ts     |   5 +-
 app/test/unit/scaffolding/github/url-input.spec.ts |  64 +++++++++++++
 13 files changed, 225 insertions(+), 81 deletions(-)
 rename app/src/scaffolding/{zip => github}/run.html (100%)
 rename app/src/scaffolding/{zip => github}/run.ts (85%)
 create mode 100644 app/src/scaffolding/github/url-input.html
 create mode 100644 app/src/scaffolding/github/url-input.ts
 delete mode 100644 app/src/scaffolding/zip/url-input.html
 delete mode 100644 app/src/scaffolding/zip/url-input.ts
 create mode 100644 app/test/unit/scaffolding/github/url-input.spec.ts
```

Why did this `removed old logfile: C:\Users\nik\AppData\Roaming\monterey\logs\2016-08-25.csv.txt` happen?

**Comment by vegarringdal** [comment]
we added a delete x days old log files, dont want to use to much space :-)

**Comment by adriatic** [comment]
Makes sense for some people (not me as I have more disk space than the king of Arabia). Best regulated by a preference.

**Comment by vegarringdal** [comment]
yes :-)

**Comment by JeroenVinke** [comment]
one problem: the log files are kept in the same folder for development as for real use, so whenever you use the "clear cache" function the default will be to remove old log files, and it will do that.

**Comment by adriatic** [comment]
I do not believe that the term `clear cache` should stay as it is (not well) defined now. I considered it as a quick way getting rid of the history because a "crude" bug (likely to pop up in the early stage of development) made it difficult to continue using Monterey. 

The log files were introduced as a help for support - allowing us to see the history of Monterey's use that led to some problem that would not be easy to solve otherwise. If we plan to use this data in this way, discussing when to erase them makes little sense to me. We also need to defined more precisely what can be safely removed and what not.

I believe that this issue needs to be discussed some more.

**Comment by JeroenVinke** [comment]
> I do not believe that the term clear cache should stay as it is (not well) defined now. I considered it as a quick way getting rid of the history because a "crude" bug (likely to pop up in the early stage of development) made it difficult to continue using Monterey.

Which is exactly why it needs to stay

> The log files were introduced as a help for support - allowing us to see the history of Monterey's use that led to some problem that would not be easy to solve otherwise. If we plan to use this data in this way, discussing when to erase them makes little sense to me

I disagree for a couple of reasons:

1. log files become more irrelevant over time. It is unlikely that a user will report an issue that happened weeks ago
2. allows us to log more data, without worrying about wasting too much of the users disk space. Logging more (and cleaning up files) is more important than logging less and keeping the files around
3. removing log files is good ettiquette, so this makes perfect sense to me

**Comment by JeroenVinke** [comment]
were you suggesting to rename the clear cache menu item? If so I agree

**Comment by adriatic** [comment]
> I disagree for a couple of reasons:
1.
2.
3.

You would be a good debater, as after reading your arguments, I could easily switch my position and take yours :smile: . Must be that the truth is somewhere in the middle and as long I see that you have not forgotten the basic reason for introducing the logs :smiling_imp: - I will not argue my points.

**Comment by adriatic** [comment]
On `clear cache` issue

If this actions only deletes the log file(s) then it should be called that way (`delete logs`). Otherwise, if it addresses several different data structures they should be all listed on the `clear` command, with check-boxes that will allow the user to be selective.
