### ISSUE TITLE
github repo chooser

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#24]
Creating the project from a zip file is a terrific way to ensure that we do not allow users to grab stuff from branches. That itself will save **many** frustrations:

I would like to propose adding our own repo chooser to make the selection of the monterey project source as easy as it is to select the destination

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16548097/8618875a-4151-11e6-916e-ba8a96d70d7f.png"></img>
 <br><br>
</p>

**Comment by JeroenVinke** [comment]
what would the github repo chooser look like? I like the idea, just want to see if we can do it

**Comment by adriatic** [comment]
Since there is no such native application, we cannot make a platform specific version, but rather a generic version. I will make a moqup for it and I am pretty sure that GitHub API is sufficiently rich to allow everything we need.

**Comment by JeroenVinke** [comment]
> I will make a moqup for it

:+1: 

>  and I am pretty sure that GitHub API is sufficiently rich to allow everything we need.

I think so too

> monterey app should invoke it the same way as files explorer / whatever the name of that thing is on mac

I agree

**Comment by JeroenVinke** [comment]
tracking implementation in https://github.com/monterey-framework/monterey/issues/32
