### ISSUE TITLE
Store default project directory of scaffolding wizard in session

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#241]
Usually developers have one development directory containing all their projects. So we can store this directory in settings so we can provide this as the default value in in the project scaffolding wizard

**Comment by vegarringdal** [comment]
good suggestion, default could be my documents

**Comment by adriatic** [comment]
For some reason, I really dislike `my documents` folder - likely because it looks like a garbage dump on most computers.

I would propose to add the path to the development folder to user preferences data.

**Comment by vegarringdal** [comment]
I only have github projects :-)
but ofc, could force users to select it the first time, /maybe checkbox in the wizard where you could check :"set at default folder"
