### ISSUE TITLE
It should be easier to add new settings

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#242]
We should make it very easy to create new settings, and the preferences screen should dynamically show form controls for these settings. This way we are more inclined to add new settings, knowing that there is little overhead

**Comment by adriatic** [comment]
I agree with the basic premise and do not yet see how will that be done. Since I already created the [Preferences chapter](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/preferences.html), please add what needs to be in that chapter.
