### ISSUE TITLE
Rename projects

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#243]
It should be possible to rename projects (the name is not necessarily the name in the package.json file)

**Comment by adriatic** [comment]
Let me know when this is in - so I can show how to use it (ideally a context menu in Task manager, since it reaches everywhere - but this may not be easy to implement)

**Comment by JeroenVinke** [comment]
Thinking of adding the rename option to the context menu of the project list instead, which was just added:

![image](https://cloud.githubusercontent.com/assets/2189477/18146900/7c7b4ebc-6fd2-11e6-9cd5-c9dac1644b6c.png)

**Comment by adriatic** [comment]
I use context menus (and expect them in all tools) a lot - it is very convenient, unless (like in Gitter), one can cause a lot of harm if allowing `delete` without checking whether that was the intent :-)
