### ISSUE TITLE
Transition from Developer to Task manager should be "smoother"

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#247]
![image](https://cloud.githubusercontent.com/assets/2712405/18173084/3ee8a84c-7036-11e6-87a0-1b0eca883703.png)

It requires the addition click on that list item to see this "updated" view

![image](https://cloud.githubusercontent.com/assets/2712405/18173148/811f605c-7036-11e6-8a84-3953ea18efbf.png)

**Note** however that this updated content ( console with its own content) does not match the actual situation as the status (above the terminal window) should be `Running`  - not `finished`.

**Comment by JeroenVinke** [comment]
What's good to mention is that the developer window is only visible for monterey developers, not for users. It allows us to quickly generate a set of tasks for the taskmanager, or to throw an error (if we want to bring up the Errors dialog).

**Comment by JeroenVinke** [comment]
But even then, it's good to mention the current project name, so i'll do that

**Comment by adriatic** [comment]
I would suggest that you just opened the door to my dreamworld where my interaction with Monterey (in the context of developing my other things) would be always through this interface - which I insist on calling a workflow.

The details will change as we move ahead, I just want you to keep this concept in mind.
