### ISSUE TITLE
Ended task should not be able to start

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#248]
![image](https://cloud.githubusercontent.com/assets/2712405/18173436/8f4ec1f8-7037-11e6-962f-f08958b7f61d.png)

Note that Monterey knows better :smile: !

![image](https://cloud.githubusercontent.com/assets/2712405/18173383/60130386-7037-11e6-89ee-40a65d3bb6eb.png)

**Comment by JeroenVinke** [comment]
Pretty stupid of me. Previously, when you had "jspm install" and "gulp watch" (where gulp watch depends on jspm install) then it would start "gulp watch" when you would cancel "jspm install". But when you cancel `jspm install` then there is no chance that `gulp watch` will run successfully. So now when you cancel the "parent" task, it cancels all "children" (and children of children etc)

**Comment by JeroenVinke** [comment]
In light of https://github.com/monterey-framework/monterey/issues/250, should we display cancelled tasks?

**Comment by adriatic** [comment]
> should we display cancelled tasks?

Yes, I agree with your reasoning - as long as we can get rid of them eventially.
