### ISSUE TITLE
user friendly navigation issues

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#25]
- [x] support the project redefinition

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16548134/1313bd7c-4153-11e6-9387-20ae3c297453.png"></img>
 <br><br>
</p>

- [ ] the navigation controls should always reflect your current state and signal where can you go from there. Here is an example of such "active" breadcrumb

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16549191/39af6f32-416a-11e6-9bee-c0d79f05ef3c.png"></img>
 <br><br>
</p>

Here is a lot more complex "wizard" that guides the user through the process of creation and management of the workflow which assists the patient's discharge from the hospital care and subsequent home based recovery;

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16549259/1a7c8c52-416b-11e6-8b1b-473c24484aa0.png"></img>
 <br><br>
</p>

With the proper dose of humility, I will point out that my team at the time got a very large grant for this from the Robert Wood Johnson foundation, a bit smaller grant from Washington State, even smaller, but very significant funding from Microsoft and the application was deployed at several counties in WA State.

**Comment by JeroenVinke** [comment]
> the navigation controls should always reflect your current state and signal where can you go from there. Here is an example of such "active" breadcrumb

That one will be difficult. Imagine if you choose to scaffold an aurelia-cli project, and when you're at the last step of the wizard (the project description page) you click on the button to get back to the first step. If you then choose to scaffold a skeleton-navigation the entire flow of the wizard is different than what you had when you selected aurelia-cli. Am I right when I say that this is only possible if we would have a single flow (or path) throughout the entire wizard?

**Comment by JeroenVinke** [comment]
Another example: when the user is on the first screen of the wizard it is not clear how many steps there are. Hoe many steps there are depends on the choices made by the user

**Comment by adriatic** [comment]
I handled all such issues so I know the answers. It is not obvious that changing the UI to fit this navigation model would be of significant enough benefit to warrant subsequent discussions and time to do that.

> when the user is on the first screen of the wizard it is not clear how many steps there are

That is rather obvious - but when the user decides for the first step, he might appreciate seeing the whole trip in front if him.

**Comment by JeroenVinke** [comment]
Closing this for now as the amount of work that would go into implementing the breadcrumb would not be worth the reward. (there is not much to gain since the wizard is pretty great already)

**Comment by adriatic** [comment]
Agreed?
