### ISSUE TITLE
Too many dead tasks clog the view

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#250]
![image](https://cloud.githubusercontent.com/assets/2712405/18173519/e3dd7f84-7037-11e6-825e-784335b3d3fe.png)

I believe that these should be removed from the list as they are `ended`

**Comment by JeroenVinke** [comment]
well there is a "Show finished" checkbox:

![image](https://cloud.githubusercontent.com/assets/2189477/18180090/b159cf56-7085-11e6-9244-837d1dfbb561.png)

**Comment by adriatic** [comment]
I missed that - so I find this issue properly addressed now

**Comment by JeroenVinke** [comment]
We can save the state of that checkbox in the session (using a setting in the preferences), right now the checkbox is always checked by default
