### ISSUE TITLE
Skeleton-Esnext-Aspnetcore shows incorrect configuration

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#251]
![image](https://cloud.githubusercontent.com/assets/2712405/18176450/a9d32396-7043-11e6-8b6e-b2f3661bbf88.png)

**Comment by JeroenVinke** [comment]
mistakenly included the fix in https://github.com/monterey-framework/monterey/commit/d9d31648d66bd56349994049a14fd4cd5344e48e
