### ISSUE TITLE
Write the Preferences chapter for User manual

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#254]
Here is the [placeholder](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/preferences.html)

**Comment by JeroenVinke** [comment]
Also write [Support toolbar item](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/support.html)

**Comment by adriatic** [comment]
Yep - in the works https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/support.html

**Comment by JeroenVinke** [comment]
can this be closed? or are you planning to add more text to https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/preferences.html?

**Comment by JeroenVinke** [comment]
Closing this as i'm perfectly happy with what's in the preferences article
