### ISSUE TITLE
don't assume all `gulp` enabled projects have a `gulp watch` command

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#260]
Aurelia libraries do not have a `gulp watch` task, so monterey needs to check if it exists before proposing to run it after scaffolding such project via the github template

**Comment by JeroenVinke** [comment]
This is a tricky one. Gulp demands that everything is done via the locally installed gulp (in the node_modules of the project directory, and not gulp installed in the global node_modules folder). This means that we need to `npm install` before we can check which gulp tasks are available. 

![image](https://cloud.githubusercontent.com/assets/2189477/18204529/9e93b1e6-711d-11e6-8586-103acd1c716c.png)

Here we do not know which gulp tasks the project has, not until "npm install" has completed. So we can't show a list of possible tasks either. But I do not think it is a big deal yet, considering:

1. the user can uncheck "gulp watch"
2. monterey knows that it does not exist when it's about to start the task, so it does nothing and continue:

![image](https://cloud.githubusercontent.com/assets/2189477/18204634/18ad7fca-711e-11e6-8599-6863c288c3cc.png)

**Comment by adriatic** [comment]
I do not see what more could be done without having the `will need gulp watch` / `will not need gulp watch` declaration in package.json :smile:

**Comment by JeroenVinke** [comment]
good idea, the package.json standard has a `start` script, like the webpack skeleton uses [here](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/package.json#L32). But this is not used in the majority of projects (for example, the [skeleton-esnext](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext/package.json#L21-L24)).

**Comment by adriatic** [comment]
Pioneers always suffer from lack of good standards. As we plan to support projects other than Aurelia-CLI or Aurelia navigation skeletons based, we cannot gain much even if Rob would put the needed "metadata" into these package.json files.

We could certainly make Monterey to add such data once it has correctly recognized the project type (app or lib), so all Monterey created app would be good to go later.

**Comment by JeroenVinke** [comment]
Closing this for now, as I agree with:

> I do not see what more could be done without having the will need gulp watch / will not need gulp watch (or app / lib) declaration in package.json
