### ISSUE TITLE
building freshly installed clone results with a fork

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#265]
```
Installed Forks

                                 npm:aurelia-framework 1.0.1 1.0.2
```

jspm update aurelia-framework does not help

```
λ jspm update aurelia-framework
     Looking up npm:aurelia-framework
     Updating registry cache...
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-dependency-injection
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-metadata
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-path
     Looking up npm:aurelia-task-queue
     Looking up npm:aurelia-templating
     Downloading npm:aurelia-binding@1.0.3
     Downloading npm:aurelia-templating@1.0.1
ok   Installed npm:aurelia-templating@^1.0.0 (1.0.1)
ok   Installed npm:aurelia-binding@^1.0.0 (1.0.3)
ok   Up to date - aurelia-framework as npm:aurelia-framework@^1.0.0-beta.1.1.4 (1.0.2)
     Clearing configuration for npm:aurelia-binding@1.0.1
     Clearing configuration for npm:aurelia-templating@1.0.0
     Removing package files for npm:aurelia-binding@1.0.1
     Removing package files for npm:aurelia-templating@1.0.0

     The following existing package versions were altered by install deduping:

       aurelia-binding 1.0.1 -> 1.0.3
       aurelia-templating 1.0.0 -> 1.0.1

     To keep existing dependencies locked during install, use the --lock option.
     Installed Forks

                                 npm:aurelia-framework 1.0.1 1.0.2

     To inspect individual package constraints, use jspm inspect registry:name.


ok   Install complete.
```

#### Some version locking has to happen :smile: .

**Comment by JeroenVinke** [comment]
did you run the command I gave to you?

**Comment by adriatic** [comment]
check the `jspm update aurelia-framework does not help` comment in the first entry in this issue

**Comment by JeroenVinke** [comment]
try `jspm install aurelia-framework`

**Comment by adriatic** [comment]
```
λ jspm install aurelia-framework
     Updating registry cache...
     Looking up npm:aurelia-framework
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-dependency-injection
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-metadata
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-path
     Looking up npm:aurelia-task-queue
     Looking up npm:aurelia-templating
ok   Up to date - aurelia-framework as npm:aurelia-framework@^1.0.2 (1.0.2)
     Installed Forks

                                 npm:aurelia-framework 1.0.1 1.0.2

     To inspect individual package constraints, use jspm inspect registry:name.


ok   Install complete.
```

**Comment by adriatic** [comment]
This is the case for Monterey to resolve (if it were so smart already)

**Comment by JeroenVinke** [comment]
it is mad:

![image](https://cloud.githubusercontent.com/assets/2189477/18211797/ce0a62b8-713f-11e6-9cd5-96b7341fa321.png)

**Comment by adriatic** [comment]
The current Monterey's `app/config.json` has `"aurelia-framework": "npm:aurelia-framework@^1.0.2"`

Monterey from 8/27  `"aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.1.4",`

Why this change?

**Comment by JeroenVinke** [comment]
> The current Monterey's app/config.json has "aurelia-framework": "npm:aurelia-framework@^1.0.2"
Monterey from 8/27 "aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.1.4",
Why this change?

Somehow [this change](https://github.com/monterey-framework/monterey/pull/255/commits/dcc7a8aa7269339cf125df853fc3d4c58b6109b6#diff-90deddb0a32bd08f975a2acf3723ccdcR152) added aurelia-framework@1.0.2 to config.js, even though there was an aurelia-framework@1.0.1. I have updated all the references from package.json (the ^beta ones to the 1.0.0 ones) and after `jspm update` it resolved the fork. Strange thing is that we were working with 1.0.0 already, so the `@^1.0.0.beta.1.0.0` can't be the reason for it not wanting to update

**Comment by adriatic** [comment]
### Am I happy that we caught this one

**Comment by adriatic** [comment]
Confirmed fix:

### `ok   Install tree has no forks.`

**Comment by vegarringdal** [comment]
maybe Im the one that managed to make this mess, sorry, I know Im the reason for 1.0.2 :-)
sorry

**Comment by adriatic** [comment]
No need to be sorry, Vegar - you are doing a great job, making a lot of good additions to Monterey and we would not be even close to the functionality we have now, without you.
