### ISSUE TITLE
Permission denied, rename error on mac

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#268]
![image](https://cloud.githubusercontent.com/assets/2189477/18213608/5709b3da-7149-11e6-95db-6ebdd050e99a.png)

Could be a local issue with my virtual machine

**Comment by adriatic** [comment]
I will try this on my **real** mac and come back here

**Comment by JeroenVinke** [comment]
False alarm, the `scaffolding` folder I selected was created by root, while monterey is running under a normal user account

**Comment by adriatic** [comment]
OK
