### ISSUE TITLE
Add icons to tiles

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#27]
![image](https://cloud.githubusercontent.com/assets/2189477/16557525/a7ed60dc-41e0-11e6-91de-9e81f9fb9bf8.png)

For example, we could add [this icon](https://raw.githubusercontent.com/isaacs/npm/master/html/npm-256-square.png)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16567178/dea1f6f2-421b-11e6-91bc-1bf8ac62a304.png)

**Comment by adriatic** [comment]
Simply lovely. In particular, I like the loss if the starting pop-up dialog. This rapidly approaches my wish-list :-)
