### ISSUE TITLE
Cannot use folder path as unique key for the applicationstate

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#272]
![image](https://cloud.githubusercontent.com/assets/2189477/18216277/031fd1ca-7156-11e6-8ba8-6b8234ac81a0.png)

Guess what happens to your applicationstate when you update

**Comment by adriatic** [comment]
You get a new one - without asking for this to happen :-)

**Comment by JeroenVinke** [comment]
we have a winner ;)

**Comment by adriatic** [comment]
adding the time stamp ?

**Comment by JeroenVinke** [comment]
maybe we can use regex to strip out the version.

**Comment by adriatic** [comment]
That would work
