### ISSUE TITLE
Switching between projects too quickly causes error

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#273]
By switching between projects using the arrow keys on my keyboard caused an error. Nothing breaks though. @vegarringdal something for next week :smile: 
```
TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLInputElement.<anonymous> (file:///Users/jeroen/Development/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.2.4/vGrid/v-grid-attributes-key-move.js:43:35)
    at vGridAttributesKeyMove.dispatchCellClick (file:///Users/jeroen/Development/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.2.4/vGrid/v-grid-attributes-key-move.js:61:27)
    at file:///Users/jeroen/Development/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.2.4/vGrid/v-grid-attributes-key-move.js:209:20
    at file:///Users/jeroen/Development/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.2.4/vGrid/v-grid-attributes-key-move.js:107:11
```

**Comment by adriatic** [comment]
This (switch requests) should be buffered and serialized - something that would not impact normal use (I would not even think of overwhelming Monterey in such cruel way)

**Comment by JeroenVinke** [comment]
I think this is something that needs to be fixed in the v-grid

**Comment by adriatic** [comment]
Yes, that is what I meant

**Comment by vegarringdal** [comment]
Ill have a look at it, assign this to me so I find it fast, I have option to disable this for the simple html option we use I added in 0.2.0. 
we want to be able to use arrow keys?

**Comment by vegarringdal** [comment]
one thing is great, Ive improved some parts if my grid with monterey/electron, resizing of window, something my other demos would not catch easly :-)
And now mayve something new :-)

**Comment by vegarringdal** [comment]
@jeroen can you remove v-key-move from the input, we did go over to the row repeat from simple html, that attribute was never made for that setup.

**Comment by vegarringdal** [comment]
@jeroenVinke did u give it a try?
btw, I can look at adding a own attribute for handling this if its wanted, but figured errors awsy is first priority :-)

**Comment by vegarringdal** [comment]
Guessing that solved the error messages? :-)

**Comment by JeroenVinke** [comment]
Yeah, by disabling the feature :P

**Comment by vegarringdal** [comment]
less is more :-)
