### ISSUE TITLE
Enumerating Monterey's features

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#280]
As I am preparing the email for Monterey evaluators, I would like to be sure that I have listed all Monterey features from a typical user's viewpoint, in a very compact form.

Monterey can be used to:

1. ...
2. ...

***

Note: I do not want to condense the [Monterey user manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/) into several bullet points, I want a more high level view that would appeal to Aurelia application developer in two categories

- ___what can it be used for today___
- ___what more is needed right away___

**Comment by Thanood** [comment]
Monterey can be used to:

1. Quickly scaffold an Aurelia app based on aurelia-cli or any skeleton (without downloading the whole zip, copying it to its destination and install npm/jspm).
2. Look up which version of a library is actually installed - not so easy in a JSPM project.
3. Easily update dependencies.
4. Fire up a `watch` process without opening a terminal.
5. Fire up a terminal if needed.
6. Start any editor/IDE you want with the working directory already set to the project path.
7. Get a quick status overview of your project (npm/jspm/webpack versions).
8. Fire up a pre-configured gist.run!
9. Look up the output of previous operations (tasks) to track down potential errors.

What more is needed:
* Support "sub-projects" like our bridges. I have to create two projects for the bridge and its sample.

**Comment by JeroenVinke** [comment]
> what can it be used for today

Before monterey when I wanted to start developing I needed to:

1. start visual studio
2. run start in visual studio
3. browse to my project folder
4. open cmd.exe in the project folder
5. run `gulp watch`
6. open vscode (often needing to select the project directory)
7. open a different cmd.exe so I can run jspm install type of commands

Now I can add all my projects in Monterey and do all the above by simply clicking a few tiles/buttons. 

> What more is needed:

What @Thanood said about sub-projects. I'd like grouping etc. For example, I have a visual studio project and an aurelia project, would be nice if we could group these together under a single name.

We also need to improve (extend) the JSPM and NPM package manager screens, and we need to add GUI's for a whole lot more of existing tools

**Comment by JeroenVinke** [comment]
> Look up which version of a library is actually installed - not so easy in a JSPM project.

The core issue here is not knowing that your dependencies are out of date. I bet that many (if not all) projects have outdated dependencies, but you don't know about this because no tool (other than monterey) is telling you

**Comment by adriatic** [comment]
Great set of features - I want us to use them all in the subsequent "marketing discussions" as well as moving ahead planning discussions.

Let me also add a few of my "what to do next" ideas:

In order to establish a reasonable shared vocabulary, I would prefer not to use the term Aurelia-CLI as the area where to expand Monterey, since CLI (command line interface) is misnomer in the Monterey context. The main properties of Monterey (in the Aurelia CLI context) are:

1. It uses an **interactive dialogue with the user** (let's call this ___Monterey Wizard___) to allow variations in the finally generated skeleton, that the apps from Aurelia Navigation Skeleton repository do not allow.

2. It uses **RequireJS module loader** to build the app from pieces.

### Now, I can write about next few tasks for Monterey

Make sure  that all of our bridges are supported by Monterey. To make this more clear, I would say it this way: ___Monterey should directly support application "growth from the initial skeleton" using RequireJS module loader___ (as stated in 2 above).

**Comment by AlainBaslter** [comment]
I second what @Thanood is saying...

What more is needed:
Support "sub-projects" like our bridges. I have to create two projects for the bridge and its sample.

I am not quite sure how this would manifest itself but this is how I would like to use it..

Say I pick what bridge flavor I'd like to integrate in my project: Kendo, Syncfusion etc...

Then get a list of the controls available and I pick only those I intend to use and it generates the related useXXX() configurations (maybe in a separate file) that is used in main.js to configure the associated plugin. 

The end game is my "bundled" app uses no more and no less than what I consume.
I can start with a small subset of the controls and add them as needed.
If I attempt to use them and did not configure them I get a reminder to add them in.
It seems like a lot of hand holding but the goal it to keep it lean.

**Comment by JeroenVinke** [comment]
@adriatic please read https://github.com/monterey-framework/monterey/issues/277#issuecomment-244932492 and comment

**Comment by Thanood** [comment]
Example workflow (this actually happened):
* start Monterey
* create an esnext skeleton app
* open up a cmd, `jspm aurelia-materialize-bridge`, close the cmd
* create an atom app launcher
* click the launcher to open atom
* open the task manager
* start `gulp watch` task
* start `gulp bundle` task (several times)
* notice that you never opened a console :smile:

**Comment by JeroenVinke** [comment]
Closing this as we've enumerated all features :)
