### ISSUE TITLE
Automated help

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#282]
Will add more info, but I would be in favor of what @vegarringdal proposed a while ago: https://github.com/monterey-framework/monterey/issues/1#issuecomment-228470760

**Comment by Thanood** [comment]
I had a similar thought, maybe something like [intro.js](http://introjs.com/)..

**Comment by JeroenVinke** [comment]
That library is pretty nice

**Comment by adriatic** [comment]
I am under the impression that  **[intro.js](http://introjs.com/)** is meant do be used as an animated version of the classical [user manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/)** - not as an "live overlay" on the application. Did not get the chance to use it, so I am not sure how to embed it in Monterey.

**Comment by JeroenVinke** [comment]
The only thing intro.js does is that it highlights parts of the applications and uses balloons to say "look, with this part of monterey you can do X"

**Comment by JeroenVinke** [comment]
I do not think that it replaces the user manual, but it helps the gets people started that do not want to go through the user manual

**Comment by Thanood** [comment]
Basically it's like the overlay info @vegarringdal posted in https://github.com/monterey-framework/monterey/issues/1#issuecomment-228470760 but it's seperated into chunks, animated and interactive.

Of course that doesn't replace a user manual. But it adresses the feeling of "getting lost" when seeing all available tiles.

**Comment by adriatic** [comment]
I believe that @JeroenVinke considers this as the solution

![image](https://cloud.githubusercontent.com/assets/2712405/18411179/9dde8e1e-7740-11e6-813b-30dea446102d.png)

Questions: 

- what user action triggers live help and how is it ensured that the live help does not get in the way of the normal workflow (using the app)
- what happens if I click on the `next` button? explanation for the first tile in the collection of tiles or explanation for the next category of Monterey controls?

Note: I know that the answers to these questions would come as the consequence of the Live help design **we have yet to do** - so this article is written to get design going.

**Comment by JeroenVinke** [comment]
> what user action triggers live help and how is it ensured that the live help does not get in the way of the normal workflow (using the app)

You would only get the live help when you have opened Monterey for the very first time. So basically after adding an existing project or creating a new project at this screen:

![image](https://cloud.githubusercontent.com/assets/2189477/18411338/b91b3fee-7775-11e6-948c-297645b5fc91.png)

> what happens if I click on the next button? explanation for the first tile in the collection of tiles or explanation for the next category of Monterey controls?

Live help higlights different parts of the application and explains what each part does. By clicking "next" you confirm that you have read the balloon and the next part of the application will be highlighted. This continues until the user either clicks "skip" (stop live help entirely) or until all parts have been gone through

**Comment by JeroenVinke** [comment]
For the best impression, go to [this link](http://introjs.com/) and click the blue "Demo" button

**Comment by adriatic** [comment]
**Of course** that I saw the demo :-) before writing anything about using this tool.

I do not believe that having access to the live help only first time through is sufficient.

I also do not believe that having just sequential access to the explanations provided by this tool is sufficient (I would not use it - and yes, this is just one person's opinion).

Let me find a better solution for live help.

**Comment by adriatic** [comment]
We may not need a better solution - having Rob add the opinion of favor to intro.js, it would be meaningless to try to do more than this plugin will do for us

**Comment by Thanood** [comment]
> I also do not believe that having just sequential access to the explanations provided by this tool is sufficient 

In addition to opening this help for the first time, we could add a small "info" button on the UI parts/dialogs which restarts live help in the given context.

**Comment by Thanood** [comment]
Having read #233 now, I think tooltips are a great addition, too.
For example hovering over the NPM tile it tells you what it can do exactly.

**Comment by JeroenVinke** [comment]
@Thanood would the [title](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/title) be enough? or do you think that we need a more customizable tooltip

**Comment by Thanood** [comment]
Let's try it and see what it looks like.
I don't like the delay of the native title tooltip but that may be my personal taste.

**Comment by adriatic** [comment]
It seems that we are oscillating about the solution for this issue. I accepted `intro.js` based on the enthusiasm Rob expressed seeing it, but I still feel that the help system where you need to step sequentially through all elements to reach the one you want to learn more about, is not the right solution. Then I saw Daniel join my case and Jeroen accepting it - however, limiting the set of UI objects that would be covered by such help to tiles only.

I am suggesting to include all GUI objects that would benefit from this feature - this includes all elements of the toolbar, application templates, buttons and fields of all wizard steps, buttons on npm and jspm manager - basically everything that our common sense would advise us.

I would also like to augment the standard tooltip content to include the reference **into** online help books, meaning that all points where tooltip wants to jump into the book need to have anchors.

**Comment by JeroenVinke** [comment]
> where you need to step sequentially through all elements to reach the one you want to learn more about

I believe there are two different use cases at play here. When starting Monterey for the first time you may get overwhelmed with the amount of things you see on your screen. Intro.js gives you a **basic** introduction to the different parts (left menu, right side of the screen, toolbar), but it should not tell you about **all** the things you see on the screen

It is not used to get information about a specific thing, for that we need something else (like a tooltip)

**Comment by JeroenVinke** [comment]
> I would also like to augment the standard tooltip content to include the reference into online help books, meaning that all points where tooltip wants to jump into the book need to have anchors.

I like that

**Comment by adriatic** [comment]
... and I like

> When starting Monterey for the first time you may get overwhelmed with the amount of things you see on your screen. Intro.js gives you a basic introduction to the different parts (left menu, right side of the screen, toolbar), but it should not tell you about all the things you see on the screen

So, we do both !

**Comment by JeroenVinke** [comment]
Just pushed the initial intro.js to master. If you use the "start from scratch" option, then you will get the experience of someone opening Monterey for the very first time:

![image](https://cloud.githubusercontent.com/assets/2189477/18417885/a01fd99c-783c-11e6-8de9-ead9af50bc34.png)

**Comment by adriatic** [comment]
I checked this feature - it looks **really nice and useful** to the point that I would really like to disassociate it from the "start from scratch" option and add a global toggle to handle its state

**Comment by adriatic** [comment]
The message "do this as a last resort" would scare everyone who would like to get a refresher and wants to turn it on at any point in subsequent use of Monterey.

**Comment by JeroenVinke** [comment]
> I checked this feature - it looks really nice and useful to the point that I would really like to disassociate it from the "start from scratch" option and add a global toggle to handle its state

Do you mean for us as developers or for users as well?

We can start the tour again from the Developer toolbar item too:

![image](https://cloud.githubusercontent.com/assets/2189477/18419436/fddbbad8-785a-11e6-8d4c-c4d78c91ea0d.png)

**Comment by JeroenVinke** [comment]
> The message "do this as a last resort" would scare everyone who would like to get a refresher and wants to turn it on at any point in subsequent use of Monterey.

It should be scary :) Maybe we can add this option to the Preferences screen, although hopefully the user will never need/want to use it

**Comment by adriatic** [comment]
My **[original comment](https://github.com/monterey-framework/monterey/issues/282#issuecomment-246185932)** means to indicate how **users** should be able to re-enable (pun intended) the `intro.js` functionality **without** having to resort to scary actions :smile:

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18608753/48cd899a-7cf2-11e6-9da5-4ee92fddc3ef.png)

**Comment by adriatic** [comment]
It's fun to read this whole thread from the beginning - and then the final solution which is sooo cool and logical 😄
