### ISSUE TITLE
Split up the CSS in a stylesheet for colors and one for structure

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#283]
When talking about Material Design and that it may look aweful on a Mac (for example) we thought it might help to support theming.

To help implement this, split up the CSS in a stylesheet for colors and one for structure (padding, margins etc).

@JeroenVinke:

> That way we can replace the stylesheet that has colors with a materialize one, while keeping the structural css the same)
> I don't mean "replace" but we can have multiple stylesheets with different theming

We could even use the "accent/primary" color principle (for all themes - maybe more colors).. This way it's easy to keep the UI streamlined..

...

A `colors.less` file or something similar should be enough.

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18380242/b651baea-7676-11e6-8e1c-29d886c2132b.png)

**Comment by JeroenVinke** [comment]
I chose not to use the colors.less approach, because themes should be able to specify more than just the base color. The materialize theme would be able to use the accent/primary approach though

**Comment by Thanood** [comment]
> themes should be able to specify more than just the base color

You're right.

I had something different in mind, though. I'll try to be more specific. :smile: 
* define a bunch of colors which are used in the application (try to limit them to a few)
* put them in `colors.less` (in **addition** to other theme files)

Then we have a classical palette definition and a reference for future themes.

**Comment by JeroenVinke** [comment]
Correct me if i'm wrong, but in the less files of the themes we would work with variables out of the colors.less file of the theme?

**Comment by Thanood** [comment]
Now it makes less sense to me. :smile: 
It's just a shortcut or a reference to which colors are used. Also it's a help to streamline color usage.

Nothing more, actually. Of course themes can still use their own colors.

Let's say I'm writing a simple theme which does nothing more than change the colors (because pink looks alien on my device or I simply don't like pink).
I copy/import Monterey's `colors.less` and change the colors.

In another example I'd like to keep the colors but add some more things. I can use the colors defined in Monterrey's `colors.less`  file there and be happy.

This is just to explain what I thought. Everytime I read this, it somehow becomes less "important" but I like the approach of having a color guide for ourselves.

**Comment by JeroenVinke** [comment]
OK, we are on the same page now :)

I'm working on the theme switcher now so I'll make sure that this is possible as well
