### ISSUE TITLE
Starting multiple tasks at once (workflow)

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#284]
After scaffolding the aspnet-core-typescript skeleton you are given the opportunity to start both `gulp watch` and `dotnet run`. Running both these commands is necessary to start the application. When you want to restart the application, then you need to run `gulp watch` and `dotnet run` manually.

Using the name "workflows" we have discussed something similar (https://github.com/monterey-framework/monterey/issues/211). I see a workflow as a combination of multiple commands, runnable via a single button (a tile perhaps). A workflow could be to start `gulp watch` and `dotnet run` and the name of the workflow would be "Run application". The "Run application" workflow would be simple for skeleton-esnext samples, it would just run `gulp watch`.

Someone could also create a "release" workflow, that could run `gulp build`, `gulp prepare-release`, `gulp deploy`. Starting the workflow "release" would add the three gulp commands to the task manager, allowing the user to follow the progress of the workflow.

**Comment by Thanood** [comment]
> runnable via a single button (a tile perhaps)

Excellent idea.
Would it be possible to have (configurable) task references as tiles in general? So I can add a `gulp build-release` task and just click it.. This could become the feature you proposed by being able to combine tasks into a tile.

**Comment by JeroenVinke** [comment]
> Would it be possible to have (configurable) task references as tiles in general? So I can add a gulp build-release task and just click it.. This could become the feature you proposed by being able to combine tasks into a tile.

I like it

**Comment by JeroenVinke** [comment]
> Example workflow (this actually happened):
- start Monterey
- create an esnext skeleton app
- open up a cmd, jspm aurelia-materialize-bridge, close the cmd
- create an atom app launcher
- click the launcher to open atom
- open the task manager
- start gulp watch task
- start gulp bundle task (several times)
- notice that you never opened a console (for longer than a minute) :smile:

**Comment by JeroenVinke** [comment]
Initial implementation is in master
