### ISSUE TITLE
Fix styling issues

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#285]
![image](https://cloud.githubusercontent.com/assets/2189477/18348513/06fa3b76-75cc-11e6-9a62-14dcf962c41d.png)

@Thanood and I have found a few issues so far:

- There should be more margin left to the project template list
- "Create new application" should be aligned to the left
- "Project template" text should be smaller, renamed to "Templates" or removed completely

**Comment by adriatic** [comment]
While all above remarks will make the app nicer, I would propose a more systematic approach (will do this tomorrow), where I want enumerate all UI elements and subject them to a critical discussion:

Example: the arrow symbol indicating the selected grid element:

![image](https://cloud.githubusercontent.com/assets/2712405/18370203/5c75a630-75f9-11e6-91d2-71042d20b098.png)

- Is this additional selector (additional to the grid cell color) really needed?
- If we want to keep it, it ought to look a lot better (this is likely something from the font-awesome collection, which would not be used in Excel UX for example :-)

I do not want to continue this as it should be sufficient to indicate my intention **Monterey should not look cheap**

**Comment by adriatic** [comment]
Example of a good improvement is to use Daniel's proposed projects grid "header" 

![image](https://cloud.githubusercontent.com/assets/2712405/18417710/8d59c8b8-7805-11e6-8ed7-7ca856887350.png)

Note that the added tooltip based live help allows to use this header in the form it is now - no text needed

**Comment by JeroenVinke** [comment]
I'll just write down things I noticed in this issue. The background-color of the splashscreen is different than the background color of the main screen. So after about two seconds of loading the background color changes to a different gray color

![image](https://cloud.githubusercontent.com/assets/2189477/18426107/4352f93c-78bf-11e6-8be2-ab579a3fcb6a.png)

![image](https://cloud.githubusercontent.com/assets/2189477/18426108/460ac39e-78bf-11e6-9f2f-b7645564c8fc.png)

**Comment by Thanood** [comment]
@JeroenVinke This will depend on the theme used. I mean we can add a default `#f7f7f7` to the background in index.html but if some theme turns the background color to red it's the same problem again. :smiley: 

Maybe we could blend the background color with a slight transition. What do you think?

**Comment by JeroenVinke** [comment]
Ah yes, that could become an issue. Also, it takes time to load the theme, as it loads in main.js. So if the theme sets the background color of the splash screen then there is a flash of unstyled content. I guess we could say that the splashscreen should be the same for all themes? 

In that case a transition from the splash screen to the main screen would be best

**Comment by JeroenVinke** [comment]
@Thanood love the tiles, but i'm not sure if I like the padding on the project list:

![image](https://cloud.githubusercontent.com/assets/2189477/18596074/cc69e3ee-7c47-11e6-9cf6-22923ff4e8ad.png)

without the arrows:

![image](https://cloud.githubusercontent.com/assets/2189477/18596096/debe8f04-7c47-11e6-9d6c-5cfa3efdcbe0.png)

@adriatic what do you think?

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18596317/d9ad86ea-7c48-11e6-8dee-0bb131cf5c74.png)

I like that the project list items use the hand cursor now, it's the little things :smile:

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18596747/11813cae-7c4b-11e6-83c7-535e06569583.png)

**Comment by Thanood** [comment]
Very good feedback, thanks! 👍

**Comment by JeroenVinke** [comment]
Gulp watch :) the developer toolbar item can spawn tasks but they do not last forever

**Comment by Thanood** [comment]
Of course! 😄 
Thanks.
