### ISSUE TITLE
Create npm package manager screen

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#29]

**Comment by adriatic** [comment]
**Hint** - unless this task is planned for @JeroenVinke, it would be nice to define it with more than 0 words :-)

**Comment by JeroenVinke** [comment]
This issue is just a placeholder. I was guessing we could wait for the jspm package manager screen to be finished so we can reuse parts of it here

**Comment by adriatic** [comment]
I understand.
