### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#298]
### Intention

**I'm submitting a feature request**  

Discussion started in https://github.com/monterey-framework/monterey/issues/282#issuecomment-246172976

### Description
**Current behavior:**  
Tiles do not have tooltips, so you need to open all tiles to see what it does. For example, you would need to click on the Gistrun tile to figure out that it opens gistrun in a new browser window.

**Expected/desired behavior:**  
Tiles should have tooltips. In the case of the Gistrun tile, a tooltip would be able to explain that a click on the tile would open gistrun in a new browser window:

![image](https://cloud.githubusercontent.com/assets/2189477/18416712/fb4d7958-781b-11e6-8d0b-c79a881fcc58.png)

Instead of "Free web tutorials" it would say "Clicking this tile results into GistRun being opened in a new browser window"

**What is the motivation / use case for changing the behavior?**  
If we add tooltips to the tiles then the user wouldn't have to click on all tiles to see what they do

**Comment by JeroenVinke** [comment]
> I would also like to augment the standard tooltip content to include the reference into online help books, meaning that all points where tooltip wants to jump into the book need to have anchors.

Something to keep in mind is that we should have a uniform way of showing tooltips (e.g a single component that is called by all different parts of Monterey). Plugins should be able to add the tooltips, so that Monterey itself does not have deep knowledge of its features

**Comment by JeroenVinke** [comment]
@adriatic if you pull (and jspm install from the app directory) you should be able to see the tooltip workin for the NPM tile and the Task manager toolbar item.

I have made a `tooltip` custom attribute that you can put on anything. An example:

```
<div tooltip="tooltip-npm"></div>
```

Where `tooltip-npm` is a reference to a definition in the i18n translation file: https://github.com/monterey-framework/monterey/blob/master/app/locales/en/translation.json#L71-L72. Note that you can use markdown

**Tiles**
All tiles use the `default-tile.html` view, which has the `tooltip` custom attribute: https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/default-tile.html#L5. Even though all tiles use the same view, the view-model is different for each tile. The `tooltip` custom attribute (shown in `default-tile.html`) is bound to the `tooltip` property. The [npm tile](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/npm/tile.ts#L12) has defined this property and therefore has a tooltip. `tooltip-npm` is again a reference to the i18n translation file I showed in the previous paragraph. 

**Taskbar**
The taskbar is dynamically composed from `task-bar.html` and `task-bar.ts` files from all plugin folders (when the plugin has a taskbar item). For the taskmanager it is [task-bar.html](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/task-manager/task-bar.html) and [task-bar.ts](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/task-manager/task-bar.ts). Note that in [task-bar.html](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/task-manager/task-bar.html) there is a `tooltip="tooltip-taskmanager"` custom attribute

Let me know how far you get

**Comment by adriatic** [comment]
On the first glance (pretty short one, as I want to first finish Monterey user manual) this seems pretty clear. Will let you know if I need more information soon.

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18443706/6daa2b36-7916-11e6-96d2-f09ae6dc1163.png)

![image](https://cloud.githubusercontent.com/assets/2189477/18443716/7536dd4a-7916-11e6-88c2-098598f99098.png)

**Comment by adriatic** [comment]
I propose to make the tooltips easier to "spot" - probably by changing their background

**Comment by Thanood** [comment]
Personally I like something like the dark style in the second paragraph on this site:
http://qtip2.com/demos

Third from the left in the first row.
Dark because it contrasts the bright style we currently have.

**Comment by adriatic** [comment]
Hpw about this

![image](https://cloud.githubusercontent.com/assets/2712405/18455421/d668bd80-7917-11e6-9e7a-f1240952a97b.png)

I would **much prefer** a long timeout, where everyone can close the tooltip

**Comment by adriatic** [comment]
@JeroenVinke says
> Let me know how far you get.
 I only started this at 9:30 PM (local time - EST) so I could not have done much yet. There should be no problem to do this task in a couple of hours at most, though, so I plan to do it first thing tomorrow morning.

A question on `default-tile.html`  view which is view only (no default-tile.ts view model):

The `tooltip="${tooltip}"` assignment is meaningful because  each plugin's `tile.ts` view model has the decorator `@useView('plugins/default-tile.html')`, right?

**The real question is**: "how did you became aware if this "trick" (multiple view models using the same view)?

**Comment by adriatic** [comment]
### More on tooltips styling

We want to control the tooltip location (relative to the location of the  plugin being described), as well as style (see Daniel's [comment](https://github.com/monterey-framework/monterey/issues/298#issuecomment-246435856) above.

**Comment by JeroenVinke** [comment]
> The tooltip="${tooltip}" assignment is meaningful because each plugin's tile.ts view model has the decorator @useView('plugins/default-tile.html'), right?

Yes. The default-view binds to the tooltip property of the view-model, and the view-model is determined (and hooked up) at runtime.

> The real question is: "how did you became aware if this "trick" (multiple view models using the same view)?

I read it in a blogpost once

> We want to control the tooltip location (relative to the location of the plugin being described)

I don't follow

**Comment by JeroenVinke** [comment]
> I would much prefer a long timeout, where everyone can close the tooltip.

I wouldn't. I can imagine people hovering over all interesting Monterey features, so if you would need to close each tooltip manually then that would get really annoying.

**Comment by adriatic** [comment]
**Two responses:**

>We want to control the tooltip location (relative to the location of the plugin being described)

At the moment, I have the impression that the tooltip shows up at almost random locations instead of following a specific rule that we set, like "show up" at the northwest corner (plus some margin) of the object the cursor is hovering above.

>I would much prefer a long timeout, where everyone can close the tooltip.

This comment was made under the impression that the tooltip disappears on timer, where the time is shorter than it takes me to visually process the context of the tooltip.

Now, I realized that the tooltip disappears on "cursor-out" event and I am very happy

**Comment by JeroenVinke** [comment]
> @Thanood should still apply his styling magic to these tooltips

Yes please!! :smile:

**Comment by adriatic** [comment]
@Thanood - please wait until I check in the `tooltips` branch - in a few hours after I run some errands.

**Comment by Thanood** [comment]
Sure.. I'm currently checking out a runaway tile.. :smiley:

**Comment by adriatic** [comment]
@JeroenVinke there seem to be some irregularity in the tiles collection - as some of them (cmd, chrome and files explorer) are defined outside of the [plugins folder](https://github.com/monterey-framework/monterey/tree/master/app/src/plugins) so I get some silly tooltips like:

![image](https://cloud.githubusercontent.com/assets/2712405/18485680/d652f9c4-79bb-11e6-9049-1e1b99fa49f9.png)

You might decide to do some refactoring or if that is not required, please show me where to fix this

**Comment by JeroenVinke** [comment]
This will require some additional work, as app launcher such as "cmd" and "file explorer" are not statically defined

**Comment by JeroenVinke** [comment]
I believe you are editing [tile.ts](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/tile.ts) and not [editor-tile.ts](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/editor-tile.ts) which is the tile for the "App launcher" tile

**Comment by adriatic** [comment]
> I believe you are editing tile.ts (the view-model for every app launcher such as "cmd" and "file explorer"

I edited only the file `tile.ts` for **each tile** in the [plugins folder](https://github.com/monterey-framework/monterey/tree/master/app/src/plugins) - like [this](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/tile.ts) file for the app-launcher tile.

> app launcher such as "cmd" and "file explorer" are not statically defined

Why?

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18487347/1e725216-79f5-11e6-8861-4fb6557e9441.png)

> app launcher such as "cmd" and "file explorer" are not statically defined
> Why?

Because you can create your own app launchers. While we provide some default app launchers that are commonly used (file explorer, cmd), you could decide to create an app launcher for a program that only you use

**Comment by adriatic** [comment]
I am more confused now due to terminology being used: the term I used in these last two exchanges is "tile" - which you seem to refer to as "app launcher". This would fine, we could be both referring to the same object if there was not a tile that is called App launcher. 

To avoid this confusion, lets use my name (tile) for each square object on the main view. Then, please explain to me why is it that `cmd`, `File Explorer` and `Chrome` could not all be constructed the same way as say `NPM`, all of them living in the same folder and all of them being subjected to the same process of adding support for tooltips

**Comment by adriatic** [comment]
Attempt #2 on
> I believe you are editing [tile.ts](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/tile.ts) (the view-model for every app launcher such as "cmd" and "file explorer") and not [editor-tile.ts](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/editor-tile.ts) which is the tile for the "App launcher editor" tile

I re-read your comment with a bit more CPU involvement - and you are right, explaining me what I did wrong. Thanks.

**Comment by JeroenVinke** [comment]
> I am more confused now due to terminology being used: the term I used in these last two exchanges is "tile" - which you seem to refer to as "app launcher". This would fine, we could be both referring to the same object if there was not a tile that is called App launcher.
To avoid this confusion, lets use my name (tile) for each square object on the main view. Then, please explain to me why is it that cmd, File Explorer and Chrome could not all be constructed the same way as say NPM, all of them living in the same folder and all of them being subjected to the same process of adding support for tooltips

Yes, they are all tiles. But some of them are so called "app launchers". The "file explorer" tile is an "app launcher". An app launcher is a tile that executes a command when clicked. NPM is a tile but not an app launcher since it opens a screen and not a command.

**Comment by adriatic** [comment]
Perhaps using the names of  "internal" and "external" app launchers could improve this classification - as this is really the only real difference.

**Comment by JeroenVinke** [comment]
> There should be no difference between them from the view of my task (adding tooltips)

There is a difference. The NPM tile is added via code at compile time, the app launchers are added dynamically at run time. This means that the tooltip texts for app launchers need to be kept at runtime as well, while tooltip texts for other tiles (such as the NPM tile) can be added declaratively

**Comment by JeroenVinke** [comment]
So it is a bit more involved to add tooltips for app launchers, but i'm fairly certain we can do this in a nice way

**Comment by adriatic** [comment]
I am on a slow uptake today obviously, so please give me some time to think, after I finish all tooltips for the "built in" action tiles

**Comment by adriatic** [comment]
Several points:

1. Added the [initial code](https://github.com/monterey-framework/monterey/commit/24dc45658fa518226ff1178e0fcf5b355b24ac0a) for tooltips (in the [tooltips](https://github.com/monterey-framework/monterey/tree/tooltips) branch). This task is not yet complete as I have not yet covered the toolbar items - that comes next.

2. The above discussion aabout tiles / app launchers / internal "apps" / external apps needs of course be resolved, some way. I think that I understand the remaining problem (provide the support to add tooltip help information to the existing code that allows users to add their own app launchers).

**Comment by adriatic** [comment]
Last comment for today: checked in everything ([toolbar item's tooltips](https://github.com/monterey-framework/monterey/commit/bc8647941e6c0e13f1cd2259a621794d274127da)).

There is an issue that I left for @JeroenVinke to fix - the toolbar item's tooltip is limited to just the name, as shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/18493708/e9bb2da0-79df-11e6-8efd-5c58ba97b27a.png)

The Taskmanager toolbar item however, shows the "complete" tooltip:

![image](https://cloud.githubusercontent.com/assets/2712405/18493795/5b041c74-79e0-11e6-89e7-996da2dd2ce7.png)

This ought to be the consequence of not all toolbar items having the file `tile.ts` which would have the decoration `@useView('plugins/default-tile.html')`.

As I do not want to step on some landmine (however unlikely that might be, as the code is really well structured, written with a ton of patience and pleasure to "hack"), I am leaving this for @JeroenVinke to finish -- and invite @Thanood to do the styling.

**Comment by JeroenVinke** [comment]
@adriatic seeing the translation key (tooltip-terminal) indicates that i18n did not find the translation key in the json file, and thus could not translate it

**Comment by adriatic** [comment]
> This ought to be the consequence of not all toolbar items having the file tile.ts which would have the decoration @useView('plugins/default-tile.html').

Did you miss my sentence quoted above? Does it not explain why we do not see the complete data in toolbar item's tooltip?

**Comment by JeroenVinke** [comment]
> Does it not explain why we do not see the complete data in toolbar item's tooltip?

Oh right, toolbar items work a bit differently than tiles, they don't use `@useView` like tiles, which I think is possible (and if so, I'll refactor it)

But this does not explain why you don't see the complete data. Aurelia-i18n tries to lookup `tooltip-terminal` in [this file](https://github.com/monterey-framework/monterey/blob/bc8647941e6c0e13f1cd2259a621794d274127da/app/locales/en/translation.json#L78-L79) but it does not find it, and therefore it just shows the translation key (`tooltip-terminal`). Did you add the `tooltip-terminal` entry to [translation.json](https://github.com/monterey-framework/monterey/blob/bc8647941e6c0e13f1cd2259a621794d274127da/app/locales/en/translation.json)?

**Comment by adriatic** [comment]
> Did you add the tooltip-terminal entry to translation.json?

Yes - (of course I did, which is the reason I believe you need to do the refactoring to use the @useView)

**Comment by adriatic** [comment]
Note that I checked in all my planned changes, so you can merge the tool tips branch and do that refactoring. I also did ALL needed changes in the User manual.

**Comment by Thanood** [comment]
I'll merge this into my master when you're ready. Then I'll try cherrypicking these commits into the styling branch - with my limited git skills.. :smile:

**Comment by JeroenVinke** [comment]
The last commit to the tooltip branch was 17 hours ago (from githubs point of view). Is this correct?

**Comment by adriatic** [comment]
Yes, this is correct [these are the tooltip "messages"](https://github.com/monterey-framework/monterey/blob/tooltips/app/locales/en/translation.json#L70-L80) - and you are correct that tooltip-preferences and tooltip-about are missing in the tooltips branch.

**Comment by adriatic** [comment]
I do not have the good explanation for that other than GitHub had a hiccup I did not notice

**Comment by adriatic** [comment]
Update:

My local copy of tooltips branch is complete and behaves as shown below:

1. All toolbar items except developer (where I did not add the "tooltip-developer"  definition act like `preferences` item

![image](https://cloud.githubusercontent.com/assets/2712405/18520189/cffcf688-7a74-11e6-89d4-ec183e10e850.png)

(Hovering above `Developer` toolbar item has no effect

The second exception is the Task manager toolbar item which acts as

![image](https://cloud.githubusercontent.com/assets/2712405/18520290/37709ad6-7a75-11e6-9869-d48b90447d13.png)

I believe that this is the behavior that all toolbar items should comply with - and the difference is that of all toolbar items only Task manager item also exists as a tile.

**Comment by adriatic** [comment]
I can update the toolptip branch from my machine - or you can pick it up from here (to add the tile.ts class to other toolbar items)

**Comment by JeroenVinke** [comment]
> I can update the toolptip branch from my machine - or you can pick it up from here (to add the tile.ts class to other toolbar items)

Yes please update the branch

**Comment by adriatic** [comment]
Also, note that at the moment the GitBook service is in a shock and behaves completely silly (you would like to use it to verify the links from tooltips to user manual

**Comment by JeroenVinke** [comment]
thanks for the headsup :+1:

**Comment by adriatic** [comment]
This last commit should result with complete set of tooltip data definition

```
  "tooltip-about":       "**About**         <br> Information about Monterey <br/>                         [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/introduction/what_is_monterey.html)",
  "tooltip-app-launcher": "**App launcher** <br> Configurable tiles manager <br/>                         [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/app_launcher.html)",
  "tooltip-aurelia-cli":  "**Aurelia-CLI**  <br> Aurelia-CLI application generator <br/>                  [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/aurelia-cli.html)",
  "tooltip-dotnet":       "**DotNet core**  <br> .NET Core manager <br/>                                  [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/dotnet.html)",
  "tooltip-gist-run":     "**GistRun**      <br> GistRun activation tile <br/>                            [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/gistrun.html)",
  "tooltip-gulp":         "**Gulp**         <br> Gulp manager <br/>                                       [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/gulp.html)",
  "tooltip-jspm":         "**JSPM**         <br> Package manager for JSPM <br/>                           [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/jspm_manager.html)",
  "tooltip-npm":          "**NPM**          <br> Package manager for NPM <br/>                            [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/npm_manager.html)",
  "tooltip-preferences":  "**Preferences**  <br> Preferences setting panel <br/>                          [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/preferences.html)",
  "tooltip-project-info": "**Project Info** <br> Brief project summary generator <br/>                    [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/project_info.html)",
  "tooltip-support":      "**Support Info** <br> Panel with support options <br/>                         [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/project_info.html)",
  "tooltip-taskmanager":  "**Taskmanager**  <br> Monitors running processes and can start new tasks <br/> [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/task_manager.html)",
  "tooltip-typings":      "**Typings**      <br> Typings manager <br/>                                    [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/typings.html)",
  "tooltip-webpack":      "**Webpack**      <br> Webpack <br/>                                            [Documentation](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/features/webpack.html)"
```

I linked About with `https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/introduction/what_is_monterey.html` - which may or may not be to your liking

I also chaned the definition of "show-irrelevant-tiles" message.

**Comment by JeroenVinke** [comment]
well this is weird..

without changing anything:

![image](https://cloud.githubusercontent.com/assets/2189477/18520938/4e47b606-7aaa-11e6-968c-6548b23d75b3.png)

**Comment by JeroenVinke** [comment]
> I also changed the definition of "show-irrelevant-tiles" message.

I like that

**Comment by adriatic** [comment]
This is the running clone of the `tooltips` branch after my last push?

**Comment by JeroenVinke** [comment]
Yes. Does a restart of Monterey help?

**Comment by adriatic** [comment]
Well - I am observing the same (now correct) behavior as well (without any restarts)

**Comment by JeroenVinke** [comment]
OK, I'd still like to refactor to using @useView as I believe it's cleaner (and in line with the tiles). Can I do this now?

**Comment by adriatic** [comment]
I believe that I did what I was tasked with - and have no idea why we had all these hiccups (GitHub push, Electron something) - sorry it took as long. Please refactor and merge so we can ask Daniel to make these beautiful :-

**Comment by JeroenVinke** [comment]
> sorry it took as long

It didn't take long

What you saw in https://github.com/monterey-framework/monterey/issues/298#issuecomment-247068891 is that the tooltip wanted to translate `tooltip-preferences` using translation.json,  but it did not find it translation.json. Translation.json is loaded at runtime, so it is kept in memory and thus will not reload until a Monterey refreshes. Monterey automatically refreshes when it detects that a file has changed (such as translation.json). 

Since translation.json was correct on disk, `gulp watch` must not have detected any changes because otherwise it would have refreshed. Strange thing is that git also did not detect changes to translation.json as otherwise it would have committed the changes. But i'm not sure what would prevent multiple applications from detecting changes to files

**Comment by JeroenVinke** [comment]
@Thanood all yours :smile:

**Comment by Thanood** [comment]
@JeroenVinke This isn't in master, right?
GitHub says "no changes" when I compare my fork.

**Comment by JeroenVinke** [comment]
No it's in the tooltips branch

**Comment by adriatic** [comment]
@JeroenVinke while refactoring the tooltip invocation for the toolbar items, please do the same for the three buttons in the "My projects header"

![image](https://cloud.githubusercontent.com/assets/2712405/18534218/d3a2cc58-7ab6-11e6-9a46-806c7f187fbf.png)

This will allow to remove their textual definitions and use only symbols that @Thanood proposed (+, - and whatever was the symbol for 1create1)

**Comment by JeroenVinke** [comment]
> whatever was the symbol for create

This is a concern of mine

https://cloud.githubusercontent.com/assets/2712405/18417710/8d59c8b8-7805-11e6-8ed7-7ca856887350.png

The pencil is often used as "edit", which is not add or create. And there is ambiguity for the plus sign: is the plus sign "add" or "create"? I would rather stick with what we have as to avoid confusion (without users resorting to tooltips for things that we should have been clear about). 

It is not like we will be able to make the project list smaller anyway, as we need room for showing project names in a meaningful way (not too small). This dictates the width of the project list, not the buttons

**Comment by Thanood** [comment]
I didn't really propose icons, the texts just didn't fit in my sidenav. I actually like the text. 😃

**Comment by adriatic** [comment]
Two good count-arguments. I stand corrected 😄

**Comment by Thanood** [comment]
> It is not like we will be able to make the project list smaller anyway

Does that splitter support a min-size? I guess that would become handy.

**Comment by JeroenVinke** [comment]
It uses [jquery-resizable](https://github.com/RickStrahl/jquery-resizable)

**Comment by JeroenVinke** [comment]
This is in master
