### ISSUE TITLE
.gitignore needs to be updated

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#300]
### Intention

**I'm submitting a bug report**  

### Environment

* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.5
* **Chrome:**
52.0.2743.82
### Description

**Current behavior:**  
**`git pull`** comand fails

```
λ  git pull                                                                      
remote: Counting objects: 276, done.                                             
remote: Compressing objects: 100% (268/268), done.                               
Receiving objects:  81% (224/276)                                                
Receiving objects: 100% (276/276), 121.85 KiB | 0 bytes/s, done.                 
Resolving deltas: 100% (97/97), completed with 1 local object.                   
From https://github.com/monterey-framework/monterey                              
   7f17a36..ed44d8d  master     -> origin/master                                 
Updating 7f17a36..ed44d8d                                                        
error: Your local changes to the following files would be overwritten by merge:  
        app/styles/layout.css                                                    
Please commit your changes or stash them before you can merge.                   
Aborting                                                                         
```

**Expected/desired behavior:**  

**`.css`** files should be ignored

**What is the motivation / use case for changing the behavior?**

**Comment by JeroenVinke** [comment]
Fixed this two days ago. We already had the css files in the gitignore, but we didn't remove them from the git repository (which I did two days ago: https://github.com/monterey-framework/monterey/commit/7f17a363c5897c6228035e27210363dff72d4ef6). It is probably why you are getting this conflict.

You should be able to fix this with `git reset app/styles/layout.css --hard`, then pull again

**Comment by adriatic** [comment]
I simply did `git stash` - which allowed me to get the "full load** including the correct .gitignore
