### ISSUE TITLE
Store only the value of settings in ApplicationState

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#302]
Right now we store the entire settings definition in the ApplicationState:

![image](https://cloud.githubusercontent.com/assets/2189477/18418913/aec6571a-784f-11e6-8d64-ae7dc316d45d.png)

We should only store the value of settings in the ApplicationState, so that we can change the definition of a setting and not have to worry about patching the setting definition that someone may have in their ApplicationState

**Comment by adriatic** [comment]
I do not understand what is happening here:

"Store only the value of settings" - value as part of the (`key`, `value`) pair?, what is then "the definition of a setting"?

This ought to be something very simple and i just do not parse the language correctly.
