### ISSUE TITLE
Help define the Monterey survey questions

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#303]
As a part of preparations for Monterey announcement, I am building the survey as a part of our new website http://blog.aureliatools.com, using the tool from http://www.opinionstage.com/.

Please help me define the set of questions (which should have **yes**, **no** and **user defined text** as answers.

Example question:
> Is the support for generating applications using Aurelia-CLI sufficient for your needs?

My preference is to ask all questions we care most about, in this "rigid" form, to avoid "ramblings" - however, I will also add the "free form" field at the end of the survey.

**Comment by adriatic** [comment]
My sense if that we can benefit most from finding more about user's need to use specific module loader, creating a series of questions will result with the report stating percentages of votes for each option, like this example:

![image](https://cloud.githubusercontent.com/assets/2712405/18420504/07e2c94a-7842-11e6-98a6-b7df8f74348b.png)

**Comment by JeroenVinke** [comment]
Well it is good to know what they are using now, but what is equally important is to find out whether or not they are considering switching to a different module loader.

**Comment by Thanood** [comment]
I've seen a lot of people (in Aurelia/discuss Gitter room) which don't seem to recognize that Aurelia-CLI uses requirejs. Maybe we could put this in brackets like "RequireJS (used by Aurelia-CLI)".

**Comment by JeroenVinke** [comment]
Good one

**Comment by adriatic** [comment]
The software package I decided to use is not supporting nested questions, so I will reformat them to accommodate your comments,

### Equally important: do you have any other questions in mind?

**Comment by Thanood** [comment]
What do you use Monterey for?
* scaffolding apps
* update dependencies
* launch gulp tasks
* all of the above

**Comment by adriatic** [comment]
Fantastic one, thanks Daniel - and keep 'em coming :-)

**Comment by adriatic** [comment]
I am trying to circumvent the problem caused by survey question fields allowing only ascii text (I would like to place there the references to user manual section that talks more about that question. Here is a screen shot of the supported behavior

![image](https://cloud.githubusercontent.com/assets/2712405/18615937/a19c4776-7d80-11e6-8694-e78f1d03183a.png)

I would prefer to be able to define the survey to show at the specific place **within** the blog entry. I posted this question to the support team - so far no bites, so I will have to spend some time to find a better solution with experimentation. The obvious alternative (a blog entry for each set of related questions makes no sense as it will grow the list of blog entries way too big.

I am very tempted to make my own survey application ...

**Comment by JeroenVinke** [comment]
did you take a look at other survey wordpress plugins that do support such a thing?

**Comment by adriatic** [comment]
My god, what a question :-)

The answer is yes, there is over 70 - and I looked at top few. Before committing to a survey, I will check more of them again.

**Comment by JeroenVinke** [comment]
@adriatic made the survey
