### ISSUE TITLE
Monterey fails to recognize watch URL

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#309]
### Intention

**I'm submitting a bug report**  

### Environment

* **Operating System:**
Windows 10

* **Node Version:**
v6.2.2

* **NPM Version:**
3.9.5 (or whatever is shipped with Monterey)

### Description
**Current behavior:**  

Wild guess: Monterey parses terminal output to provide me a URL I can click on.
It doesn't get this:
```
[20:12:11] Using gulpfile ~\Documents\Entwicklung\js\aurelia\demo-materialize\gulpfile.js
[20:12:11] Starting 'serve'...
[BS] Local URL: http://localhost:9000
[BS] Serving files from: .
[20:12:12] Finished 'serve' after 1.4 s
[20:12:12] Starting 'watch'...
[20:12:12] Finished 'watch' after 7.23 μs
```

**Expected/desired behavior:**  

Monterey task manager provides a clickable URL.

**What is the motivation / use case for changing the behavior?**  

Run a watch task and click the URL. 😄

**Comment by JeroenVinke** [comment]
> Wild guess: Monterey parses terminal output to provide me a URL I can click on.

Correct: https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/gulp/command-service.ts#L50

Seems like skeletons output "Local: http://localhost:9000" while demo-materialize outputs "Local URL: http://localhost:9000"
