### ISSUE TITLE
Gulp task runner plugin

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#31]
![img](http://i1.visualstudiogallery.msdn.s-msft.com/8e1b4368-4afb-467a-bc13-9650572db708/image/file/140744/1/console.png)

**Comment by adriatic** [comment]
This should offer two way services:
- the ability to enhance the gulp tasks that will be used to run the just assembled app
- the ability to attach this plugin to a running instance of gulp (this might be hard, but it has been done already (https://msdn.microsoft.com/en-us/library/3s68z0b3.aspx)

**Comment by Thanood** [comment]
That was mind-reading again.. half an hour ago I switched to console only to `gulp build` something and thought "that's a good feature for Monterey" :smile: 

> the ability to enhance the gulp tasks that will be used to run the just assembled app

Open `<favourite editor>` with the file in which the task was found?

**Comment by adriatic** [comment]
Not only that we managed to assemble a pretty good team (form the technical view point), we are quite close to each other in many other, more important ways, Daniel.

**Comment by JeroenVinke** [comment]
something like this perhaps? when you click the gulp button in the taskbar it opens up a small window

![image](https://cloud.githubusercontent.com/assets/2189477/17275236/f2c27a5e-5700-11e6-8aa4-be9fabcf5b0e.png)

**Comment by adriatic** [comment]
Great start - I will make more comments later, this is just to acknowledge seeing this

**Comment by adriatic** [comment]
I am a bit confused by the two highlighted buttons being on this page - does this mean that the [image 1](https://github.com/monterey-framework/monterey/issues/102#issuecomment-236702708) goes away?

![image](https://cloud.githubusercontent.com/assets/2712405/17329967/e6e8f7ba-5892-11e6-8c0b-03942c62104e.png)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/17330068/a4bf9e38-58c5-11e6-93ab-674426531a1a.png)


No, the highlighted part of the above screenshot "pops over" everything else (so you can see the status of the gulp tasks in any screen)

**Comment by adriatic** [comment]
> No, the highlighted part of the above screenshot "pops over" everything else (so you can see the status of the gulp tasks in any screen) 
Brilliant - as you just addressed my big concern about gulp - it **should** be used almost everywhere and it **should be accessible** from everywhere. 

___What gave you the right to claim that you are not a good UX designer, when everything I see tells me the opposite___?

**Comment by JeroenVinke** [comment]
:smile:

**Comment by JeroenVinke** [comment]
initial work: http://screencast.com/t/tHSZinfvuT5w

need to think about how to handle switching between projects after opening the gulp popup. if you start `gulp watch` for the typescript project, and then switch to the esnext project then what do we do with the running `gulp watch`?

we can probably cache the list of gulp tasks in session, so that only the first load is slow (of course with a refresh button to refresh the gulp tasks).

haven't pushed this to master yet btw

**Comment by JeroenVinke** [comment]
another reason why we need tiles to be per-project: imagine being able to add the `gulp watch` task as a tile, so you can start `gulp watch` with a single click, instead of the 3 clicks involved (opening the gulp window, scrolling and clicking on the `watch` task`, then clicking the start button)

**Comment by adriatic** [comment]
> need to think about how to handle switching between projects after opening the gulp popup 

I would suggest that limiting the gulp window size by constraining it to behave as [mdi](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632591%28v=vs.85%29.aspx) is not a good direction to take (Microsoft learned that long time ago). 

Chrome solved this by using tabs and that is in my mind the best alternative today. As I stated before, I really would like to see us making a few experiments with using Kendo in Monterey as it really provides rich UI - and in order for Monterey to be great it requires the rich UI (remember, one could say that the driving force behind Monterey project is to replace various CLIs with logically equivalent "screen editors / viewers"

**Comment by adriatic** [comment]
> another reason why we need tiles to be per-project: imagine being able to add the gulp watch task as a tile

Simply wonderful idea - confirming Rob's comment about tiles being user programmable scripted applets. If I ever get out of catching your development with my documentation efforts, I will certainly like to create as many "UX prototypes" as possible - and what better media than Monterey supporting GistRun as we discussed before. This is one of the ideas I mentioned about driving Monterey to the "place where no man has been before"

Remember our discussion about [LightSwitch](https://www.syncfusion.com/products/lightswitch)? Monterey can do that

**Comment by JeroenVinke** [comment]
i'm not against changing the UI, but only after we have looked at a few possibilities (like you said). that takes time, so we should continue with what we have until we have made a decision.

**Comment by JeroenVinke** [comment]
I think it's good enough for now
