### ISSUE TITLE
add task options

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#311]
### Intention

**I'm submitting a feature request**  

### Environment

* **Operating System:**
Windows 8

* **Node Version:**
v6.2.2

* **NPM Version:**
3.10.5

### Description
**Current behavior:**  

There is no way to define options for tasks. For example if I want to run `gulp prepare-release --bump minor` I cannot tell monterey to use the `bump` option.
If I started the task now, gulp would only bump the patch version.

**Expected/desired behavior:**  

For example, when clicking a task in task manager list, open a panel on the right side where I can enter options. If I then favourite that task, save my options with that task.

As an alternative, when I click "Start this task" Monterey could ask me for options in a dialog.
Or have a checkbox "with options" next to that button and when this checkbox is checked and I click "start this task", only then open the options dialog.

Also a function to rename a favourite task would be fine, so I can rename said task f.i. to `gulp prepare-release minor`.

**Comment by JeroenVinke** [comment]
Ah yes, I will keep this in mind. I'm working on the workflow editor now where you need to do something similar, so i'll create a custom element that allows you to configure options
