### ISSUE TITLE
Improve run workflow

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#315]
### Intention

**I'm submitting a feature request**  

### Environment
* **Project name**
skeleton-typescript-webpack
* **Project path:**
C:\work\tests\Monterey-testing-09122016\skeleton-typescript-webpack
* **NodeJS:**
6.5.0
* **NPM:**
3.10.7
* **Electron:**
1.4.0
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-09122016\skeleton-typescript-webpack\package.json
* **Project is using Webpack**
* **Webpack.config.js path:**
C:\work\tests\Monterey-testing-09122016\skeleton-typescript-webpack\webpack.config.js

### Description
**Current behavior:**  

The `skeleton-typescript-webpack` project was successfully built, run and stopped. This initial condition is equivalent to adding that same project that successfully built, run and stopped a day ago.

Now, I select this project (from `My project` list / v-grid view) and hit the just added `Run` button. I see this:

![image](https://cloud.githubusercontent.com/assets/2712405/18601981/287c76d8-7c34-11e6-87bd-8f94006fc25a.png)

I get the notice about the successful launch (top right corner) and the icon on the Task manager toolbar item starts spinning. This last visual cue is cuter than a little puppy, by the way :-)

**Expected/desired behavior:**  

Clearly the screenshot below shows the best possible reaction to the click on the `Run` button (Rob would literally melt seeing this, I guess 😏)

![image](https://cloud.githubusercontent.com/assets/2712405/18602093/d20a7c22-7c34-11e6-8908-5a78b43792be.png)

Now, add to this the implementation of my proposed feature [Optimized sharing desktop real estate](https://github.com/monterey-framework/monterey/issues/292), where we can define the layout for all tools participating in a given workflow. In this specific case we would set Chrome as out browser of choice and using the [Monterey Desktop manager](https://github.com/monterey-framework/monterey/issues/293) state that we wish the browser show the running app at the right side of Monterey (or on a second screen, perhaps).

___This is a view of the future release - not a pitch to do it right away___

**Comment by adriatic** [comment]
There is also the alternative `Run` workflow possible:

1. click on the Task manager icon on the Monterey toolbar results with this view - where the `npm start` item on the Task manager's list entry (highlighted in green) indicates that this task is running.

![image](https://cloud.githubusercontent.com/assets/2712405/18602389/c1ba10d8-7c36-11e6-8861-827e166feea5.png)

In my opinion, this view looks confusing for a novice - as there is plenty of possible next actions - including the `npm` start tile which should not be there given the fact that this task is actually running.

The correct choice in this situation (assuming that the user wants to see the application running) is to click on that "(highlighted in green)" list entry, which will result with:

![image](https://cloud.githubusercontent.com/assets/2712405/18602484/8600f862-7c37-11e6-829d-692700885f62.png)

where a click on the (red highlighted) live URL will start the browser

**Note:** I believe that we are all pedantic enough to realize that this whole issue is quite important to ensure as smooth workflow as possible (least possible friction for novice users.

**Comment by JeroenVinke** [comment]
There is a third way, clicking the chrome tile which opens the browser at the project URL

**Comment by JeroenVinke** [comment]
> In my opinion, this view looks confusing for a novice - as there is plenty of possible next actions - including the npm start tile which should not be there given the fact that this task is actually running.

The taskmanager does a lot of different (powerful) things:

- Start new gulp tasks
- Start new AureliaCLI tasks
- Create complex workflows
- Show progress of running tasks
- Cancel tasks

The current UI is not good enough (it is too complex) I think, and https://github.com/monterey-framework/monterey/issues/287 is where we should add our thoughts (and screendesigns)

**Comment by JeroenVinke** [comment]
I would like to close this issue as we are discussing improvements in two other issues already: https://github.com/monterey-framework/monterey/issues/318 and https://github.com/monterey-framework/monterey/issues/287

**Comment by adriatic** [comment]
Agreed
