### ISSUE TITLE
Re-running skeleton-esnext-aspnetcore via Run tile fails

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#317]
### Intention

**I'm submitting a bug report**  

### Environment

* **Project name**
skeleton-esnext-aspnetcore
* **Project path:**
C:\work\tests\Monterey-testing-09122016\skeleton-esnext-aspnetcore
* **NodeJS:**
6.5.0
* **NPM:**
3.10.7
* **Electron:**
1.4.0
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-09122016\skeleton-esnext-aspnetcore\src\skeleton\package.json
* **Project is using JSPM**
* **JSPM version:**
0.16.41
* **Config.js path:**
C:\work\tests\Monterey-testing-09122016\skeleton-esnext-aspnetcore\wwwroot\config.js
* **Project is using Gulp**
* **gulpfile.js path:**
C:\work\tests\Monterey-testing-09122016\skeleton-esnext-aspnetcore\src\skeleton\gulpfile.js
* **Project is using dotnet core**
* **project.json path:**
C:\work\tests\Monterey-testing-09122016\skeleton-esnext-aspnetcore\src\skeleton\project.json

**Current behavior:**  

Click on **`Run`** button results with the following transition of the application state

![image](https://cloud.githubusercontent.com/assets/2712405/18602607/9691cb1a-7c38-11e6-9a63-83e5b4c5b212.png)

... **and the problem is that is stays in this state forever**

Click on the Task manager icon on the Monterey toolbar shows this:

![image](https://cloud.githubusercontent.com/assets/2712405/18602698/59b257b8-7c39-11e6-993d-a16028c44279.png)

(no place to nudge the queued task - but that is really a silly comment as "nudging" is not the way to fix this 😏 )

**Comment by JeroenVinke** [comment]
nice one 👍
