### ISSUE TITLE
Github Explorer

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#32]
[Github explorer](https://github.com/aurelia-tools/github-explorer) is a standalone web / electron app that is created as a "container" for the [repo chooser](https://github.com/monterey-framework/monterey/issues/24) monterey utility.

The principal reason for developing this outside the monterey project is the freedom for experimentation with [GitHub.js](http://michael.github.io/github/) allowing the discussion on how to add relevant parts of it to [monterey-electron-pal](https://github.com/monterey-framework/monterey-pal-electron)

**Comment by adriatic** [comment]
https://github.com/fxding/greader offers a nice start

**Comment by JeroenVinke** [comment]
this issue tracks implementation of https://github.com/monterey-framework/monterey/issues/24

**Comment by JeroenVinke** [comment]
I think the workflow is good enough for now (you can simply paste in a github url, and the checks are good enough so that only valid github urls are accepted). we can start discussing this again in the future if necessary

**Comment by adriatic** [comment]
Agreed - as the next level of improvement would require caching of all Github repos :-)

**Comment by JeroenVinke** [comment]
Yes, I have more idea's but the time is not right yet
