### ISSUE TITLE
css preprocessor

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#33]
Based on [this slant article](http://www.slant.co/topics/217/~css-preprocessors-postprocessors) and my own previous experience, [`less`](http://lesscss.org/) seems like the best choice.

Although monterey would not likely use a lot of css, I think we should establish the use of a css pre-processor,

**Comment by Thanood** [comment]
And why does `less` seem to be the best choice? :smile:

**Comment by adriatic** [comment]
Fair question, Daniel - let's see if I can satisfy you with my answers:

- **Sass** has most :+1: but requires Ruby - and in my opinion that is not good. So, I eliminated Sass because of CON.
- **Stylus** also has a strong CON (Heavily reliant on whitespaces). I am allergic to that.
- **less** strong PROs trivial CONs

**Comment by Thanood** [comment]
Sass doesn't need Ruby anymore.
I'm okay with less, though. :smile:

**Comment by adriatic** [comment]
Jeroen's call - or simple voting should solve this dilemma :-)

**Comment by JeroenVinke** [comment]
I vote for less, because that means we don't have to change a thing :) and it is my preference as well
