### ISSUE TITLE
Testing Monterey on OSX

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#330]
### Intention
Verification of Monterey 0.3.2

1. How does the installer handle the presence of the previous version of Monterey. Should we care about this until the autoupdater gets solid?

**Comment by JeroenVinke** [comment]
@adriatic I just removed the "draft" status from 0.4.0, so you could try if the auto update feature works for you. https://github.com/monterey-framework/monterey/issues/324 is what I saw on mac

**Comment by adriatic** [comment]
Not really sure how could I do that in a given situation, where I really want to remove everything either monterey or docker related, to re-verify my https://github.com/monterey-framework/monterey/issues/331

**Comment by JeroenVinke** [comment]
> How does the installer handle the presence of the previous version of Monterey. Should we care about this until the autoupdater gets solid?

After opening the installer you have to drag monterey to the applications directory. At this point you are asked if you want to replace the existing monterey with the new one. That is basically everything to it. We have resolved the issues you found on mac so I think we can close this now
