### ISSUE TITLE
Monterey installer for OSX seems to be bad

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#331]
### Intention

**I'm submitting a bug report**  

As I am writing this on my Windows machine, I will supply the OSX relevant information a bit later. At the moment, just the top level problem: 

1. Downloading the OSX installer (I did it from the blog article to verify the latest addition to the blog done by @JeroenVinke an hour ago) went fine.

2. Double click on the downloaded file (used Chrome on my MAC) creates a folder that looks unknown to me. and the Monterey icon on the desktop.

3. Drag the Monterey icon that resides in that strange folder into applications folder results with the appearance of the Docker's Kitematic tool icon on Mac's toolbar (bottom of the screen)???

4. Double click on the Monterey icon on the Mac's desktop starts the app as one would expect. I started to create my first (Aurelia-CLI) app, I realized that I should better report this weird stuff than to continue verifying normal stuff.

### My conclusion

AS @JeroenVinke does not have a Mac, but rather runs it in a VM, I thinking that by adding Docker to his machine screwed up the "virtual Mac" to the point that the installer picked up parts that it should not have.

### My proposal for a fix

- @JeroenVinke writes the document for building the OSX installer
- @adriatic builds the installer on the original Mac
- @JeroenVinke picks up that installer and adds all the tricks needed to be present on his server so that autoupdater works.

**Comment by JeroenVinke** [comment]
I do not follow. Can you create screenshots?

**Comment by JeroenVinke** [comment]
> AS @JeroenVinke does not have a Mac, but rather runs it in a VM, I thinking that by adding Docker to his machine screwed up the "virtual Mac" to the point that the installer picked up parts that it should not have.

CI servers (traviscy, appveyor) are building the installers, not my machine and not my mac VM. These CI servers are started from scratch for every build, so there is no way that docker could sneak into the installer

**Comment by Thanood** [comment]
> Drag the Monterey icon [...] into applications folder results with the appearance of the Docker's Kitematic tool icon on Mac's toolbar

It's a sign.. Divine intervention? 😂

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18721936/07067960-8033-11e6-8d90-aaa33390e2a0.png)


![image](https://cloud.githubusercontent.com/assets/2189477/18721942/0c9cba1a-8033-11e6-95d8-1a60b24c85b5.png)


![image](https://cloud.githubusercontent.com/assets/2189477/18721945/12de691e-8033-11e6-8185-d96654416f3b.png)


![image](https://cloud.githubusercontent.com/assets/2189477/18721952/18169f14-8033-11e6-9eb3-c91284f059a8.png)

![image](https://cloud.githubusercontent.com/assets/2189477/18721958/1d308582-8033-11e6-8650-f7e90d591498.png)


![image](https://cloud.githubusercontent.com/assets/2189477/18721962/21acfba4-8033-11e6-8ab9-ae594b039d3f.png)

**Comment by JeroenVinke** [comment]
I have documented the release workflow [here](https://aurelia-ui-toolkits.gitbooks.io/monterey-technical-documentation/content/development_to_release.html)

**Comment by adriatic** [comment]
OK, I will go through the same identical steps and add my experience below:

**Comment by adriatic** [comment]
This is my situation when double-clicking the downloaded file. Why do I see all these other things?

![image](https://cloud.githubusercontent.com/assets/2712405/18727555/2e0bf402-8017-11e6-8dfb-b730b1c428c9.png)

Now drag the Monterey to applications folder

![image](https://cloud.githubusercontent.com/assets/2712405/18730191/00cfc890-8023-11e6-9d38-712911a2b453.png)

Quick view of the app as it sits in the applications folder (it seems really big):

![image](https://cloud.githubusercontent.com/assets/2712405/18730164/d2515e66-8022-11e6-859b-6d70662473b7.png)

**Comment by adriatic** [comment]
It seems that even without comparing each of @JeroenVinke's screenshots with mine - we are OK

**Comment by JeroenVinke** [comment]
> This is my situation when double-clicking the downloaded file. Why do I see all these other things?

http://www.macosxtips.co.uk/index_files/quickly-show-hidden-files.php

> In Mac OS X, files with names that start with a dot (.) are hidden. You may have noticed some of these before, for example when copying files from your Mac to a PC where they aren’t hidden. The most common one you might bump into is the .DS_Store file that Mac OS X puts in every folder (to save various view settings), but there are all sorts of other hidden files used by all sorts of applications.

> These files are hidden by default for good reason — the average user almost never needs to change them, so keeping them visible would just cause useless clutter. But every now and again you may find that you need to view the hidden files, for example to browse the UNIX filesystem, to work with .htaccess files or to find a file that you accidentally (or purposefully) hid by naming it with a dot.

It could be that Docker turned this setting on, so that you could mount Linux filesystems to Mac and see all files

**Comment by adriatic** [comment]
I will watch for this some more - thanks for the explanation. I do not thing that I turned the "show hidden files" mode on, myself.
