### ISSUE TITLE
Selected project on Mac too difficult to spot

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#332]
### Intention

**I'm submitting a bug report**  

### Environment

* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.5
* **Chrome:**
52.0.2743.82
* **Operating system:**
darwin

### Description
**Current behavior:**  

![image](https://cloud.githubusercontent.com/assets/2712405/18727897/e2cab97c-8018-11e6-812f-4958f9eaf6b8.png)

**Expected/desired behavior:**  

More distinguished selection

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18780291/13ed4f14-817d-11e6-84a3-6adfc918611d.png)

**Comment by adriatic** [comment]
That is the way to highlight, yes!!
