### ISSUE TITLE
spawn au ENOENT

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#333]
### Intention

**I'm submitting a bug report**  

### Environment
* **Project name**
aurelia-cli-Default-ESNext
* **Project path:**
/Users/congral/work/monterey-tests/aurelia-cli-Default-ESNext
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.5
* **Chrome:**
52.0.2743.82
* **Operating system:**
darwin
* **Project is using NPM**
* **Package.json path:**
/Users/congral/work/monterey-tests/aurelia-cli-Default-ESNext/package.json
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
/Users/congral/work/monterey-tests/aurelia-cli-Default-ESNext/aurelia_project/aurelia.json

### Description
**Current behavior:**  

![image](https://cloud.githubusercontent.com/assets/2712405/18729564/508a83a0-8020-11e6-8e82-7be5d1269aad.png)

Not being sure what to to here (how come Aurelia-CLI needs to be installed?), I let it continue and finally saw this

Reported error
```
Error: spawn au ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by JeroenVinke** [comment]
This is the error you get when aurelia cli is not installed (npm install aurelia-cli -g). Monterey shows a toastr message that warns about this as soon as the project is created and you are asked what actions to perform.

**Comment by adriatic** [comment]
Ah, we need to make a stronger point about this in the manual. You should not be watching this any more today 😏

**Comment by adriatic** [comment]
Note also that even this last step in the app creation wizard should show the `close` button - as my only chance (missing the aurelia-cli being installed) is to click on the `start` button to see the app fail.

I do not feel very strongly about this other than wanting to see Monterey always be smarter than its user

**Comment by Thanood** [comment]
Can we perhaps *start* this command if the user confirms that?
Of course the user must have a chance to confirm but I think this would fit in line with Monterey's approach.

**Comment by JeroenVinke** [comment]
not sure if this would work on mac, as I believe you need to be root in order to install something globally

**Comment by adriatic** [comment]
Making Monterey run in "sudo" mode would solve this - but I do not believe that any developer that is Monterey user would be comfortable with so powerful Monterey. So, just making sure that the user understand what happened - translating `spawn au ENOENT` into `please install aurelia-cli` would be sufficient and polite

**Comment by JeroenVinke** [comment]
I agree with not running monterey in sudo mode. Added the following clarification:

![image](https://cloud.githubusercontent.com/assets/2189477/18779124/d5230012-8177-11e6-958b-7b52d7610bda.png)

**Comment by adriatic** [comment]
Great!
