### ISSUE TITLE
gulp watch suddenly closes window on refresh

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#336]
after changing a file during `gulp watch` and monterey is supposed to refresh, at random times it decides to close the window instead

![image](https://cloud.githubusercontent.com/assets/2189477/18738084/a0e64294-8098-11e6-8388-ed8ae8d5de30.png)

**Comment by JeroenVinke** [comment]
seems that after running a command via monterey it starts with this behavior

**Comment by JeroenVinke** [comment]
changed the exit procedure so the window is reloaded after killing all running commands when in development mode

**Comment by adriatic** [comment]
This seems like a really efficient way to ensure Monterey's compliance. I wonder though, how is it that I never encountered this problem before

**Comment by JeroenVinke** [comment]
It was reproduced as follows:

- start a command via monterey (via taskmanager or via the run workflow)
- make a change in a file of Monterey so gulp watch detects a change and refreshes monterey

**Comment by adriatic** [comment]
I understand that - and I was using such setup a lot, without ever observing the terminal window being closed. It must be that it happened to me as well and I did not notice that.

**Comment by Thanood** [comment]
Not the terminal window was closed. Monterey's window was.
I've encountered that, too during style changes.

**Comment by adriatic** [comment]
> Not the terminal window was closed. Monterey's window was.

You mean that the Monterey application **exited**? Wow! as I am always running Monterey with `gulp watch`, that probably explains why I never saw this happen.
