### ISSUE TITLE
can we move state storage to localStorage?

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#34]
It's bothering me a little that each monterey session starts blank. Can we move the open projects state to localStorage or implement a "restore last session" command?

**Comment by JeroenVinke** [comment]
Yeah, the session storage isn't working right (it's using cookies right now if I remember correctly). So we need an alternative yep

**Comment by adriatic** [comment]
I was thinking along the same lines when pondering about [GitHub repo choser](https://github.com/monterey-framework/monterey/issues/24), which should have his own "history of recently visited repositories"

I am not sure what is `localStorage` - you may look at https://github.com/jviotti/electron-json-storage as one example. Alternatively check this https://github.com/fxding/greader/blob/master/app/render/db.js

**Comment by JeroenVinke** [comment]
+1 for https://github.com/jviotti/electron-json-storage

**Comment by adriatic** [comment]
In that same vein, let's use [appdirectory](https://www.npmjs.com/package/appdirectory) as well

**Comment by JeroenVinke** [comment]
we have to change [these functions](https://github.com/monterey-framework/monterey-pal-electron/blob/master/src/session.js#L12-L39) to use https://github.com/jviotti/electron-json-storage
