### ISSUE TITLE
please show me ...

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#35]
Well, I have a concrete question (see second comment) but I thought maybe we could collect questions and answers related to Monterey development here. Could become a new "developer's notes" for this project.. :smile:

**Comment by Thanood** [comment]
How does Monterey know it should use `monterey-pal-electron` when it's importing `monterey-pal`?
Never really got that.

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/blob/master/index.html#L22-L25

monterey-pal-electron calls the `initializePal()` function of `monterey-pal` and overrides all of [these](https://github.com/monterey-framework/monterey-pal/blob/master/src/fs.js#L6-L8) functions. That way when you get `FS` from `monterey-pal` it actually contains all the functions from `FS` of `monterey-pal-electron`

**Comment by Thanood** [comment]
Clever. And the one file I didn't have a look at. Thank you. :smile:

**Comment by JeroenVinke** [comment]
It probably means that aurelia-bootstrapper calls aurelia-pal-browser

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/issues/35
