### ISSUE TITLE
working on the pal

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#36]
The readme advises to use `jspm link -y` to work on the PAL. That leads to an error:

```
$ jspm link -y

err  Package registry not specified.
```

I'm guessing `jspm link github:monterey-framework/monterey-pal@0.1.4` is the correct command?

**Comment by JeroenVinke** [comment]
weird, since the registry is there: https://github.com/monterey-framework/monterey-pal/blob/master/package.json#L14

**Comment by Thanood** [comment]
Well, syntax help tells me:
```
jspm link registry:pkg@version     Link a local folder as an installable package
```

The above command worked, btw.
Now I'm having the problem that `JSPM` is somehow undefined, although it is set here:

`index.js/initializePAL()` in `monterey-pal-electron`:

```
Object.assign(jspm, _jspm)
Object.assign(jspm, _jspm.constructor.prototype);
```

Also the debugger says it's present in `aurelia-pal` as well as in `aurelia-pal-electron`.

**Comment by JeroenVinke** [comment]
can you push these changes to a branch so I can look?

**Comment by Thanood** [comment]
I forgot to export JSPM.
I'll push them anyway since I only have a few minutes left. : (

Not getting the task to work and I don't get any messages. Even the dialog doesn't show up.
I'll take another look at Vegar's approach and see if I missed anything before pushing.

**Comment by Thanood** [comment]
Please see here:
https://github.com/monterey-framework/monterey-pal/pull/1
https://github.com/monterey-framework/monterey-pal-electron/pull/1

**Comment by JeroenVinke** [comment]
updated the readme with better cmds:

```
cd ../monterey-pal
gulp build
jspm link github:monterey-framework/monterey-pal -y
cd ../monterey-pal-electron
gulp build
jspm link github:monterey-framework/monterey-pal-electron -y
cd ../monterey
jspm install monterey-pal=github:monterey-framework/monterey-pal --link -y
jspm install monterey-pal-electron=github:monterey-framework/monterey-pal-electron --link -y
```

(versions are picked up by jspm automatically)

BTW, the PAL worked fine until I clicked the button to install JSPM dependencies. It seems like `System._require('jspm')` overrides `System` so the app breaks at that point:

![image](https://cloud.githubusercontent.com/assets/2189477/16575744/d327cd8c-428a-11e6-8fde-dfbf53b4cf8f.png)

This hack works: https://github.com/monterey-framework/monterey-pal-electron/blob/master/src/jspm.js#L5-L7

![image](https://cloud.githubusercontent.com/assets/2189477/16575794/32de6cc2-428b-11e6-8f09-efaa284429e5.png)

yeey

Can't wait to see the JSPM screen with all dependencies etc :smile: :smile:

**Comment by JeroenVinke** [comment]
Also, I merged the JSPM branch to master because it did not crash when I opened a couple of projects in monterey.

**Comment by vegarringdal** [comment]
> This hack works: https://github.com/monterey-framework/monterey-pal-electron/blob/master/src/jspm.js#L5-L7

Nice one, but I allready tried running it in the main process, worked great first time, but next time internal installed variable was set, and failed  on the next project? 
Hope it works and I did something something wrong, but jspm.setPackagePath will prb compain next time you change path/project.
Thats the reason why I ended up using the threadpool with electron-remote to completely clear jspm config (require("jspm/lib/config")) like jspm will when it runs in the CLI, new context

**Comment by JeroenVinke** [comment]
@vegarringdal I thought it was already using threadpool but I was wrong. will try it with threadpool because that sounds like the better option

**Comment by vegarringdal** [comment]
** If it works on multiple projects and actually installs the files then you dont have change anything**, but I just ran into problems, tried going into require("jspm/lib/config") and clearing it and setting jspm path, but noticed it worked in install, but it didnt actually install anything.

So test it first before you change :smile:
