### ISSUE TITLE
Host all Monterey manual sources in GitHub

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#369]
### Intention

**I'm submitting a feature request**  

### Description
**Current behavior:**  
The manuals are hosted at GitBook

**Expected/desired behavior:**  
Host manuals at GitHub

**What is the motivation / use case for changing the behavior?**  
Enable Monterey contributors to submit PRs for documents

**Comment by adriatic** [comment]
### Done

1. [monterey-user-manual](https://github.com/monterey-framework/monterey-user-manual)

2. [monterey-technical-documentation](https://github.com/monterey-framework/monterey-technical-documentation)

3. [monterey-overview](https://github.com/monterey-framework/monterey-overview)

**Comment by JeroenVinke** [comment]
Nice 👍 Seems like you have gotten the hang of it 😄
