### ISSUE TITLE
404 on aurelia-cli/project-info.js

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#375]
### Intention

**I'm submitting a bug report**  

Someone (me) removed the [project-info](https://github.com/monterey-framework/monterey/blob/0f6b5af1bfe8d0f1e670476b4b2c6cf0e0088a0a/app/src/plugins/aurelia-cli/project-info.ts) screen of aurelia-cli when removing the unused tiles, causing the first error of https://github.com/monterey-framework/monterey/issues/374

**Comment by adriatic** [comment]
As we all know, this issue is unrelated to the other one in #374

**Comment by JeroenVinke** [comment]
Yes, but the first error in #374 is not the cause of the second error in #374

**Comment by JeroenVinke** [comment]
Yes
