### ISSUE TITLE
0.4.5 Draft version misbehaves in "new way"

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#377]
### Intention

**I'm submitting a bug report**  

### Environment

* **Project name**
contact-manager-materialize
* **Project path:**
C:\work\tests\Monterey-testing-10062016\contact-manager-materialize
* **NodeJS:**
6.5.0
* **NPM:**
3.10.8
* **Electron:**
1.4.3
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-10062016\contact-manager-materialize\package.json
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
C:\work\tests\Monterey-testing-10062016\contact-manager-materialize\aurelia_project\aurelia.json

### Description
**Current behavior:**  

Using the default workflow for this **[application](https://github.com/aurelia-ui-toolkits/cm-bridges/tree/master/materialize)**, the app built correctly. Click on the displayed URL results with

![image](https://cloud.githubusercontent.com/assets/2712405/19171489/114a0d88-8beb-11e6-913d-1c68a6459bac.png)

I assigned this problem to some Monterey build (CI TRavis) issue and decided not to promote the draft. My conclusion is based on the finding that even the simplest app (`skeleton-esnext`) crashes identically 😏 .

**Comment by JeroenVinke** [comment]
this is unrelated to the changes we have made. https://github.com/electron/electron/issues/7519 indicates that this is an issue in electron 1.4.3, what is used in monterey v0.4.5. We should try and lock down the version of electron to prevent this from happening again
