### ISSUE TITLE
managing user preferences

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#38]
I believe that the time has come to implement this. feature once addressing [state storage](https://github.com/monterey-framework/monterey/issues/34).

Existing solutions to look at:

1. https://github.com/nathanbuchar/electron-settings
2. https://github.com/yeoman/configstore

Give Sindre's reputation, I would vote for 2. 

My immediate use for this is the preference to launch [cmder](http://cmder.net/) instead of cmd.exe. Granted, monterey already has functional app launcher (very nice touch):

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16569355/94d1cc40-4203-11e6-8fcf-b8b85520cdb3.png"></img>
 <br><br>
</p>

where I added `cmder` already. As one could expect there will be many more app launchers and **each user** should be able to maintain his preferred subset - similarly to what I have in sublime editor

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16569422/443fdb36-4204-11e6-9d5a-10f75885674c.png"></img>
 <br><br>
</p>

**Comment by JeroenVinke** [comment]
I may have misunderstood you but the app launchers are already defined globally (not per project). But we should have a screen where the user can configure other settings.

**Comment by adriatic** [comment]
> I may have misunderstood you but the app launchers are already defined globally (not per project).

You may have missed my point, which is to allow ___seeing only a subset of app launchers___ as a user preference. For example, I would like to hide cmd.exe and see only cmder.

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16649439/461a27c2-4439-11e6-8a75-c4d43ba15894.png)

**Comment by JeroenVinke** [comment]
Opened https://github.com/monterey-framework/monterey/issues/53 to track the creation of a screen where users could set other preferences
