### ISSUE TITLE
adding cmder app to app launcher

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#39]
It makes little sense to make a PR for this and as a principle I do not want to muck with the repo directly, so please add these "parts"

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16569511/5be91d0a-4205-11e6-98f3-019b704bf7d7.png"></img>
 <br><br>
</p>

![cmder-icon windows](https://cloud.githubusercontent.com/assets/2712405/16569527/89322504-4205-11e6-9c39-91252f076f8d.png)

**Note:** I set the path to fit my situation, as cmder does not have a standard place (like in program files). To address this properly I suggest to use the same approach as you did for the `File Explorer` Cmd definition = `cmder %path%`, leaving to the user the task of adding the actual path to cmder.exe to the environment variables

**Comment by adriatic** [comment]
Since I am getting this response clicking on the `cmder` app icon 

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16570590/742de8da-4216-11e6-9766-969105d4e461.png"></img>
 <br><br>
</p>

I tried to see how the cmd behaves. Here is what I get:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16570607/e6c51ad0-4216-11e6-95d7-ec318a873a46.png"></img>
 <br><br>
</p>

```
←[1;32;40mC:\work\test\monterey-test\perica\Monterey3 {git}
←[1;30;40m{lamb} ←[0m
```

**Guess**: the launcher expects to use some "git shell` thing that seems to be an over-reach, since I am using cmder with git without any problems

**Comment by JeroenVinke** [comment]
I am not getting that issue when I open cmd, so there must be something in your environment that is causing this.

We should think about having conditionial default app launchers. For example, we could have a sourcetree app launcher that only gets shown when you have sourcetree installed.

**Comment by adriatic** [comment]
By the way, did you add cmder to the apps collection (without me creating the PR for that)?

**Comment by JeroenVinke** [comment]
> Most likely the consequence of installing some old git command line tool, so this is not a real issue if monterey just uses the %path% string from the environment. I will have a look at the code to be sure that this is true.

It does not use %path% from the environment, it replaces the %path% string with the folderpath: https://github.com/monterey-framework/monterey/blob/master/src/plugins/app-launcher/tile.js#L18

> By the way, did you add cmder to the apps collection (without me creating the PR for that)?

No, I want to use this opportunity to make app launchers smarter (take in account the OS / what's actually installed on the machine)

**Comment by adriatic** [comment]
> It does not use %path% from the environment, it replaces the %path% string with the folderpath:

That means that my either my `project.path` is bad (it is not) or `replace(/%path%/g, this.project.path)` fails. I will debug this.

**Comment by JeroenVinke** [comment]
Added cmder as part of https://github.com/monterey-framework/monterey/commit/aaac27f23e5a5d0770d11fee0b675706d0990fef: https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/defaults.json#L16-L24
