### ISSUE TITLE
Progress log

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#4]
### 25-6-2016

![image](https://cloud.githubusercontent.com/assets/2189477/16358260/e584b842-3b0e-11e6-9d69-3cfaf19f41b8.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16358263/fa127362-3b0e-11e6-8091-10652cc34bb7.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16358265/085bface-3b0f-11e6-8ad9-4ebe5ad56542.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16358266/16392810-3b0f-11e6-9e11-3f99ea7da389.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16358278/423050ba-3b0f-11e6-9995-28745453d999.png)

**Comment by adriatic** [comment]
### Hooray - we have a first moving piece

**Comment by adriatic** [comment]
The events from the **[monterey framework](https://github.com/monterey-framework)** repos are sent and discussed in the aurelia-tools owned **[monterey-electron](https://gitter.im/aurelia-tools/monterey-electron)**  instead to the **[monterey global issues](https://gitter.im/monterey-framework/global-issues)** chat room.

I propose to gradually retire the **[monterey-electron chat room](https://gitter.im/aurelia-tools/monterey-electron)** so that everything **monterey related** lives in monterey-framework organization and is linked to **https://gitter.im/monterey-framework organization**

This issue should be added to a task list and assigned to the proper dude :-)

**Comment by JeroenVinke** [comment]
### 26-6-2016
![image](https://cloud.githubusercontent.com/assets/2189477/16361351/ff244d9c-3b8d-11e6-8582-0e3d338837dc.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16361368/9960ad88-3b8e-11e6-824d-3800a92e65be.png)

Validation is triggered when the "next" button is clicked or the input field has lost focus. The wizard is entirely data driven based on [this json](https://github.com/aurelia/cli/blob/master/lib/commands/new/new-application.json)

![image](https://cloud.githubusercontent.com/assets/2189477/16361362/6837a0f4-3b8e-11e6-8229-05ea750068af.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16361365/7057a018-3b8e-11e6-8020-7971dcca55e9.png)
(this is a lie :))

This is when the custom option is chosen (allowing you to customize more settings):
![image](https://cloud.githubusercontent.com/assets/2189477/16361366/85fce108-3b8e-11e6-8fdc-c9c86e9c57bd.png)

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16361879/e1263af6-3b9e-11e6-8fec-4d60afb4ccac.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16361881/f058c034-3b9e-11e6-87c4-ff496616d316.png)

and after completing the wizard:

![image](https://cloud.githubusercontent.com/assets/2189477/16361885/fcc80b7c-3b9e-11e6-9545-e89e46d27f29.png)

**Comment by JeroenVinke** [comment]
### 28-6-2016

http://screencast.com/t/vNzV2p8yKVgk

I've taken some of the design of the aurelia docs: http://aurelia.io/hub.html#/doc/persona/developer

Projects you've created or added to monterey will be registered in an JSON object which is saved in a cookie. When monterey starts up it will detect that no projects have been added yet so it will show the launch screen with two options (add or create a project). As soon as a project is created or added you will get to the main screen of monterey. 

Plugins are registered [here](https://github.com/monterey-framework/shell/blob/master/src/plugins/index.js). The feature function of aurelia will call `plugins/app-launcher/index.js` and `plugins/npm-package-manager/index.js`.

This is what the `index.js` file of the app-launcher plugin looks like:

```
import {PluginManager} from '../../shared/plugin-manager';

export function configure(aurelia) {
  let pluginManager = aurelia.container.get(PluginManager);

  pluginManager.registerPlugin({
    name: 'App launcher',
    viewModel: 'plugins/app-launcher/app-launcher'
  });
}
```

Basically it registers itself as a plugin to the pluginmanager. That way the pluginmanager is aware of all plugins available within the system. The list of plugins maintained by the pluginmanager is used to show the plugin buttons on the main screen. Each plugin can either use the default view for plugins (just a rectangle with the name of the plugin), or have their own. For example, the app-launcher has a custom view:

![image](https://cloud.githubusercontent.com/assets/2189477/16415635/8231b600-3d3e-11e6-91fe-5431b04684a1.png)

1. Now we have to allow plugins to replace the entire right hand side of the main screen to show a specific page like [this](![image](https://cloud.githubusercontent.com/assets/2189477/16415727/f1d30c20-3d3e-11e6-9ac7-494fc5da443f.png))
2. We have to allow plugins to determine whether or not they want to be visible, based on the selected project. 
3. Each plugin should be asked what the type of the selected project is (may be the same as 2.)

then we can start implementing all the different plugins :smile:

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16430515/4ecebbd0-3d7c-11e6-9a46-280e566665d8.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16430569/89b52da6-3d7c-11e6-871d-a0374974b3cf.png)

**Comment by adriatic** [comment]
I simply love to follow your own admission that saying "I know nothing about UX" is simply not true. In no time, I will be able to just sit and enjoy what the whole team is doing (and brag about it :-)

**Comment by JeroenVinke** [comment]
29-6-2016

started with the taskbar which shows all running task registered in the taskmanager

![image](https://cloud.githubusercontent.com/assets/2189477/16465558/b24d52ca-3e3f-11e6-9132-8c277bee495d.png)

the idea is to be able to click on that and get an overview of what monterey is working on in the background

**Comment by Thanood** [comment]
I love that idea. :+1:

**Comment by adriatic** [comment]
I love it more than you do, Daniel :-)

**Comment by JeroenVinke** [comment]
### 1-7-2016

http://screencast.com/t/6gLZBnLq4ct7

http://screencast.com/t/QmtlYA3y3Ah6

**Comment by adriatic** [comment]
Not all is completely obvious - but the two videos clearly show that monterey can grab stuff from GitHub and that it has the task manager. Very cool :-)

**Comment by vegarringdal** [comment]
Very nice :-)
Keep up the good work @JeroenVinke :+1:

**Comment by JeroenVinke** [comment]
### 2-7-2016

I've added github release API to the project scaffolding wizard. Now Monterey will take the latest version of skeleton-navigation if the user chooses that option.

The following information is kept for every project that has been added to monterey:
![image](https://cloud.githubusercontent.com/assets/2189477/16541962/42e33848-4095-11e6-861c-9d9bf59236f7.png)
Each plugin can store information there so any plugin can use that information. The Package.json path was detected by the NPM plugin ([link](https://github.com/monterey-framework/shell/blob/master/src/plugins/npm/index.js#L18-L43)). We can add an equivalent jspm/webpack/whatever plugin. All this information is stored in the session (so this process only happens when a project is added to Monterey)

The remove project button works:
![image](https://cloud.githubusercontent.com/assets/2189477/16541975/d4b28f1c-4095-11e6-9090-a3fb0097732a.png)

Also added an NPM install button:
![image](https://cloud.githubusercontent.com/assets/2189477/16541961/3452165a-4095-11e6-8c5a-0383749a2f6a.png)

The NPM install feature makes us of the taskmanager:
![image](https://cloud.githubusercontent.com/assets/2189477/16541959/2546068a-4095-11e6-9ae8-28427a1b47cd.png)

Also, the abstractions folder has now been removed and instead [monterey-pal](https://github.com/monterey-framework/monterey-pal) and [monterey-pal-electron](https://github.com/monterey-framework/monterey-pal-electron) is used. This allows for easier unit testing and makes https://github.com/monterey-framework/shell/issues/9 possible

@monterey-framework/monterey-team I think i've got the basic system in place, so please try it out and provide feedback. We can now start developing more features (in addition to improving what we have).

**Comment by JeroenVinke** [comment]
Closing this as the progress can be followed with github issues
