### ISSUE TITLE
project information panel should support context menu

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#40]

**Comment by adriatic** [comment]
There are likely other places that need the same

**Comment by JeroenVinke** [comment]
How are you imagining this for the project information tile? Keep in mind that the project information screen will be improved

**Comment by adriatic** [comment]
> How are you imagining this for the project information tile?

It is normal to expect to be able to copy the information from that tile - so the context menu should support that operation. That remains true regardless of the future improvement, unless that improvement includes something like this:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16586898/21b41900-4296-11e6-92b0-f7cc8081886b.png"></img>
 <br><br>
</p>

Just to be safe: `something like this` is a reference to the `button` that copies something to the clipboard.

**Comment by JeroenVinke** [comment]
:+1: lets find a small javascript context menu library to help us

**Comment by adriatic** [comment]
Yep, let me do that, so I can crack the ice (so far, I am just circling around like a dog that wants to lay down)

**Comment by adriatic** [comment]
I will use this (https://github.com/electron/electron/blob/master/docs/api/menu.md) to implement the context menus.

I am assuming that all plugins run as renderer threads

**Comment by JeroenVinke** [comment]
@adriatic instead of using electron (because then monterey will have a dependency on electron, and we'd need to go through the PAL if we're being consistent) perhaps a browser javascript library is better.

**Comment by adriatic** [comment]
> perhaps a browser javascript library is better

Which confirms my approach that (unless I am an absolute ruler) it is a lot better to signal my intents before doing anything.

**Comment by adriatic** [comment]
Choice number 2: https://www.sitepoint.com/building-custom-right-click-context-menu-javascript/

**Comment by vegarringdal** [comment]
@adriatic 
Dunno if you can use any of this, but Ill paste in in anyway
Some parts are tied into the grid, and some parts isnt really good, so might be easier to make something from scratch :smile: 

Attribute class.
https://github.com/vegarringdal/aurelia-v-grid-TOOLKIT_FORK/blob/master/src/vGrid/v-grid-attributes-contextmenu.js

Baseclass
https://github.com/vegarringdal/aurelia-v-grid-TOOLKIT_FORK/blob/master/src/vGrid/v-grid-contextmenu.js

css:
https://github.com/aurelia-ui-toolkits/aurelia-v-grid/blob/master/src/vGrid/styles/v-grid-contextmenu.css

**Comment by JeroenVinke** [comment]
@adriatic sounds like a good option. Also consider https://github.com/aantthony/contextmenu which seems to have a nice API to work with

**Comment by adriatic** [comment]
My tendency after seeing all these alternatives is to look at  https://github.com/aantthony/contextmenu first (seems to have a nice API to work with) :-)

**Comment by JeroenVinke** [comment]
i'm not sure if we should add a context menu just for this feature, as the same can be accomplished with a button:

![image](https://cloud.githubusercontent.com/assets/2189477/16709298/c35580fe-460c-11e6-8728-82ed82f7c602.png)

(used [clipboard.js](https://clipboardjs.com/) for this). Going to track all use cases that might benefit from a context menu in this issue https://github.com/monterey-framework/monterey/issues/61
