### ISSUE TITLE
additions to "working on the pal" section of readme

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#42]
The `npm install` command is missing before each `gulp build` line:

```
cd ../monterey-pal
npm install                    <------
gulp build
jspm link github:monterey-framework/monterey-pal -y
cd ../monterey-pal-electron
npm install                    <------
gulp build
jspm link github:monterey-framework/monterey-pal-electron -y
cd ../monterey
jspm install monterey-pal=github:monterey-framework/monterey-pal --link -y
jspm install monterey-pal-electron=github:monterey-framework/monterey-pal-electron --link -y
```

Alternatively, the `build` script should be modified accordingly

**Proposal**

How about implementing this whole section as a gulp script?

**Comment by vegarringdal** [comment]
you are missing the jspm, this is needed according to the package.json devDependencies



```
cd ../monterey-pal-electron
npm install && jspm install  <<<<---
gulp build
```

**Comment by adriatic** [comment]
@vegarringdal Oh, well - of course you are right (trying to issue a correction, I created a new error) :-)

**Comment by JeroenVinke** [comment]
if someone wants to make a gulp task for this then i'm not going to say no :smile:

**Comment by adriatic** [comment]
I take this as a chalenge, man!

**Comment by JeroenVinke** [comment]
btw, the npm install and jspm install needs to be executed once, while the rest of the script needs to be executed for each change to the pal/pal-electron.

**Comment by adriatic** [comment]
> the npm install and jspm install needs to be executed once

This is very clear - if you live in a calm, ordered world. My world is still different, as I really do not trust `git` and `build` sufficiently to dare starting my day with `git pull` and live happily after that. So, I start each day by deleting all local monterey repos and make fresh clones :-)

**Comment by vegarringdal** [comment]
Made this one:
https://github.com/vegarringdal/montery-dev

Have tested it a little, no promises that it work 100% atm :smile:

**Comment by vegarringdal** [comment]
Just tested the ```node run link-run``` command
I when and added a console.log("test") to monterey-pal-electron fs/opendialog function.
ran ```node run link-run``` and links was updated :-)

 * ```node run link-run``` does this:
  - unlink pal and pal-electron from monterey
  - build both pal's
  - create link in pal's
  - installs link in montery
  - runs "gulp watch" in monterey app
