### ISSUE TITLE
Remove pty component from the application

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#423]
### Intention

**I'm submitting a feature request**

**Comment by adriatic** [comment]
As I do not feel comfortable to perform such surgery on Monterey, I am doing it only on the Prototyper, expecting that **[this information](https://github.com/monterey-framework/prototyper/issues/33)** will help with performing the same action on. Monterey

**Comment by adriatic** [comment]
Fixed for Prototyper - see **[here](https://github.com/monterey-framework/prototyper/issues/33#issuecomment-270480468)**

**Comment by vegarringdal** [comment]
Note for later:

Monterey will also need this removed:
* plugin folder
https://github.com/monterey-framework/monterey/tree/master/app/src/plugins/terminal

* plugin loading code
https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/index.ts#L16

* less style file
https://github.com/monterey-framework/monterey/blob/master/app/styles/less/layout/terminal.less

* less loading/ref code
https://github.com/monterey-framework/monterey/blob/master/app/styles/less/layout/index.less#L13

**Comment by JeroenVinke** [comment]
Thanks for those steps @vegarringdal 👍 

The [postinstall task](https://github.com/monterey-framework/monterey/blob/development/package.json#L25) of `npm install` will now install the app dependecies as well
