### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#44]
Is there a good reason that monterey does not start like this:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16591810/ada1e25c-42ab-11e6-9ec7-2f03c7f32628.png"></img>
 <br><br>
</p>

instead of 

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/16591891/11b201fa-42ac-11e6-897d-a7722d1ab1a6.png"></img>
 <br><br>
</p>

**Comment by JeroenVinke** [comment]
When you start monterey for the first time then there are no projects linked to monterey yet. So we could go directly to the [this screen](https://cloud.githubusercontent.com/assets/2712405/16591810/ada1e25c-42ab-11e6-9ec7-2f03c7f32628.png) but [this screen](https://cloud.githubusercontent.com/assets/2712405/16591891/11b201fa-42ac-11e6-897d-a7722d1ab1a6.png) is more user friendly as you only see two options. [this screen](https://cloud.githubusercontent.com/assets/2712405/16591891/11b201fa-42ac-11e6-897d-a7722d1ab1a6.png) should only be shown once but the [session storage does not work correctly](https://github.com/monterey-framework/monterey/issues/34)

**Comment by adriatic** [comment]
> [this screen](https://cloud.githubusercontent.com/assets/2712405/16591891/11b201fa-42ac-11e6-897d-a7722d1ab1a6.png) should only be shown once but the [session storage does not work correctly](https://github.com/monterey-framework/monterey/issues/34)

Thank you - I agree completely (after seeing the above explanation :-)
