### ISSUE TITLE
bad repo after last merge

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#49]
Just cloned the repo after [these changes](https://github.com/monterey-framework/monterey/commit/86e314955f98fd825e2acff55f1032244a10c9e2)

Context: monterey, running `λ npm install && jspm install` command, I get these questions 

```
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [.\jspm_packages]:
Enter config file path [.\config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use a transpiler? [yes]:
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur? [babel]:
```

I understand all questions,  it is safe to take all defaults (true?) but I did not have to do that until this new version of monterey that is approx 1 hour old. What's different?

Added a few minutes later:

monterey fails to start with:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/twbs/bootstrap@3.3.6/css/bootstrap.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/work/monterey-framework/monterey/app/jspm_packages/system.src.js Failed to load resource: net::ERR_FILE_NOT_FOUND
config.js:1 Uncaught ReferenceError: System is not defined
index.html:22 Uncaught ReferenceError: System is not defined
C:\work\monterey-framework\monterey\node_modules\electron-connect\lib\client.js:27 [2016-07-05T21:39:01.854Z] [electron-connect] [client: 1] connected server
```

So, `jspm install` failed because something (jspm section of package.json ?) is missing. I will leave this for @JeroenVinke's update (hopefully tomorrow)

**Comment by JeroenVinke** [comment]
a side effect of https://github.com/monterey-framework/monterey/pull/46 is that config.js lives in the app directory. I have updated the readme: 

```
1. npm install
2. cd app
3. npm install
4. jspm install
5. gulp watch (manually reloading electron with ctrl+R is required) or gulp watch-r to automatically reload electron
```

**Comment by adriatic** [comment]
Thank you for the explanation
