### ISSUE TITLE
Normalize paths through nodeJS's path.normalize

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#50]
found by @vegarringdal :
![img](https://files.gitter.im/aurelia-ui-toolkits/team/LAnb/blob)

**Comment by adriatic** [comment]
the slash / back-slash issue is best treated by allowing back-slashes on "input" and always normalize them on output (meaning convert to slashes). Since monterey will be multi-platform, that is what we should do as well
