### ISSUE TITLE
Make monterey responsive

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#52]
I believe it would be great if we can make Monterey responsive, even though it is a "desktop" app.

Imagine being able to put this small screen next to your browser or editor:
![img](http://i.imgur.com/RYVSSmV.png)

**Comment by vegarringdal** [comment]
Dunno..., main problem with desktop app is when they dont allow you to show even more, så end up opening more view &clicking then I wanted to (my issue on work)
Maybe this is just me :-)

What about a option for a small toolbox for taskbar, or/and small utillity window you can lunch that allways stays on top.

**Comment by JeroenVinke** [comment]
Lets make this low priority for now :+1:

**Comment by adriatic** [comment]
I agree with Jeroen - while there are "rules of behavior" for Electron apps, we do not have to obey them if there is a good reason for that. Well, [this image](https://github.com/monterey-framework/monterey/issues/52#issue-164258024) is a good reason for that.

Should I point out that we are working on the most important piece of an IDE?

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/issues/171 is what I wanted to accomplish with this
