### ISSUE TITLE
Create user preferences screen

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#53]
Users should be able to configure preferences for Monterey

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16653094/1e8e2cce-444f-11e6-9efc-ccb54987d7ff.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16653099/26565cce-444f-11e6-883c-857dcfa1230a.png)

![image](https://cloud.githubusercontent.com/assets/2189477/16653102/2e6a1a7c-444f-11e6-89cc-429827fee2a8.png)

**Comment by adriatic** [comment]
Very cool (I wanted to do that :-1:  - but I self-exiled myself, so all is cool)
