### ISSUE TITLE
Clone/copy project

### ISSUE THREAD

**Issue by vegarringdal** [monterey-framework/monterey#57]
Could it be useful to have a option for cloning a project
When you click on the button you show a dialig where they type in project name and select folder
This simplifies it when you have a project you are working on, but you want to make a copy before you try a crazy idea in the middle of the night :joy:

![image](https://cloud.githubusercontent.com/assets/2901416/16671966/0f5d5f46-44a3-11e6-8a96-4d2142742b01.png)

**Comment by adriatic** [comment]
Not a bad idea, as I almost always do that manually - but this would fit into an IDE - not monterey (I am pretty sure that Jeroen has me under constant surveillance to ensure I do not make a slight turn in monterey development that would make it a baby IDE)

**Comment by vegarringdal** [comment]
This would also rename the package.json for you, so it also shows up as a own project in the list :-)
Then you start adding plugins etc

**Comment by JeroenVinke** [comment]
This is why we have source control though. Also, I'm not sure if it is wise to copy a 200MB node_modules folder

**Comment by vegarringdal** [comment]
> not sure if it is wise to copy a 200MB node_modules folder
yes that might not be a good idea
feel free to close this one
