### ISSUE TITLE
Add app launchers for IDEs

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#58]
App launchers for atom/visual studi/vscode/webstorm can be predefined in monterey just not immediately enabled

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16689814/020ff9ca-4525-11e6-99ad-d812d4642185.png)

all of these are disabled (and therefore hidden) by default, but can be made enabled

**Comment by adriatic** [comment]
As the list of tiles grows, I am more and more anxious to **use** monterey - and I find it a good sign (many people will do too).
