### ISSUE TITLE
cannot build current monterey master branch on my mac

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#63]
I have updated nodejs to version 6.3.0 which came with npm version 3.10.3. Then cloned the monterey master, and ran 

```
1. npm install
2. cd app
3. npm install
4. jspm install
5. gulp watch
```

`gulp watch` results with

```
=> gulp watch
module.js:442
    throw err;
    ^

Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/congral/work/monterey/gulpfile.js:3:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Not sure what is going on and would like to move ahead without spending the rest of the day debugging my mac development environment. So this should stay as a record of what I just encountered

**Comment by adriatic** [comment]
Added later (being more frustrated)

I cannot even extract the [prebuilt monterey](https://github.com/monterey-framework/monterey/releases/download/0.1.3/monterey-darwin-x64.7z) - as I do not have .7z extractor on my mac, Fine, I logged into the store, and picked the most recommended tool [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12). Click on "install" results with that damned message "The iTunes terms and conditions have changed. To proceed, you must read and accept the new terms and conditions", with OK and Cancel button on that popup.

Guess what - no matter what button I clicked on - the popup disappears and no terms to read. Just because I cannot believe that such things happen on OSX, I tried something that I would never do elsewhere: installed a security patch for the El Kapitan ESX (which was offered, completely unrelated to my woes). You guessed correctly - installing that patch resulted with the "terms" popup show up

**Comment by adriatic** [comment]
Now, after cooling down (by taking a recess to have a dinner), having the content of that archive extracted, I came back to see how monterey runs. Well, here is how:

![screen shot 2016-07-11 at 6 51 13 pm](https://cloud.githubusercontent.com/assets/2712405/16751763/dfb9d4b8-47a9-11e6-912b-c8594bde5703.png)

Mac goes to bed now, and I am switching to my PC even if it is too late to make my book on monterey done today

**Comment by adriatic** [comment]
Now, I know that it is not OSX that gives me problems as trying to build and run monterey on my windows machine, I get the [identical experience](https://github.com/monterey-framework/monterey/issues/63#issue-164950302) as I was getting on OSX. 

A few more details - after running the first four commands:
```
1. npm install
2. cd app
3. npm install
4. jspm install
```

my current directory is `monterey-framework\monterey\app`. I I try to run `gulp watch` in that directory, I would get:
```
λ gulp watch
[21:09:13] Local gulp not found in C:\work\monterey-framework\monterey
[21:09:13] Try running: npm install gulp
```
So, I would run `npm install gulp` (which executed just fine), followed by `gulp watch` -- only to get the same feedback shown above - (`Try running: npm install gulp`).

So, I would conclude: `gulp watch` should be executed in ``monterey-framework\monterey` - not ``monterey-framework\monterey\app`. If I do that, as stated before, I get:

```
C:\work\monterey-framework\monterey (master)                                           
λ gulp watch                                                                           
module.js:442                                                                          
    throw err;                                                                         
    ^                                                                                  
                                                                                       
Error: Cannot find module 'require-dir'                                                
    at Function.Module._resolveFilename (module.js:440:15)                             
    at Function.Module._load (module.js:388:25)                                        
    at Module.require (module.js:468:17)                                               
    at require (internal/module.js:20:19)                                              
    at Object.<anonymous> (C:\work\monterey-framework\monterey\gulpfile.js:3:1)        
    at Module._compile (module.js:541:32)                                              
    at Object.Module._extensions..js (module.js:550:10)                                
    at Module.load (module.js:458:32)                                                  
    at tryModuleLoad (module.js:417:12)                                                
    at Function.Module._load (module.js:409:3)                                                                                                                             
```

**Note that I am plying the role of a semi-intelligent tester to deliver you the direct experience**. I am not going to start looking at build scripts, knowing that it is relatively late for me and I still want to install monterey from the zip file on my PC

**Comment by adriatic** [comment]
Well, something at least: I was able to extract the monterey.exe and I had to ___convince___ windows that it is OK to run it. We need to fix this - probably by distributing it via **[windows store](https://www.microsoft.com/en-us/store/apps/windows?icid=en_US_Store_UH_apps_Win)**.

Extracting the app took almost 4 minutes - on my ultra fast SSD drive, so this is less than optimal release method.

**Comment by JeroenVinke** [comment]
Hmm, all devDependencies are no longer in package.json. I think I know how this happened. The 'gulp bump-version' task was incorrect once causing it to copy the package.json in 'app' to the one in the root, and the app does not have those devDependencies such as require-dir etc. I will add those again and verify that it works then

**Comment by JeroenVinke** [comment]
> I had to convince windows that it is OK to run it

How?

**Comment by JeroenVinke** [comment]
> Now, after cooling down (by taking a recess to have a dinner), having the content of that archive extracted, I came back to see how monterey runs. Well, here is how:

Not good :) I was only able to 7zip monterey for mac because the normal ZIP program of windows did not want to zip it (some format issue). I have read about it on the electron-packager repo and someone said that you have to build and zip it on a mac, which will be difficult

**Comment by adriatic** [comment]
we can close this - as the fix https://github.com/monterey-framework/monterey/commit/3b84cc70fc672d03dc617f6439602d652a693362 removed the problem
