### ISSUE TITLE
projects repository contains some garbage

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#64]
I would strongly advise to maintain this data very strictly - and use some alternative repo for testing. We will never know when someone will be running the app and seeing garbage as template is not a good thing :-)

![image](https://cloud.githubusercontent.com/assets/2712405/16752609/c16770a4-47b0-11e6-909d-3f0a36346c04.png)

**Comment by JeroenVinke** [comment]
Oops :)
