### ISSUE TITLE
GitHub credentials dialog opens multiple times

### ISSUE THREAD

**Issue by Thanood** [monterey-framework/monterey#70]
If you don't set your GitHub credentials in `preferences` before accessing jspm view, a dialog is shown which asks for your credentials. This dialog is opened multiple times (the background becomes completely black due to multiple dialog overlays being on top of each other).

It's safe to enter your credentials once and just close the other instances.

**Comment by JeroenVinke** [comment]
that's not good :P

I think the cleanest solution is to remove [these function calls](https://github.com/monterey-framework/monterey/blob/master/app/src/shared/github-api.ts#L20) and have screens call the `confirmAuth()` function.

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/16893666/a2b2bdb6-4b3f-11e6-80b3-d399d19549cc.png)
