### ISSUE TITLE
operation not permitted: rename ...

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#72]
In this situation:

![image](https://cloud.githubusercontent.com/assets/2712405/16843911/0ea4273e-49b1-11e6-974f-8dcb5d952468.png)

I clicked on the Next button and got

![image](https://cloud.githubusercontent.com/assets/2712405/16843926/224a2c16-49b1-11e6-82f9-0c8146407503.png)

Here is the view from the explorer after this problem was reported

![image](https://cloud.githubusercontent.com/assets/2712405/16844029/8c69dea2-49b1-11e6-96d1-feaee064a974.png)

It seems that the temp files algorithm is not conservative enough as I believe that I am encountering a name collision after only a few tries to run monterey

**Comment by JeroenVinke** [comment]
Any chance that there already was a folder called "skeleton-typescript-test" ?

**Comment by JeroenVinke** [comment]
https://github.com/Medium/phantomjs/issues/19#issuecomment-13995639 is about the same error message ("EPERM: operation not permitted, rename") and some people say that their antivirus was the cause for this error.

**Comment by JeroenVinke** [comment]
But regardless, we do need to check if the folder that monterey wants to create already exists and if so, let the user choose a different name

**Comment by JeroenVinke** [comment]
The check has been implemented, and did not have the error anymore
