### ISSUE TITLE
Project configuration panel has a bug

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#74]
![image](https://cloud.githubusercontent.com/assets/2712405/16881564/cbd5740c-4a88-11e6-85d1-5ead783cc42c.png)

**Comment by JeroenVinke** [comment]
Fixed that https://github.com/monterey-framework/monterey/commit/af4503ec2a7fb10b0660f58d5c0f2a82474c13f4#diff-e40f955f4719402d69a9bba6477ad5dbR14 :smile:
