### ISSUE TITLE
we need the enhanced gistrun for monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#75]
#It is very obvious to me that the gistrun tool integrated with monterey will be one of the highlights and cause everyone to use monterey just for that thing alone.

We need to be able to invoke GistRun with defining the initial content of the "blue box" shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/16881939/8a0b4522-4a8a-11e6-952f-2c0f51183410.png)

Of course, like with all other situations, we define what happens when the GistRun tile is clicked (and that knowledge is either set automatically from the monterey's "state information" or, monterey offers the choices

- which item from the [aurelia-kendoui-bundles](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bundles) repository to preload
- invoke GistRun in the context of creating a problem report (this clearly has a far wider applicability than just just our own support issues
- ... (whatever else we decide to use monterey's own GistRun for)

**Comment by adriatic** [comment]
### Task
Add relevant parts of today's discussion in https://gitter.im/JeroenVinke chatroom

**Comment by JeroenVinke** [comment]
Discussing this as Quick apps
