### ISSUE TITLE
double click on any project in the history list should open that project

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#79]
Currently double click on **`esnext`** does nothing:

![screen shot 2016-07-15 at 6 15 10 pm](https://cloud.githubusercontent.com/assets/2712405/16889949/566c8216-4ab8-11e6-8717-0071dc1d5c36.png)

**Comment by JeroenVinke** [comment]
What should be opened and in which application?

**Comment by adriatic** [comment]
I was being dumb (did not realize that the switch of the current project for another one from the history list happens on single click and that this action causes only change in the `currentProjectReference` "pointer"

**Comment by JeroenVinke** [comment]
Ahh :+1:
