### ISSUE TITLE
In preparation for monterey database ...

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#83]
This is something I would really like to play with - if I was in charge of what am I doing in monterey scope. As I am not, this I would not be surprised to see @vegarringdal grab it and be done in two hours of his time (he lives on a space-ship that travels at 0.99 speed of light)

1. Grab a copy of **[pouchdb](https://pouchdb.com/)**
2. Make the Aurelia version of the app described in **[this](http://blog.couchbase.com/sync-with-couchbase-using-only-angularjs-and-pouchdb)** (very cool) article.
3. Make the protype of the monterey plugin based on **[this](https://dzone.com/articles/build-a-desktop-app-with-github-electron-and-couch)** article

Pending @JeroenVinke approval, this could advance is rather quickly. As he **[mentioned already](https://gitter.im/monterey-framework/monterey?at=578e9b3816487c5e51597330)** we do need it interfaced to monterey via API layer, which I expect Jeroen will define.

**Comment by JeroenVinke** [comment]
Discussing our needs (https://github.com/monterey-framework/monterey/issues/152) seems like the best thing to do first. Then we can decide whether or not pouchdb is the right fit

**Comment by adriatic** [comment]
What's going on? I am just typing **agreed** every few seconds!
