### ISSUE TITLE
Collecting stack trace of Monterey crash

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#84]
By collecting a stack trace (or log of actions performed by monterey) we should be able to more easily reproduce a crash

**Comment by adriatic** [comment]
Love your very cautious wording here ,,,

**Comment by JeroenVinke** [comment]
Monterey is going to interact with many external processes, which is always risky to do, so we need to be able to investigate crashes. Maybe we can use aurelia-logger to log all actions (as info) to a .txt file on disk. we already have a custom aurelia-logger. Also, we need to log exceptions to that file (I believe we're already logging global exceptions to aurelia-logger, so that should work out nicely)

In order not to write to disk too much, maybe we should try and limit how much we write to the text file. When monterey crashes (I think we can detect this from electrons index.js) we need to be sure that all logs get written to the text file so for example, write to disk every 10 seconds (assuming there are things to write to disk). but when monterey crashes, electron's main process should take over and write everything to disk

Also, we don't want the log files to become too large. we probably don't need to know what monterey did yesterday, just what has happened on the current day

**Comment by JeroenVinke** [comment]
Implemented by @vegarringdal
