### ISSUE TITLE
a few problems with monterey overview book that need to be fixed

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#88]
I write an email to GitBook support that seems to be ignored so far. So, @JeroenVinke see, whether you can fix my problems with book internal links.

1. [ ] Bottom of the [Creating the application](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/introduction/alpha.html) page I have the paragraph
```
In the [next section](../npm_dependencies_management.md) we click  on the [NPM manager tile](../../monterey_tiles/npm_manager.md) and run the equivalent of the `npm install` command executed in the console application
```
These links are not doing anything at the moment.
<br>
2. [ ]  Git too pissed with GitBook (issues other than links) to continue this book-keeping ...

**Comment by JeroenVinke** [comment]
about 1.:

` [next section](../npm_dependencies_management.md)`  should be `[next section](./beta.md)`. Note that `npm dependencies management` is the `beta.md`  file and is in the same directory as `alpha.md` (the `Creating the application`  page)

![image](https://cloud.githubusercontent.com/assets/2189477/17186390/4ede4288-5435-11e6-85e7-096a4139e482.png)

**Comment by adriatic** [comment]
You are obviously correct - thanks for pointing this out. I am still somewhat frustrated with GitBook and at the some time, I love it as well. All these weird pages (`alpha`, `beta`, ...)  are caused by me being lazy to think ahead what would be the names of the articles belonging to the same chapter, ahead of the time when I created the empty skeletons. Then later, I had a hell of the time trying to rename them, so I left them for a while until I find the right way of doing that on a model - not on the actual book.

**Comment by JeroenVinke** [comment]
Yeah I experience gitbook the same way

**Comment by adriatic** [comment]
It will eventually get to the point where I will just enjoy using it :-)
