### ISSUE TITLE
In preparation for more advanced UI ...

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#9]
As the current version of shell is being built, please try to extract all currently supported user - shell conversations that take place before the shell engages npm to build the requested skeleton. 

#### For example:
![image](https://cloud.githubusercontent.com/assets/2712405/16364918/2587e8a4-3bc0-11e6-9c22-5de5bbd06391.png)

![image](https://cloud.githubusercontent.com/assets/2712405/16364925/63bc13fc-3bc0-11e6-8ca3-ff3f559bc901.png)

![image](https://cloud.githubusercontent.com/assets/2712405/16364932/98420096-3bc0-11e6-915d-21f72e0414eb.png)

and so on. Rather than having me sniff the actual code, or run it, please create and maintain this information in a form of a text document.

This would allow me to create the node.js based simulator and a web based client (I do want to use KendoUI bridge for that for visual effects) that would talk to that simulator. I can even define time delays to "hide" the the fact that we are using a simulator.

From my previous experience, I know that this will dramatically accelerate the monterey creation as this can be done in parallel with the actual "CLI workflow".

I guess I am asking for the API (that would also fit aurelia CLI, by the way)

**Comment by JeroenVinke** [comment]
I believe that the [abstractions](https://github.com/monterey-framework/shell/tree/master/src/shared/abstractions) will make this possible.

**Comment by adriatic** [comment]
This link https://github.com/monterey-framework/shell/tree/master/src/shared/abstractions became bad

**Comment by JeroenVinke** [comment]
we have done this through the PAL

**Comment by adriatic** [comment]
> we have done this through the PAL

Can you please explain the reference **`this`** in the context of your comment?

**Comment by JeroenVinke** [comment]
Any interation with external systems such as JSPM, NPM or Node is abstracted away from monterey using the monterey-pal/monterey-pal-electron setup. Monterey is going through the PAL for every interaction with NodeJS so you should be able to replace monterey-pal-electron with a fake implementation of the PAL. For example, in monterey-pal-electron we have [this function](https://github.com/monterey-framework/monterey-pal-electron/blob/master/src/fs.js#L37-L41):

```
  async showOpenDialog(config) {
    return new Promise(resolve => {
      dialog.showOpenDialog(config, c => resolve(c));
    });
  }
```
This function calls electron to show a folder browser dialog and returns the path that the user selects.

in a different implementation of the PAL this can be replaced with:

```
  async showOpenDialog(config) {
    return new Promise(resolve => {
      setTimeout(() => {
          resolve('some/fake/path/the/user/selected');
      }, 5000); // simulate that the user took 5 seconds to select a file
    });
  }
```
This simulates that the user took 5 seconds to select the 'some/fake/path/the/user/selected' path

**Comment by adriatic** [comment]
**That is my man talking now** (sometimes you are too cryptic for me, but the good thing is that you do not mind writing more when I ask)

Thanks :+1:

**Comment by adriatic** [comment]
Rest assured that one consequence of working at a computer manufacturer writing their OS, one has a very clear understanding of PAL :_)
