### ISSUE TITLE
First run on mac fails

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#90]
Using freshly installed Monterey 0.2.0 I tried to create the esnext-typescript app, by telling Monterey to fetch it from GitHub navigation skeletons repo.

1. Starting Monterey app after installing it results with OSX feeling suspicious

 ![screen shot 2016-07-27 at 3 41 54 pm](https://cloud.githubusercontent.com/assets/2712405/17190578/609756d4-5414-11e6-923d-225a79b376f0.png)
<br>
 Click on the `Open` button solves this, but I was hoping to be treated more friendly given the fact that the app is signed.
<br>
2. The "interview" went fine and I chose not to run `NPM` in that stage. So, I got to see Monterey in it's full glory, where only a few tiles were installed (there are more tiles in Windows).
<br>
3. I started the `NPM` tile and got this - **Note the wheel spinning endlessly**

 ![screen shot 2016-07-27 at 3 57 40 pm](https://cloud.githubusercontent.com/assets/2712405/17190773/1ad46550-5415-11e6-8187-bfe660c9d745.png)

4. Despite the wheel spinning, I was able to click on the `Install` button - and here is what happened:

 ![screen shot 2016-07-27 at 3 58 30 pm](https://cloud.githubusercontent.com/assets/2712405/17190919/b89cc66a-5415-11e6-89d9-9cbe7c3cd539.png)

 Note the amount of time spent (this takes only a few seconds on my PC. As it was still doing something I went for another screenshot

 ![screen shot 2016-07-27 at 3 59 37 pm]
(https://cloud.githubusercontent.com/assets/2712405/17190960/ed0f9b20-5415-11e6-894a-c694ef2c9afe.png)

and only then realized that the `npm install` failed.

No sense in trying anything before this gets properly understood and addressed.

**Comment by JeroenVinke** [comment]
1. This is not a problem with the app, but rather a courtesy to the user, this probably happens with any executable downloaded from the internet

2. Ah yes. The tiles you see in windows are specific for windows (explorer.exe does not exist on mac so no reason to show it on mac). We probably need a finder tile for mac

3. Not sure

4. Does it really take seconds? Npm install on a new project takes minutes for me (especially skeletons as they have a lot of npm modules). When npm install has already been run it is much quicker though

Something is going wrong with npm, will check

**Comment by JeroenVinke** [comment]
About 1, I have seen the app to be blocked conpletely where you need to disable the firewall to get it to launch, also got an error that the app was created by an unkown developer and you had to explicitly allow the app to run. So the warning you are getting now doesnt seem so bad

**Comment by adriatic** [comment]
After returning back to my PC, I tried to repeat the same steps (I did not do the TypeScript skeleton ever before). Here is what took place

![failure-on-pc](https://cloud.githubusercontent.com/assets/2712405/17191491/1f4fed7c-5418-11e6-9bf0-16bf27976844.png)

This shows incomplete error handling (the wheel continues to spin), there is no recovery from here (`Previous` button results with error warning "this is not possible"), so I clicked `Close` - which does not do anything

**Comment by JeroenVinke** [comment]
try and open devtools, it should show you an error in the console

**Comment by adriatic** [comment]
> So the warning you are getting now doesnt seem so bad

I agree and disagree at the same time. The idea of **installing an app** is so dramatically different from **using a web app** that I want absolutely no friction in the installation process. This is not to be considered a critical comment to the current installation process, but rather an encouragement to do better :-)

**Comment by JeroenVinke** [comment]
I have the same ambition, but changing apple's gatekeeper software to remove this generic message is not within my power :smile:

**Comment by JeroenVinke** [comment]
Yeah i'd like to, but I have no idea what we would need to do. This really looks like a feature of mac to give users a last chance not to open something (even though the app was signed), as every article on how to remove this warning is about making changes to the OS, not the app

**Comment by JeroenVinke** [comment]
Something we can look into later is deploying monterey through the app store. This would remove this warning as it wouldn't be downloaded from the internet

**Comment by JeroenVinke** [comment]
found this

![img](http://i.imgur.com/NoK3SLE.png)

The app store (https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md) seems to have some gotchas we need to think about ([link](https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md#limitations-of-mas-build))

**Comment by adriatic** [comment]
You are getting very close to the solution. As I am a registered app developer let me pick it up from here

**Comment by JeroenVinke** [comment]
Just so we're not miscommunicating, the image I showed explains that the only successful outcome of the test is the message you showed. I've had the other errors but those went away went the signing process got executed correctly. Let me know if you find anything

**Comment by adriatic** [comment]
I understand and agree!

**Comment by JeroenVinke** [comment]
I believe we tackled all issues that we had to tackle :smile:
