### ISSUE TITLE
Check if project folder exists already when scaffolding project

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#97]

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/17205498/a8f4922e-54ab-11e6-90fe-c953b1552b26.png)

![image](https://cloud.githubusercontent.com/assets/2189477/17205509/b3fcce16-54ab-11e6-8516-c784c88e5ca1.png)

**Comment by adriatic** [comment]
Excellent!
